feat(melange): use cmdline to pass ssh keys, dns, hostname variables
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

diff --git a/melange/init b/melange/init
--- a/melange/init
+++ b/melange/init
@@ -17,6 +17,16 @@ if [ -x /sbin/ldconfig ]; then
 	/sbin/ldconfig /lib /usr/lib /usr/lib64 || :
 fi
 
+# Fetch settings from cmdline
+DNS="$(tr ' ' '\n' < /proc/cmdline | /bin/grep "dns=" | /usr/bin/cut -d'=' -f2-)"
+HOSTNAME="$(tr ' ' '\n' < /proc/cmdline | /bin/grep "hostname=" | /usr/bin/cut -d'=' -f2-)"
+SSHKEY="$(tr ' ' '\n' < /proc/cmdline | /bin/grep "sshkey=" | /usr/bin/cut -d'=' -f2- | /bin/base64 -d)"
+
+if [ -z "${SSHKEY}" ]; then
+	/bin/echo "Missing default mount for ssh keys"
+	exit 1
+fi
+
 # We can ignore this fail, if we use a kernel with kvm_guest.config, we won't need this
 # and network will work anyway
 # If this fails and we won't have network, the ifconfig command will fail anyway.
@@ -28,27 +38,8 @@ fi
 # modprobe 9p if absent
 /bin/grep -q 9p /proc/filesystems || /usr/sbin/modprobe 9p
 
-/bin/ifconfig lo up
-/bin/ifconfig eth0 10.0.2.15 netmask 255.255.255.0
-/bin/route add default gw 10.0.2.2 eth0
-
-# Setup hostname
-/bin/hostname wolfi-qemu
-/bin/sed  -i 's| localhost | localhost wolfi-qemu |g' /etc/hosts
-
-# Setup DNS
-/bin/echo "nameserver 1.1.1.1" >> /etc/resolv.conf
-
-# Setup UTC timezone
-/bin/ln -sf /usr/share/zoneinfo/UTC /etc/localtime
-
 # Setup default mountpoint for 9p shared dir
 /bin/mount -t 9p -o trans=virtio defaultshare /mnt/ -oversion=9p2000.L
-
-if [ ! -e /mnt/ssh/authorized_keys ]; then
-	/bin/echo "Missing default mount for ssh keys"
-	exit 1
-fi
 
 # If we have an external disk, we want to perform builds in that
 if [ -e /dev/vda ]; then
@@ -58,17 +49,28 @@ if [ -e /dev/vda ]; then
 	/bin/mount -o nobarrier,noatime,nodiratime,nobh -t ext4 /dev/vda /home/build
 fi
 
-# Setup SSH keys for external access
-/bin/mkdir -p -m 0700 /root/.ssh/ /home/build/.ssh/
-/bin/cp /mnt/ssh/authorized_keys /root/.ssh/
-/bin/cp /mnt/ssh/authorized_keys /home/build/.ssh/
-/bin/chmod 0400 /root/.ssh/authorized_keys /home/build/.ssh/authorized_keys
-
 # Fix home permissions from cpio command
 /bin/chown -R build:build /home/build
 
+# Setup default network
+/bin/ifconfig lo up
+/bin/ifconfig eth0 10.0.2.15 netmask 255.255.255.0
+/bin/route add default gw 10.0.2.2 eth0
+
+/bin/hostname "${HOSTNAME:-"wolfi-vm"}"
+echo "127.0.0.1 ${HOSTNAME:-"wolfi-vm"}" >> /etc/hosts
+/bin/echo "nameserver ${DNS:-"1.1.1.1"}" > /etc/resolv.conf
+
+##############
+# Entrypoint #
+##############
+# Setup SSH keys for external access
+/bin/mkdir -p -m 0700 /root/.ssh/ /home/build/.ssh/
+/bin/echo "${SSHKEY}" > /root/.ssh/authorized_keys
+/bin/echo "${SSHKEY}" > /home/build/.ssh/authorized_keys
+/bin/chmod 0400 /root/.ssh/authorized_keys /home/build/.ssh/authorized_keys
+/bin/chown -R build:build /home/build/.ssh/
 # Setting up AcceptEnv
 /bin/echo "AcceptEnv *" >> /etc/ssh/sshd_config
-
 /usr/bin/ssh-keygen -A
 exec /usr/sbin/sshd -D
