amazon-cloudwatch-agent-operator: use test/daemon-check-output
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/amazon-cloudwatch-agent-operator.yaml b/amazon-cloudwatch-agent-operator.yaml
--- a/amazon-cloudwatch-agent-operator.yaml
+++ b/amazon-cloudwatch-agent-operator.yaml
@@ -52,8 +52,7 @@ test:
   pipeline:
     - uses: test/kwok/cluster
     - name: Fetch the testdata from the source repo
-      runs: |
-        git clone --depth=1 https://github.com/aws/amazon-cloudwatch-agent-operator
+      runs: git clone --depth=1 https://github.com/aws/amazon-cloudwatch-agent-operator
     - name: Install CRDs
       working-directory: amazon-cloudwatch-agent-operator/config/crd/
       runs: |
@@ -61,22 +60,28 @@ test:
         kustomize build | kubectl apply --server-side=true -f -
         # wait for all CRDs to be created
         sleep 3
-    - name: Verify Installation
-      runs: |
-        mkdir -p /tmp/k8s-webhook-server/serving-certs/
-        mkcert -install
-        mkcert -key-file /tmp/k8s-webhook-server/serving-certs/tls.key -cert-file /tmp/k8s-webhook-server/serving-certs/tls.crt localhost
-        /usr/bin/manager &
-        sleep 3
-        # Perform the curl request and capture the HTTP status code
-        STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" http://localhost:8081/healthz)
-        
-        # Check if the status code is 200, if so exit 0, otherwise exit 1
-        if [ "$STATUS" -eq 200 ]; then
-            echo "Health check passed with status code 200"
-            exit 0
-        else
-            echo "Health check failed with status code $STATUS"
-            exit 1
-        fi
-
+    - name: "Test manager run"
+      uses: test/daemon-check-output
+      with:
+        setup: |
+          mkdir -p /tmp/k8s-webhook-server/serving-certs/
+          mkcert -install
+          mkcert -key-file /tmp/k8s-webhook-server/serving-certs/tls.key -cert-file /tmp/k8s-webhook-server/serving-certs/tls.crt localhost
+        start: /usr/bin/manager
+        timeout: 30
+        expected_output: |
+          starting manager
+          Starting webhook server
+          starting server
+          Starting workers
+        post: |
+          sleep 3
+          STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" http://localhost:8081/healthz)
+          # Check if the status code is 200, if so exit 0, otherwise exit 1
+          if [ "$STATUS" -eq 200 ]; then
+              echo "Health check passed with status code 200"
+              exit 0
+          else
+              echo "Health check failed with status code $STATUS"
+              exit 1
+          fi
