feat: add standard queue test to package

diff --git a/apache-activemq-artemis.yaml b/apache-activemq-artemis.yaml
--- a/apache-activemq-artemis.yaml
+++ b/apache-activemq-artemis.yaml
@@ -24,7 +24,7 @@ environment:
       - fontconfig-dev
       - libfontconfig1
       - maven
-      - openjdk-21-default-jdk
+      - openjdk-17-default-jdk
       - openssl
       - procps
 
@@ -40,37 +40,52 @@ pipeline:
       mkdir -p "${{targets.contextdir}}"/opt/activemq-artemis
       cp -r artemis-distribution/target/apache-artemis-${{package.version}}-bin/apache-artemis-${{package.version}}/* "${{targets.contextdir}}"/opt/activemq-artemis/
 
-# subpackages:
-#   - name: "${{package.name}}-compat"
-#     description: "Compatibility package to place binaries in location expected by the container"
-#     pipeline:
-#       - runs: |
-#           cp docker/docker-run.sh "${{targets.contextdir}}"/
+subpackages:
+  - name: "${{package.name}}-compat"
+    description: "Compatibility package to place binaries in location expected by the container"
+    pipeline:
+      - runs: |
+          cp docker/docker-run.sh "${{targets.contextdir}}"/
 
-# update:
-#   enabled: true
-#   github:
-#     identifier: apache/tika
-#     use-tag: true
-#     tag-filter: 3.0.
+update:
+  enabled: true
+  ignore-regex-patterns:
+    - -doc
+  github:
+    identifier: apache/activemq-artemis
+    use-tag: true
 
-# test:
-#   environment:
-#     contents:
-#       packages:
-#         - curl
-#         - ${{package.name}}-compat
-#         - openjdk-17-default-jvm
-#   pipeline:
-#     - name: "start server and verify endpoint"
-#       runs: |
-#         (
-#         java -jar /tika-server-standard.jar &
-#         ) && \
-#         sleep 2 && \
-#         curl -s http://localhost:9998/ | \
-#         grep "<h1>Welcome to the Apache Tika 3.0.0 Server</h1>" && \
-#         sleep 2 && \
-#         echo "this is a test file!" > sample.txt && \
-#         curl -X PUT --data-binary @sample.txt -H "Content-Type: text/plain" http://localhost:9998/tika | \
-#         grep "this is a test file!"
+test:
+  environment:
+    contents:
+      packages:
+        - git
+        - maven
+        # - ${{package.name}}-compat
+        - openjdk-21-default-jdk
+  pipeline:
+    - name: "Setup activemq-artemis broker and start service"
+      runs: |
+        apk add git maven
+        mkdir /var/lib/artemis-instance 
+        export BROKER_HOME=/var/lib/
+        export CONFIG_PATH=$BROKER_HOME/etc
+        cd /var/lib/artemis-instance
+        /opt/activemq-artemis/bin/artemis create --user artemis --password artemis --allow-anonymous .
+        /var/lib/artemis-instance/bin/artemis-service start
+    - name: "Clone official apache activemq-artemis examples"
+      runs: |
+        git clone https://github.com/apache/activemq-artemis-examples.git
+    - name: "Run standard queue read and write test against running activemq-artemis service"
+      runs: |
+        cd activemq-artemis-examples/examples/features/standard/queue
+        mvn -PnoServer verify > test_output.txt
+        if grep -q "Sent message: This is a text message" "test_output.txt" &&\
+            grep -q "Received message: This is a text message" "test_output.txt"; then
+          echo "Successfully wrote to and read from activemq-artemis queue."
+          exit 0
+        else
+          echo "Failed to write to and read from active-artemis queue."
+          exit 1
+        fi
+
