busybox - address CVEs (#27356)
- Remove obsolete patch busybox/CVE-2022-30065.patch
- busybox - add openssf-compiler-options
- busybox - move to git checkout, fix several CVE

diff --git a/busybox.yaml b/busybox.yaml
--- a/busybox.yaml
+++ b/busybox.yaml
@@ -1,7 +1,7 @@
 package:
   name: busybox
   version: 1.36.1
-  epoch: 10
+  epoch: 11
   description: "swiss-army knife for embedded systems"
   copyright:
     - license: GPL-2.0-only
@@ -18,26 +18,48 @@ package:
         #!/bin/busybox sh
         /bin/busybox --install -s
 
+var-transforms:
+  - from: ${{package.version}}
+    match: \.
+    replace: _
+    to: mangled-package-version
+
 environment:
   contents:
     packages:
       - build-base
       - busybox
       - ca-certificates-bundle
+      - openssf-compiler-options
+      - perl # provides pod2html/pod2text
 
 pipeline:
-  - uses: fetch
+  - uses: git-checkout
     with:
-      uri: https://distfiles.alpinelinux.org/distfiles/edge/busybox-${{package.version}}.tar.bz2
-      expected-sha256: b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314
+      expected-commit: 1a64f6a20aaf6ea4dbba68bbfa8cc1ab7e5c57c4
+      repository: https://git.busybox.net/busybox
+      tag: ${{vars.mangled-package-version}}
+      cherry-picks: |
+        master/5dcc443dba039b305a510c01883e9f34e42656ae: CVE-2021-42380 awk: fix use-after-realloc
+        master/84ff1825dd82e8de45020e3def34d1430d8e5a99: awk: fix splitting with default FS
+        # CVE from http://lists.busybox.net/pipermail/busybox/2024-May/090761.html
+        master/0256e00a9d077588bd3a39f5a1ef7e2eaa2911e4: CVE-2023-42364 CVE-2023-42365 awk: fix precedence of = relative to ==
+        master/5f84c5633663f6ee8c9cc3a4608b86d4b56b39d6: awk: fix backslash handling in sub() builtins
+        master/fb08d43d44d1fea1f741fafb9aa7e1958a5f69aa: CVE-2023-42363 awk: fix use after free
+        # CVE number comes from ubuntu debian/patches/CVE-2022-48174.patch
+        master/d417193cf37ca1005830d7e16f5fa7e1d8a44209: CVE-2022-48174 shell: avoid segfault on ${0::0/0~09J}.
+        # fix regression made in 0256e00a9d077588bd3a39f5a1ef7e2eaa2911e4
+        master/38335df9e9f45378c3407defd38b5b610578bdda: awk: restore assignment precedence to be lower than ternary
 
   - uses: patch
     with:
-      patches: CVE-2022-28391-1.patch
+      patches: CVE-2022-28391-1.patch CVE-2022-28391-2.patch
 
+  # from aports.git busybox/0037-awk.c-fix-CVE-2023-42366-bug-15874.patch
+  # http://lists.busybox.net/pipermail/busybox/2024-March/090654.html
   - uses: patch
     with:
-      patches: CVE-2022-28391-2.patch
+      patches: 0037-awk.c-fix-CVE-2023-42366-bug-15874.patch
 
   - name: Configure
     runs: |
@@ -140,6 +162,12 @@ test:
             command -v "$p" &&
               { echo "command '$p' is present. It should not be."; exit 1; }
         done
+    - name: "awk = and ?: precedence"
+      runs: |
+        found=$(awk 'BEGIN { a=0?"bug":"ok"; print a}')
+        [ "$found" = "ok" ] &&
+          echo "PASS: ternary precedence" ||
+          { echo "FAIL: ternary precedence" ; exit 1; }
 
 update:
   enabled: true
