adding calico-3.29 subpackage tests
Signed-off-by: Kyle Steere <kyle.steere@chainguard.dev>

diff --git a/calico-3.29.yaml b/calico-3.29.yaml
--- a/calico-3.29.yaml
+++ b/calico-3.29.yaml
@@ -439,6 +439,9 @@ subpackages:
             /opt/cni/bin/calico -v
             /opt/cni/bin/calico-ipam -v
             /opt/cni/bin/install & exit 0;
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   - name: "calico-apiserver-${{vars.short-package-version}}"
     dependencies:
@@ -461,6 +464,9 @@ subpackages:
         - name: testing calico-apiserver
           runs: |
             calico-apiserver --help
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   # https://github.com/projectcalico/calico/blob/master/apiserver/Dockerfile#L8
   - name: "calico-apiserver-compat-${{vars.short-package-version}}"
@@ -484,6 +490,9 @@ subpackages:
         - name: testing calico-apiserver
           runs: |
             /code/apiserver --help
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   - name: "calico-key-cert-provisioner-${{vars.short-package-version}}"
     dependencies:
@@ -500,6 +509,14 @@ subpackages:
           modroot: .
           packages: ./key-cert-provisioner/cmd/
           output: calico-key-cert-provisioner
+    test:
+      pipeline:
+        - name: testing calico-apiserver
+          runs: |
+            calico-key-cert-provisioner --help
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   - name: "calico-app-policy-${{vars.short-package-version}}"
     dependencies:
@@ -522,6 +539,14 @@ subpackages:
           modroot: .
           packages: ./app-policy/cmd/healthz
           output: calico-healthz
+    test:
+      pipeline:
+        - name: testing calico-healthz
+          runs: |
+            calico-healthz --help
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   - name: "calico-kube-controllers-${{vars.short-package-version}}"
     dependencies:
@@ -545,6 +570,15 @@ subpackages:
           packages: ./kube-controllers/cmd/check-status
           output: check-status # keep naming convention as "check-status" is usually harded to /usr/bin/check-status
           ldflags: "-X main.VERSION=$(git describe --tags --dirty --always --abbrev=12)"
+    test:
+      pipeline:
+        - name: testing calico-healthz
+          runs: |
+            check-status -v
+            calico-kube-controllers -version
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
 
   - name: "calico-pod2daemon-${{vars.short-package-version}}"
     description: "The calico pod2daemon components"
@@ -575,6 +609,17 @@ subpackages:
       - runs: |
           mkdir -p "${{targets.subpkgdir}}"/usr/bin
           install -m755 ./pod2daemon/flexvol/docker-image/flexvol.sh "${{targets.subpkgdir}}"/usr/bin/flexvol.sh
+    test:
+      pipeline:
+        - name: testing calico-pod2daemon packages
+          runs: |
+            calico-pod2daemon-flexvol --help
+            calico-pod2daemon-csidriver --help
+            calico-pod2daemon-nodeagent && exit 0;
+        - uses: test/tw/ldd-check
+          with:
+           packages: ${{subpkg.name}}
+
 
   - name: "calico-pod2daemon-flexvol-compat-${{vars.short-package-version}}"
     dependencies:
@@ -605,6 +650,11 @@ subpackages:
           packages: ./calicoctl/calicoctl
           output: calicoctl
           ldflags: "-X github.com/projectcalico/calico/calicoctl/commands.VERSION=$(git describe --tags --dirty --always --abbrev=12) -X github.com/projectcalico/calico/calicoctl/commands.GIT_REVISION=$(git rev-parse --short HEAD) -X github.com/projectcalico/calico/calicoctl/commands/common.VERSION=$(git describe --tags --dirty --always --abbrev=12) -X main.VERSION=$(git describe --tags --dirty --always --abbrev=12)"
+    test:
+      pipeline:
+        - name: testing calico-pod2daemon-compat
+          runs: |
+            calicoctl --help
 
   - name: "calico-typhad-${{vars.short-package-version}}"
     description: "The calico typha daemon"
@@ -636,6 +686,23 @@ subpackages:
 
           mkdir -p "${{targets.subpkgdir}}"/licenses
           cp ./typha/LICENSE "${{targets.subpkgdir}}"/licenses
+    test:
+      pipeline:
+        - name: testing calico-typhad daemon
+          uses: test/daemon-check-output
+          with:
+            setup: |
+              echo "LogSeveritySys=None" >> /etc/calico/typha.cfg
+            start: "/usr/bin/calico-typha"
+            timeout: 10
+            expected_output: |
+              Successfully loaded configuration
+        - name: Verify license exists
+          runs: |
+            if [ ! -f /licenses/LICENSE ]; then
+              echo "License file not found"
+              exit 1
+            fi
 
   - name: "calico-typha-client-${{vars.short-package-version}}"
     description: "The calico typha client"
@@ -660,6 +727,11 @@ subpackages:
             go build -v -tags osusergo,netgo,cgo -v -buildvcs=false \
             -o "${{targets.subpkgdir}}"/usr/bin/typha-client \
             ./typha/cmd/typha-client
+    test:
+      pipeline:
+        - name: testing calico-typha-client
+          runs: |
+            typha-client --help
 
 update:
   enabled: true
