remove lib runtimes and add curl test
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/calico-3.30.yaml b/calico-3.30.yaml
--- a/calico-3.30.yaml
+++ b/calico-3.30.yaml
@@ -763,14 +763,7 @@ subpackages:
         - coreutils
         - dash-binsh
         - sed
-        - libacl1
-        - libattr1
         - libcap
-        - libcrypt1
-        - libcrypto3
-        - libpcre2-8-0
-        - libselinux
-        - libssl3
         - ncurses
         - zlib
         - glibc
@@ -789,7 +782,7 @@ subpackages:
               # https://github.com/projectcalico/calico/blob/master/whisker/docker-image/Dockerfile
               mkdir -p "${{targets.contextdir}}"/etc/nginx/
               mkdir -p "${{targets.contextdir}}"/etc/nginx/conf.d/
-              install -Dm644 docker-image/nginx-start.sh "${{targets.contextdir}}"/usr/bin/nginx-start.sh
+              install -Dm755 docker-image/nginx-start.sh "${{targets.contextdir}}"/usr/bin/nginx-start.sh # 644 fails on tests
               install -Dm644 docker-image/nginx.conf ${{targets.contextdir}}/etc/nginx/
               install -Dm644 docker-image/default.conf ${{targets.contextdir}}/etc/nginx/conf.d/
               install -Dm644 LICENSE "${{targets.contextdir}}"/licenses/LICENSE
@@ -824,6 +817,7 @@ subpackages:
                 echo "[OK] $so found"
               else
                 echo "[MISSING] $so not found"
+                exit 1
               fi
             done
         - name: "start daemon on localhost"
@@ -839,7 +833,7 @@ subpackages:
               start worker processes
             post: |
               wait-for-it -t 10 --strict localhost:8081 -- echo "NGINX is up"
-              curl -sfL -k "https://localhost:8081" | grep -qi "Welcome to nginx!"
+              curl -sfL --retry 3 http://localhost:8081 | grep -qi "Calico Whisker"
 
   - name: "calico-whisker-backend-${{vars.short-package-version}}"
     description: "Whisker backend"
