add whisker
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/calico-3.30.yaml b/calico-3.30.yaml
--- a/calico-3.30.yaml
+++ b/calico-3.30.yaml
@@ -53,6 +53,7 @@ environment:
       - llvm-18
       - zlib-dev
       - zstd-dev
+      - yarn
 
 # The calico build process is heavily tailored towards using Makefiles to
 # orchestrate docker commands. This makes for a less than ideal
@@ -687,6 +688,7 @@ subpackages:
             typha-client --help
 
   - name: "calico-goldmane-${{vars.short-package-version}}"
+    description: "Goldmane"
     dependencies:
       provides:
         - calico-goldmane=${{package.full-version}}
@@ -746,6 +748,88 @@ subpackages:
             post: |
               wait-for-it -t 10 --strict localhost:8080 -- echo "Server is up"
               wait-for-it -t 10 --strict localhost:443 -- echo "Server is up"
+
+  - name: "calico-whisker-${{vars.short-package-version}}"
+    description: "Tigera OSS-UI (Whisker)"
+    dependencies:
+      provides:
+        - calico-whisker=${{package.full-version}}
+      runtime:
+        - nginx-stable
+        - coreutils
+        - dash-sh
+        - sed
+        - libacl1
+        - libattr1
+        - libcap
+        - libcrypt1
+        - libcrypto3
+        - libpcre2-8-0
+        - libselinux
+        - libssl3
+        - ncurses
+        - zlib
+        - glibc
+        - merged-bin
+        - merged-usrsbin
+        - wolfi-baselayout
+    pipeline:
+      - working-directory: whisker
+        pipeline:
+          - name: Build the UI
+            runs: |
+              yarn install --frozen-lockfile
+              yarn build
+          - name: Install the files
+            runs: |
+              # https://github.com/projectcalico/calico/blob/master/whisker/docker-image/Dockerfile
+              install -Dm755 docker-image/nginx-start.sh "${{targets.contextdir}}"/usr/bin/nginx-start.sh
+              install -Dm755 docker-image/nginx.conf ${{targets.contextdir}}/etc/nginx/
+              install -Dm755 docker-image/default.conf ${{targets.contextdir}}/etc/nginx/conf.d/
+              install -Dm755 LICENSE "${{targets.contextdir}}"/licenses/LICENSE
+              mkdir -p "${{targets.contextdir}}"/usr/share/nginx/html
+              cp -avR dist/* "${{targets.contextdir}}"/usr/share/nginx/html/
+              ln -sf /usr/bin/nginx "${{targets.contextdir}}"/usr/sbin/nginx
+    test:
+      environment:
+        contents:
+          packages:
+            - wait-for-it
+            - grep
+            - curl
+      pipeline:
+        - name: Test important files
+          runs: |
+            test "$(readlink /usr/sbin/nginx)" = "/usr/bin/nginx"
+            stat /usr/bin/nginx-start.sh
+            if [ -z "$(ls -A /usr/share/nginx/html/)" ]; then
+              echo "/usr/share/nginx/html/ is empty"
+              exit 1
+            fi
+        - name: Extract the SO files from the Dockerfile and check if they exist
+          runs: |
+            #!/bin/bash
+            set -euo pipefail
+            dockerfile=$(curl -fsSL "https://raw.githubusercontent.com/projectcalico/calico/refs/tags/v${{package.version}}/whisker/docker-image/Dockerfile")
+            so_files=$(echo "$dockerfile" | grep -oP '/lib64/lib\w+\.so(\.\d+)*' | xargs -n1 basename | sed -E 's/\.so(\..*)*/.so/')
+            so_files=$(echo "$so_files" | sort -u)
+            echo "Checking .so files:"
+            for so in $so_files; do
+              if ldconfig -p | grep -q "$so"; then
+                echo "[OK] $so found"
+              else
+                echo "[MISSING] $so not found"
+              fi
+            done
+        - name: "start daemon on localhost"
+          uses: test/daemon-check-output
+          with:
+            start: "/usr/bin/nginx-start.sh"
+            timeout: 30
+            expected_output: |
+              nginx
+            post: |
+              wait-for-it -t 10 --strict localhost:8080 -- echo "Server is up"
 
 update:
   enabled: true
