composer: switch to git-checkout (#73781)
* composer: handle melange using `set -o pipefail`

Signed-off-by: Colin Watson <colin.watson@chainguard.dev>

* composer: switch to git-checkout

Signed-off-by: Colin Watson <colin.watson@chainguard.dev>

* composer: bump to 2.9.7

Signed-off-by: Colin Watson <colin.watson@chainguard.dev>

---------

Signed-off-by: Colin Watson <colin.watson@chainguard.dev>

Export:  cac611eed1073ca6794189c2da699aac989281e5

diff --git a/composer.yaml b/composer.yaml
--- a/composer.yaml
+++ b/composer.yaml
@@ -1,6 +1,6 @@
 package:
   name: composer
-  version: "2.9.5"
+  version: "2.9.7"
   epoch: 0
   description: "the PHP package manager"
   copyright:
@@ -19,14 +19,37 @@ environment:
     packages:
       - busybox
       - ca-certificates-bundle
+      - composer # circular dependency to allow building from git
+      - php
+      - php-iconv
+      - php-simplexml
+  environment:
+    COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"
 
+# Build procedure based on upstream release workflow:
+# https://github.com/composer/composer/blob/main/.github/workflows/release.yml
 pipeline:
-  - uses: fetch
+  - uses: git-checkout
     with:
-      uri: https://getcomposer.org/download/${{package.version}}/composer.phar
-      expected-sha256: c86ce603fe836bf0861a38c93ac566c8f1e69ac44b2445d9b7a6a17ea2e9972a
-      extract: "false"
-      delete: "false"
+      repository: https://github.com/composer/composer
+      tag: ${{package.version}}
+      expected-commit: 82a2fbd1372a98d7915cfb092acf05207d9b4113
+
+  - name: Install dependencies from composer.lock using composer binary provided by system
+    runs: |
+      composer install $COMPOSER_FLAGS
+
+  - name: Run install again using composer binary from source
+    runs: |
+      bin/composer install $COMPOSER_FLAGS
+
+  - name: Validate composer.json
+    runs: |
+      bin/composer validate
+
+  - name: Build phar file
+    runs: |
+      php -d phar.readonly=0 bin/compile
 
   - name: Install Composer
     runs: |
@@ -54,7 +77,18 @@ test:
     - name: "Validate composer.json"
       runs: |
         cd test-project
-        composer validate 2>&1 | grep -i "Publish errors"
+        ret=0
+        composer validate >../composer-validate-output 2>&1 || ret=$?
+        if [ "$ret" != 2 ]; then
+          echo "FAIL: expected 'composer validate' to exit 2, but got $ret" >&2
+          exit 1
+        fi
+        if ! grep -i "Publish errors" ../composer-validate-output; then
+          echo "FAIL: composer.json did not have expected publish errors" >&2
+          cat ../composer-validate-output >&2
+          exit 1
+        fi
+        echo "PASS: composer.json had publish errors as expected"
     - name: "Test Composer require command"
       runs: |
         cd test-project
