Move couchdb test to test/daemon-check-output

diff --git a/couchdb.yaml b/couchdb.yaml
--- a/couchdb.yaml
+++ b/couchdb.yaml
@@ -77,58 +77,39 @@ test:
         - jq
   pipeline:
     - name: CouchDB Start Server
-      runs: |
-        #!/bin/bash
-
-        mkdir /var/log/couchdb
-
-        # Configure CouchDB
-        # https://docs.couchdb.org/en/stable/setup/single-node.html#configure-couchdb
-        sed -i '/\[couchdb\]/a single_node = true' /usr/share/couchdb/etc/local.ini
-
-        # https://docs.couchdb.org/en/stable/setup/single-node.html#configure-admins
-        sed -i '/\[admins\]/,/^;/s/^;//' /usr/share/couchdb/etc/local.ini
-
-        # Start CouchDB in the background
-        couchdb > /var/log/couchdb/couchdb.log 2>&1 &
-
-        # Check for "cluster stable" in the logs
-        TIMEOUT=30 # Timeout in seconds
-        START_TIME=$(date +%s)
-
-        while true; do
-            # Check if the current time is past the timeout
-            CURRENT_TIME=$(date +%s)
-            if [ $((CURRENT_TIME - START_TIME)) -ge $TIMEOUT ]; then
-                echo "Timeout reached without finding 'cluster stable' in the logs."
-                exit 1
-            fi
-
-            # Check the logs for "cluster stable"
-            if grep -q "cluster stable" /var/log/couchdb/couchdb.log; then
-                echo "'Cluster stable' found in the logs."
-                break
-            fi
-
-            sleep 1  # Wait for 1 second before checking again
-        done
-    - name: CouchDB Test UIs
-      runs: |
-        #!/bin/bash
-
-        # Now test the UI
-        # Make a request to CouchDB and store the response
-        response=$(curl -s http://127.0.0.1:5984/)
-
-        # Use jq to parse the response and extract the value associated with the key "couchdb"
-        couchdb_value=$(echo $response | jq -r '.couchdb')
-
-        # Check if the extracted value is "Welcome"
-        if [ "$couchdb_value" == "Welcome" ]; then
-            echo "Test passed: 'couchdb':'Welcome' is present in the response."
-        else
-            echo "Test failed: 'couchdb':'Welcome' is not present in the response."
-        fi
+      uses: test/daemon-check-output
+      with:
+        start: "env HOME=/root couchdb"
+        timeout: 30
+        expected_output: "cluster stable"
+        setup: |
+          #!/bin/sh -ex
+          cat >/usr/share/couchdb/etc/local.ini <<"EOF"
+          [couchdb]
+          single_node = true
+          [admins]
+          admin = s3cret
+          EOF
+        post: |
+          #!/bin/sh -e
+          url=http://127.0.0.1:5984/
+          echo "testing $url"
+          response=$(curl -s "$url") || {
+            echo "curl http://127.0.0.1:5984/ failed $?"
+            exit 1
+          }
+          found=$(echo "$response" | jq -r .couchdb) || {
+            echo "response from $url failed [$?] to parse with jq"
+            echo "response: $response"
+            exit 1
+          }
+          expected="Welcome"
+          if [ "$found" = "$expected" ]; then
+              echo "Got \"$expected\" in response from $url"
+          else
+              echo "Got \"$found\" in response from $url. Expected \"$expected\""
+              exit 1
+          fi
 
 update:
   enabled: true
