fix the build
Signed-off-by: Batuhan Apaydin <batuhan.apaydin@chainguard.dev>

diff --git a/crac-criu.yaml b/crac-criu.yaml
--- a/crac-criu.yaml
+++ b/crac-criu.yaml
@@ -28,6 +28,7 @@ environment:
       - libnet-dev
       - libnl3
       - libnl3-dev
+      - libnl3-static
       - libprotobuf
       - libxml2-utils
       - nftables
@@ -52,9 +53,7 @@ pipeline:
       tag: release-${{package.version}}
 
   - runs: |
-      # shellcheck disable=SC2001
-      export CFLAGS=$(echo "$CFLAGS" | sed 's/-Wp,-D_FORTIFY_SOURCE=[0-9]//g')
-      make criu crit amdgpu_plugin docs
+      make DESTDIR=${{targets.destdir}} PREFIX=/usr install-criu V=1
 
   - uses: strip
 
@@ -63,3 +62,12 @@ update:
   github:
     identifier: CRaC/criu
     strip-prefix: release-
+
+test:
+  pipeline:
+    - runs: |
+        # check at least if the binary is there in usr/sbin/criu
+        if [ ! -f "/usr/sbin/criu" ]; then
+          echo "criu binary not found"
+          exit 1
+        fi
