fix deno and add test
Signed-off-by: debasishbsw <debasishbsws.dev@gmail.com>

diff --git a/deno.yaml b/deno.yaml
--- a/deno.yaml
+++ b/deno.yaml
@@ -26,8 +26,8 @@ environment:
 pipeline:
   - uses: fetch
     with:
-      uri: https://github.com/denoland/deno/releases/download/v${{package.version}}/deno_src.tar.gz
-      expected-sha256: 32f9d6c7c6b9b3a010999a721a1024f7ad3b8a95d0dc1cf9c56d60dd8a362880
+      uri: https://github.com/denoland/deno/archive/refs/tags/v${{package.version}}.tar.gz
+      expected-sha256: 8f9ce4e92412bbc1231dd50db57294f61690b473c6fbad4a9da230e07a031da8
 
   - name: Configure and build
     runs: |
@@ -42,3 +42,16 @@ update:
   github:
     identifier: denoland/deno
     strip-prefix: v
+
+test:
+  pipeline:
+    - runs: |
+        deno --version
+        echo 'console.log("Hello, World!");' > hello_world.js
+        output=$(deno run hello_world.js)
+        if [ "$output" = "Hello, World!" ]; then
+          echo "Test passed!"
+        else
+          echo "Test failed!"
+          exit 1
+        fi
