Adding initial changes to allow separating all components of docker-selenium

diff --git a/docker-selenium.yaml b/docker-selenium.yaml
--- a/docker-selenium.yaml
+++ b/docker-selenium.yaml
@@ -102,6 +102,14 @@ pipeline:
   - uses: strip
 
 subpackages:
+  - name: ${{package.name}}-config
+    pipeline:
+      - runs: |
+          mkdir -p ${{targets.contextdir}}/opt/selenium/
+          install -m644 "./example-config.toml" ${{targets.contextdir}}/opt/selenium/config.toml
+
+
+
   - name: ${{package.name}}-standalone
     dependencies:
       runtime:
@@ -111,11 +119,60 @@ subpackages:
       - working-directory: Standalone
         pipeline:
           - runs: |
-              mkdir -p ${{targets.subpkgdir}}/etc/supervisor/conf.d
-              mkdir -p ${{targets.subpkgdir}}/opt/bin
-              cp start-selenium-standalone.sh ${{targets.subpkgdir}}/opt/bin/start-selenium-standalone.sh
-              cp selenium.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
-              cp generate_config ${{targets.subpkgdir}}/opt/bin/generate_config
+              mkdir -p ${{targets.contextdir}}/etc/supervisor/conf.d
+              mkdir -p ${{targets.contextdir}}/opt/bin
+              cp start-selenium-standalone.sh ${{targets.contextdir}}/opt/bin/start-selenium-standalone.sh
+              cp selenium.conf ${{targets.contextdir}}/etc/supervisor/conf.d/
+              cp generate_config ${{targets.contextdir}}/opt/bin/generate_config
+    test:
+      environment:
+        contents:
+          packages:
+      pipeline:
+        - runs: |
+            /opt/bin/start-selenium-standalone.sh --help
+            /opt/bin/start-selenium-standalone.sh --version
+
+  # selenium-hub does not handle rendering or direct interaction with browsers
+  # we can skip adding chromium, Xvfb, fluxbox, and related font packages.
+  - name: ${{package.name}}-hub
+    description: Docker Selenium Hub
+    dependencies:
+      runtime:
+        - ${{package.name}}
+        - selenium-server
+    pipeline:
+      - runs: |
+          mkdir -p ${{targets.contextdir}}/opt/bin
+          mkdir -p ${{targets.contextdir}}/opt/selenium
+      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Hub/Dockerfile
+      - working-directory: Hub
+        pipeline:
+          - runs: |
+              mkdir -p ${{targets.contextdir}}/etc/supervisor/conf.d
+              cp selenium-grid-hub.conf ${{targets.contextdir}}/etc/supervisor/conf.d/
+              install -Dm755 start-selenium-grid-hub.sh ${{targets.contextdir}}/opt/bin/
+              cp example-config.toml ${{targets.contextdir}}/opt/selenium/config.toml
+    test:
+      environment:
+        contents:
+          packages:
+            - ${{package.name}}
+            - selenium-server
+        environment:
+          SE_RELAX_CHECKS: True
+          SE_BIND_HOST: False
+          SE_SESSION_RETRY_INTERVAL: 50
+          SE_HEALTHCHECK_INTERVAL: 500
+          SE_SESSION_REQUEST_TIMEOUT: 500
+      pipeline:
+      - name: "Check all in one status"
+        uses: test/daemon-check-output
+        with:
+          start: "/opt/bin/start-selenium-grid-hub.sh"
+          timeout: 60
+          expected_output: |
+            Started Selenium Hub
 
   - name: ${{package.name}}-nodebase
     description: Node base
@@ -140,7 +197,6 @@ subpackages:
         - libxcb
         - mcookie
         - novnc
-        - openjdk1
         - pulseaudio
         - pulseaudio-utils
         - ttf-dejavu
@@ -151,28 +207,55 @@ subpackages:
         - xkeyboard-config
         - xmessage
         - xvfb-run
+        - openjdk-11
+        - ${{package.name}}
+        - ${{package.name}}-config
+        - selenium-server
     pipeline:
-      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile
       - working-directory: NodeBase
         pipeline:
+          # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile
           - runs: |
-              mkdir -p ${{targets.subpkgdir}}/opt/bin
-              mkdir -p ${{targets.subpkgdir}}/etc/supervisor/conf.d
-              mkdir -p ${{targets.subpkgdir}}/usr/share/images/fluxbox
-              cp start-selenium-node.sh ${{targets.subpkgdir}}/opt/bin/
-              cp start-xvfb.sh ${{targets.subpkgdir}}/opt/bin/
-              cp selenium.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
-              cp start-vnc.sh ${{targets.subpkgdir}}/opt/bin/
-              cp start-novnc.sh ${{targets.subpkgdir}}/opt/bin/
-              cp selenium_grid_logo.png ${{targets.subpkgdir}}/usr/share/images/fluxbox/ubuntu-light.png
-              cp generate_relay_config ${{targets.subpkgdir}}/opt/bin/generate_relay_config
+              mkdir -p ${{targets.contextdir}}/opt/bin
+              mkdir -p ${{targets.contextdir}}/etc/supervisor/conf.d
+              mkdir -p ${{targets.contextdir}}/usr/share/images/fluxbox
+          - runs: |
+              cp start-selenium-node.sh ${{targets.contextdir}}/opt/bin/
+              cp start-xvfb.sh ${{targets.contextdir}}/opt/bin/
+              cp selenium.conf ${{targets.contextdir}}/etc/supervisor/conf.d/
+              cp start-vnc.sh ${{targets.contextdir}}/opt/bin/
+              cp start-novnc.sh ${{targets.contextdir}}/opt/bin/
+              cp selenium_grid_logo.png ${{targets.contextdir}}/usr/share/images/fluxbox/ubuntu-light.png
+              cp generate_relay_config ${{targets.contextdir}}/opt/bin/generate_relay_config
 
-              mkdir -p ${{targets.subpkgdir}}/home/$SEL_USER/.fluxbox
-              mkdir -p ${{targets.subpkgdir}}/tmp/.X11-unix
-              mkdir -p ${{targets.subpkgdir}}/home/$SEL_USER/.vnc
-              mkdir -p ${{targets.subpkgdir}}/opt/selenium
-              mkdir -p ${{targets.subpkgdir}}/opt/selenium
-              echo "${SEL_PASSWD}" | x11vnc -storepasswd - ${{targets.subpkgdir}}/home/$SEL_USER/.vnc/passwd
+              mkdir -p ${{targets.contextdir}}/home/$SEL_USER/.fluxbox
+              mkdir -p ${{targets.contextdir}}/tmp/.X11-unix
+              mkdir -p ${{targets.contextdir}}/home/$SEL_USER/.vnc
+              mkdir -p ${{targets.contextdir}}/opt/selenium
+              mkdir -p ${{targets.contextdir}}/opt/selenium
+              echo "${SEL_PASSWD}" | x11vnc -storepasswd - ${{targets.contextdir}}/home/$SEL_USER/.vnc/passwd
+    test:
+      environment:
+        contents:
+          packages:
+            - ${{package.name}}
+            - selenium-server
+            - ${{package.name}}-config
+            - geckodriver
+        environment:
+          SE_EVENT_BUS_PUBLISH_PORT: 4442
+          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
+          SE_EVENT_BUS_HOST: selenium-hub
+          CONFIG_FILE: /opt/selenium/config.toml  
+          SE_BIND_HOST: True    
+      pipeline:
+        - name: "Check all in one status"
+          uses: test/daemon-check-output
+          with:
+            start: "/opt/bin/start-selenium-node.sh"
+            timeout: 60
+            expected_output: |
+              Started Selenium node
 
   # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeChrome/Dockerfile
   - name: ${{package.name}}-nodechrome
@@ -180,12 +263,48 @@ subpackages:
     dependencies:
       runtime:
         - ${{package.name}}-nodebase
+        - chromium-docker-selenium-compat
     pipeline:
       - working-directory: NodeChrome
         pipeline:
           - runs: |
-              mkdir -p ${{targets.subpkgdir}}/opt/bin/
-              cp wrap_chrome_binary ${{targets.subpkgdir}}/opt/bin/wrap_chrome_binary
+              mkdir -p ${{targets.contextdir}}/opt/bin/
+              cp wrap_chrome_binary ${{targets.contextdir}}/opt/bin/wrap_chrome_binary
+    test:
+      environment:
+        contents:
+          packages:
+      pipeline:
+        - runs: |
+            /opt/bin/wrap_chrome_binary &
+            sleep 5
+            ps aux | grep chrome
+
+  - name: ${{package.name}}-nodefirefox
+    dependencies:
+      runtime:
+        - ${{package.name}}-nodebase
+        - geckodriver
+        - firefox
+    pipeline:
+      - working-directory: NodeFirefox
+        pipeline:
+          - runs: |
+              mkdir -p ${{targets.contextdir}}/opt/bin
+              mkdir -p ${{targets.contextdir}}/opt/selenium/
+              mkdir -p ${{targets.contextdir}}/etc/supervisor/conf.d/
+              cp firefox-cleanup.sh ${{targets.contextdir}}/opt/bin/firefox-cleanup.sh
+              cp firefox-cleanup.conf ${{targets.contextdir}}/etc/supervisor/conf.d/firefox-cleanup.conf
+              echo "firefox" > ${{targets.contextdir}}/opt/selenium/browser_name
+              firefox --version | awk '{print $3}' > ${{targets.contextdir}}/opt/selenium/browser_version
+              echo "\"moz:firefoxOptions\": {\"binary\": \"/usr/bin/firefox\"}" > ${{targets.contextdir}}/opt/selenium/browser_binary_location
+    test:
+      environment:
+        contents:
+          packages:
+      pipeline:
+        - runs: |
+            firefox --version
 
   - name: ${{package.name}}-supervisor-config
     description: Docker Selenium supervisor configuration
@@ -196,44 +315,25 @@ subpackages:
         - supervisor-config
     pipeline:
       - runs: |
-          mkdir -p ${{targets.subpkgdir}}/etc
-          mv ${{targets.destdir}}/etc/supervisord.conf ${{targets.subpkgdir}}/etc
-          mv ${{targets.destdir}}/etc/supervisor ${{targets.subpkgdir}}/etc
+          mkdir -p ${{targets.contextdir}}/etc
+          mv ${{targets.destdir}}/etc/supervisord.conf ${{targets.contextdir}}/etc
+          mv ${{targets.destdir}}/etc/supervisor ${{targets.contextdir}}/etc
 
           # Unset setuid bit
           # jason@ copied this directly from https://serverfault.com/a/238964
           # The extra 0 is to unset the setuid bit apparently.
-          chmod 00775 ${{targets.subpkgdir}}/etc/supervisord.conf
-
-  # selenium-hub does not handle rendering or direct interaction with browsers
-  # we can skip adding chromium, Xvfb, fluxbox, and related font packages.
-  - name: ${{package.name}}-hub
-    description: Docker Selenium Hub
-    pipeline:
-      - runs: |
-          mkdir -p ${{targets.subpkgdir}}/opt/bin
-          mkdir -p ${{targets.subpkgdir}}/opt/selenium
-      # https://github.com/SeleniumHQ/docker-selenium/blob/trunk/Hub/Dockerfile
-      - working-directory: Hub
-        pipeline:
-          - runs: |
-              mkdir -p ${{targets.subpkgdir}}/etc/supervisor/conf.d
-              cp selenium-grid-hub.conf ${{targets.subpkgdir}}/etc/supervisor/conf.d/
-              install -Dm755 start-selenium-grid-hub.sh ${{targets.subpkgdir}}/opt/bin/
-              cp example-config.toml ${{targets.subpkgdir}}/opt/selenium/config.toml
+          chmod 00775 ${{targets.contextdir}}/etc/supervisord.conf
 
   - name: ${{package.name}}-standalone-chrome
     description: Docker Selenium standalone
     dependencies:
       runtime:
-        - ${{package.name}}-nodebase
         - ${{package.name}}-nodechrome
-        - chromium
-        - chromium-docker-selenium-compat
+        - ${{package.name}}-standalone
     pipeline:
       - runs: |
-          mkdir -p ${{targets.subpkgdir}}/etc
-          mkdir -p ${{targets.subpkgdir}}/opt/bin
+          mkdir -p ${{targets.contextdir}}/etc
+          mkdir -p ${{targets.contextdir}}/opt/bin
 
 update:
   enabled: true
@@ -244,3 +344,13 @@ update:
       replace: $1.$2
   github:
     identifier: SeleniumHQ/docker-selenium
+
+test:
+  environment:
+    contents:
+      packages:
+        - ${{package.name}}-standalone
+  pipeline:
+    - runs: |
+        # Make sure Chrome and ChromeDriver are at the correct path
+        /opt/bin/start-selenium-standalone.sh --help || (echo "start-selenium-standalone.sh --help failed" && exit 1)
