Fix binary and Add test
The previous build was broken as the required jar files are either missing or misplaced. Also Move to the real scalla 3 repository to build dotty as previous one is just the alies of this one

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

diff --git a/dotty.yaml b/dotty.yaml
--- a/dotty.yaml
+++ b/dotty.yaml
@@ -25,7 +25,7 @@ environment:
 pipeline:
   - uses: git-checkout
     with:
-      repository: https://github.com/lampepfl/dotty
+      repository: https://github.com/scala/scala3
       tag: ${{package.version}}
       expected-commit: ad3f69867b4600a3550bf9e76a1fc58091cb5eaf
 
@@ -37,25 +37,90 @@ pipeline:
     runs: |
       # Create the directories with the correct permissions
       mkdir -p ${{targets.destdir}}/usr/bin
-      install -dm755 "${{targets.destdir}}"/usr/share/scala/bin
-      install -dm755 "${{targets.destdir}}"/usr/share/scala/lib
-      install -dm755 "${{targets.destdir}}"/usr/share/scala/libexec
+      install -dm755 "${{targets.destdir}}"/usr/share/scala/
 
       # Extract the zip file
-      unzip dist/target/universal/scala3-${{package.version}}-bin-SNAPSHOT.zip -d target/universal
+      unzip dist/target/universal/scala3-${{package.version}}-bin-SNAPSHOT.zip -d build
 
       # Cleaning and removing windows batch files
-      rm -rf dist/target/universal/scala3-${{package.version}}-bin-SNAPSHOT/bin/*.bat
-      rm -rf dist/target/universal/scala3-${{package.version}}-bin-SNAPSHOT/libexec/*.bat
+      rm -rf build/scala3-${{package.version}}-bin-SNAPSHOT/bin/*.bat
+      rm -rf build/scala3-${{package.version}}-bin-SNAPSHOT/libexec/*.bat
 
-      mv target/universal/scala3-${{package.version}}-bin-SNAPSHOT/bin/* ${{targets.destdir}}/usr/share/scala/bin/
-      mv target/universal/scala3-${{package.version}}-bin-SNAPSHOT/lib/* ${{targets.destdir}}/usr/share/scala/lib/
-      mv target/universal/scala3-${{package.version}}-bin-SNAPSHOT/libexec/* ${{targets.destdir}}/usr/share/scala/libexec/
+      mv build/scala3-${{package.version}}-bin-SNAPSHOT/* ${{targets.destdir}}/usr/share/scala/
+
       ln -sf /usr/share/scala/bin/scala ${{targets.destdir}}/usr/bin/scala
       ln -sf /usr/share/scala/bin/scalac ${{targets.destdir}}/usr/bin/scalac
       ln -sf /usr/share/scala/bin/scaladoc ${{targets.destdir}}/usr/bin/scaladoc
 
+      # dotty try to find the scala-cli.jar in the bin directory, so we need to move that in scala bin directory
+      mv ${{targets.destdir}}/usr/share/scala/libexec/scala-cli.jar ${{targets.destdir}}/usr/share/scala/bin/
+
+test:
+  environment:
+    contents:
+      packages:
+        - openjdk-11-default-jvm
+        - openjdk-11-jre
+  pipeline:
+    - name: Verify that the binaries are installed and executable
+      runs: |
+        for bin in scala scalac scaladoc; do
+          if [ ! -x "/usr/bin/$bin" ]; then
+            echo "$bin is not installed or not executable"
+            exit 1
+          fi
+          # Run the --version command for each binary
+          $bin --version
+        done
+    - name: "Test Scala compiler"
+      runs: |
+        # Create a simple HelloWorld.scala file
+        echo 'object HelloWorld extends App { println("Hello, World!") }' > HelloWorld.scala
+
+        # Compile the HelloWorld.scala file
+        scalac HelloWorld.scala
+
+        # Run the compiled HelloWorld program
+        scala run -cp . -M HelloWorld
+
+        # Clean up
+        rm -f HelloWorld.scala HelloWorld*.class HelloWorld.tasty
+    - name: "Test Scala compiler with multiple files"
+      runs: |
+        cat > Person.scala << 'EOF'
+        case class Person(name: String) {
+          override def toString = s"Person($name)"
+        }
+        EOF
+        cat > Main.scala << 'EOF'
+        object Main extends App {
+          val person = Person("Test")
+          println(person)
+        }
+        EOF
+        scalac Person.scala Main.scala
+        scala run -cp . -M Main | grep "Person(Test)"
+
+        # clean up
+        rm -f Person.scala Main.scala Person*.class Main*.class Person.tasty Main.tasty
+    - name: "Test Scaladoc generation"
+      runs: |
+        cat > DocTest.scala << 'EOF'
+        /** Documentation test class */
+        class DocTest {
+          /** Test method */
+          def test(): Unit = ()
+        }
+        EOF
+        scalac DocTest.scala
+        mkdir -p doc
+        scaladoc -d doc DocTest.tasty
+        test -d doc && test -f doc/index.html
+
+        # clean up
+        rm -f DocTest.scala DocTest*.class DocTest.tasty
+
 update:
   enabled: true
   github:
-    identifier: lampepfl/dotty
+    identifier: scala/scala3
