Fix bad symlinks in druid.
The package build left absolute symlinks that targetted the
full path to the destdir. This cleanup really needs to be
done more centrally, but this will do for now.

diff --git a/druid.yaml b/druid.yaml
--- a/druid.yaml
+++ b/druid.yaml
@@ -44,8 +44,34 @@ pipeline:
 
   - runs: |
       # deduplicate jars
-      cp distribution/docker/deduplicate_jars.sh ${{targets.destdir}}/deduplicate_jars.sh
-      ${{targets.destdir}}/deduplicate_jars.sh ${{targets.destdir}}/usr/share/java/druid
+      distribution/docker/deduplicate_jars.sh ${{targets.destdir}}/usr/share/java/druid
+
+      # deduplicate_jars makes symlinks, which would be fine, but they're absolute.
+      # it is meant to be run from /, so adjust things for it.
+      ddir=${{targets.destdir}}
+      cd "$ddir"
+      tmpf=$(mktemp)
+      trap "rm -f $tmpf" EXIT
+      find usr/share/java/druid -name "*.jar" -type l > "$tmpf"
+      while read src ; do
+         dest=$(readlink "$src") || {
+           echo "failed to readlink on '$src'"
+           exit 1
+         }
+         case "$dest" in
+             $ddir/*) ndest="/${dest#$ddir/}";;
+             *) continue;;
+         esac
+         [ -f "./${ndest}" -o -L "./${ndest}" ] || {
+           echo "$src was dangling symlink to $dest"
+           exit 1
+         }
+         echo "adjusting $src from $dest to $ndest"
+         ln -sf "${ndest}" "$src" || {
+           echo "failed [$?] ln -sf $ndest $src"
+           exit 1
+         }
+      done <"$tmpf"
 
 subpackages:
   - name: "${{package.name}}-compat"
