Adding test for exim
Signed-off-by: mauricio-dc-chainguard <mauricio.diazcernas@chainguard.dev>

diff --git a/exim.yaml b/exim.yaml
--- a/exim.yaml
+++ b/exim.yaml
@@ -74,6 +74,58 @@ pipeline:
 
 subpackages:
 
+test:
+  environment:
+    contents:
+      packages:
+        - postgresql
+        - postgresql-client
+        - wolfi-base
+        - shadow
+        - sudo-rs
+        - glibc-locales
+    environment:
+      PGDATA: /tmp/test_db
+      PGUSER: wolfi
+  pipeline:
+    - name: "Test database creation"
+      runs: |
+        echo "Current user: $(whoami)"
+        useradd $PGUSER
+        sudo -u $PGUSER initdb -D /tmp/test_db
+        sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
+        sudo -u $PGUSER createdb testdb
+        psql -lqt | cut -d \| -f 1 | grep -qw testdb
+    - name: "Test basic read/write operations"
+      runs: |
+        sudo -u $PGUSER psql -d testdb -c "CREATE TABLE test_table (id SERIAL PRIMARY KEY, test_value VARCHAR(50));"
+        sudo -u $PGUSER psql -d testdb -c "INSERT INTO test_table (test_value) VALUES ('Hello, PostgreSQL!');"
+        sudo -u $PGUSER psql -d testdb -t -A -c "SELECT test_value FROM test_table WHERE id=1;"
+    - name: "Test server can run and respond to requests"
+      runs: |
+        sudo -u $PGUSER psql -d testdb -c "\conninfo"
+    - name: "Test exim extension is installed and working"
+      runs: |
+        # Exim is install test
+        if ! command -v exim &> /dev/null; then
+          echo "Exim is not installed."
+          exit 1
+        else
+          echo "Exim is installed."
+        fi
+
+        # Send test email
+        echo "This is a test email sent through Exim." | sudo -u $PGUSER exim -odf recipient@example.com
+
+        # Test exim - db conection
+        exim_db_test=$(sudo -u $PGUSER exim -be '${lookup pgsql{SELECT 1 FROM dual}}')
+        if [ "$exim_db_test" == "1" ]; then
+          echo "Exim successfully connected to PostgreSQL."
+        else
+          echo "Exim failed to connect to PostgreSQL."
+          exit 1
+        fi
+
 update:
   enabled: true
   release-monitor:
