Refactor exim test
Signed-off-by: mauricio-dc-chainguard <mauricio.diazcernas@chainguard.dev>

diff --git a/exim.yaml b/exim.yaml
--- a/exim.yaml
+++ b/exim.yaml
@@ -84,6 +84,7 @@ test:
         - shadow
         - sudo-rs
         - glibc-locales
+        - exim
     environment:
       PGDATA: /tmp/test_db
       PGUSER: wolfi
@@ -113,9 +114,19 @@ test:
           echo "Exim is installed."
         fi
 
+        # Test exim - db conection
+
         exim_bp_output=$(exim -bP)
         echo "Exim -bP output:"
         echo "$exim_bp_output"
+
+        exim_db_test=$(sudo -u $PGUSER exim -be '${lookup pgsql{SELECT 1 FROM dual}}')
+        if [ "$exim_db_test" == "1" ]; then
+          echo "Exim successfully connected to PostgreSQL."
+        else
+          echo "Exim failed to connect to PostgreSQL."
+          exit 1
+        fi
 
 update:
   enabled: true
