refactor test case
Signed-off-by: Sam Singh Anantha <samsinghanantha@gmail.com>

diff --git a/fluent-bit-plugin-loki.yaml b/fluent-bit-plugin-loki.yaml
--- a/fluent-bit-plugin-loki.yaml
+++ b/fluent-bit-plugin-loki.yaml
@@ -49,26 +49,15 @@ test:
         export LOKI_URL="http://localhost:3100/loki/api/v1/push"
 
         fluent-bit -e /fluent-bit/bin/out_grafana_loki.so -c /fluent-bit/etc/fluent-bit-loki.conf > fluent_bit_output.log 2>&1 &
-
-        # Wait for the specific message or a timeout
-        TIMEOUT=10
-        INTERVAL=1
-        ELAPSED=0
-
-        while [[ $ELAPSED -lt $TIMEOUT ]]; do
+        for i in $(seq 1 10); do
             if grep -q "Starting fluent-bit-go-loki" fluent_bit_output.log; then
-                echo "Success: Detected 'Starting fluent-bit-go-loki' in Fluent Bit output."
-                break
+                echo "Success: 'Starting fluent-bit-go-loki' detected in logs"
+                exit 0
             fi
-            sleep $INTERVAL
-            ELAPSED=$((ELAPSED + INTERVAL))
+          sleep 1
         done
-
-        # Check if we exited the loop because of a timeout
-        if [[ $ELAPSED -ge $TIMEOUT ]]; then
-            echo "Timeout: Did not detect 'Starting fluent-bit-go-loki' within $TIMEOUT seconds."
-        fi
-
+        echo "Timeout: 'Starting fluent-bit-go-loki' not found in logs"
+        exit 1
 
 update:
   enabled: true
