Feat: python multiversion build for gi-docgen
recently while working on gtk-4 package we encounter that there is a python version mismatch for gi-docgen and we are getting an older version of py3-gi-docgen due to matching version for some other package in the build env

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

diff --git a/gi-docgen.yaml b/gi-docgen.yaml
--- a/gi-docgen.yaml
+++ b/gi-docgen.yaml
@@ -1,10 +1,22 @@
 package:
   name: gi-docgen
   version: "2024.1"
-  epoch: 1
+  epoch: 2
   description: A documentation generator for GObject-based libraries
   copyright:
     - license: Apache-2.0 OR GPL-3.0-or-later
+  dependencies:
+    provider-priority: 0
+
+vars:
+  pypi-package: gi-docgen
+
+data:
+  - name: py-versions
+    items:
+      3.11: '311'
+      3.12: '312'
+      3.13: '313'
 
 environment:
   contents:
@@ -15,13 +27,14 @@ environment:
       - busybox
       - ca-certificates-bundle
       - meson
-      - py3-jinja2
-      - py3-markdown
-      - py3-markupsafe
-      - py3-packaging
-      - py3-pygments
-      - py3-typogrify
-      - python3
+      - py3-supported-jinja2
+      - py3-supported-markdown
+      - py3-supported-markupsafe
+      - py3-supported-packaging
+      - py3-supported-pip
+      - py3-supported-pygments
+      - py3-supported-python
+      - py3-supported-typogrify
 
 pipeline:
   - uses: fetch
@@ -29,34 +42,68 @@ pipeline:
       expected-sha256: c2f49f0bdea0366d04b6ab6f34071f324ef70016bc3650371cc08d3c6f2764da
       uri: https://gitlab.gnome.org/GNOME/gi-docgen/-/archive/${{package.version}}/gi-docgen-${{package.version}}.tar.gz
 
-  - runs: |
-      meson . output
-      meson compile ${JOBS:+-j ${JOBS}} -C output
-      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output
-
-  - uses: strip
-
 subpackages:
-  - name: py3-gi-docgen
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: python${{range.key}} version of ${{vars.pypi-package}}
     dependencies:
+      provider-priority: ${{range.value}}
+      provides:
+        - py3-${{vars.pypi-package}}
+        - gi-docgen
       runtime:
-        - py3-markdown
-        - py3-markupsafe
-        - py3-pygments
-        - py3-jinja2
-        - py3-packaging
-        - py3-typogrify
-        - py3-tomli
-        - python3
+        - py${{range.key}}-jinja2
+        - py${{range.key}}-markdown
+        - py${{range.key}}-markupsafe
+        - py${{range.key}}-packaging
+        - py${{range.key}}-pygments
+        - py${{range.key}}-typogrify
+        - python-${{range.key}}
     pipeline:
-      - name: Python Build
-        uses: python/build-wheel
+      - runs: |
+          py=python${{range.key}}
+          pyfullpath=$(which "$py") || {
+            echo "ERROR: '$py' not found in PATH."
+            exit 1
+          }
+
+          echo "Using Python interpreter: $pyfullpath"
+
+          # Create a temporary directory and symlink for python3
+          tmp_dir=$(mktemp -d)
+          trap "rm -rf $tmp_dir" EXIT
+          ln -s "$pyfullpath" "$tmp_dir/python3"
+          export PATH="$tmp_dir:$PATH"
+
+          # Cleanup previous build and compile
+          rm -rf output
+
+          meson . output
+          meson compile ${JOBS:+-j ${JOBS}} -C output
+          DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output
+      - uses: py/pip-build-install
+        with:
+          python: python${{range.key}}
       - uses: strip
     test:
       pipeline:
         - runs: |
             gi-docgen --version
             gi-docgen --help
+
+  - name: py3-supported-${{vars.pypi-package}}
+    description: meta package providing ${{vars.pypi-package}} for supported python versions.
+    dependencies:
+      runtime:
+        - py3.11-${{vars.pypi-package}}
+        - py3.12-${{vars.pypi-package}}
+        - py3.13-${{vars.pypi-package}}
+
+test:
+  pipeline:
+    - runs: |
+        gi-docgen --version
+        gi-docgen --help
 
 update:
   enabled: true
