git - add git-subtree to installation.

diff --git a/git.yaml b/git.yaml
--- a/git.yaml
+++ b/git.yaml
@@ -1,7 +1,7 @@
 package:
   name: git
   version: "2.51.0"
-  epoch: 0
+  epoch: 1
   description: "distributed version control system"
   copyright:
     - license: GPL-2.0-or-later
@@ -59,6 +59,14 @@ pipeline:
         DESTDIR="${{targets.destdir}}" \
         INSTALLDIRS=vendor \
         install -j$(nproc)
+
+  - name: install subtree
+    runs: |
+      make -C contrib/subtree \
+        prefix=/usr \
+        DESTDIR="${{targets.destdir}}" \
+        INSTALLDIRS=vendor \
+        git-subtree install
 
   - runs: |
       mkdir -p "${{targets.destdir}}"/var/git
@@ -194,6 +202,9 @@ test:
   environment:
     environment:
       HOME: /tmp
+    contents:
+      packages:
+        - man-db
   pipeline:
     - uses: test/hardening-check
     - runs: |
@@ -224,3 +235,14 @@ test:
       runs: |
         git config --list | grep 'user.name=Wolfi' || exit 1
         git config --list | grep 'user.email=wolf@wolfi.dev' || exit 1
+    - name: Verify git subtree
+      runs: |
+        # subtree with no args exits non-zero but shows usage
+        # cannot test --help as we're not buildin docs
+        git subtree > out || :
+        if ! grep -q "usage: git subtree" out; then
+           echo "FAIL: git subtree seems no to have written usage. output:"
+           sed 's,^,> ,' out
+           exit 1
+        fi
+        rm out
