add test case
Signed-off-by: Sam Singh Anantha <samsinghanantha@gmail.com>

diff --git a/gitlab-cng.yaml b/gitlab-cng.yaml
--- a/gitlab-cng.yaml
+++ b/gitlab-cng.yaml
@@ -83,11 +83,22 @@ subpackages:
       runtime:
         - ca-certificates
         - gitlab-cng-base
-    # test:
-    #   pipeline:
-    #     - name: Test entrypoint script
-    #       runs: |
-            
+    test:
+      pipeline:
+        - name: Test bundle-certificates script
+          runs: |
+            # if bundle-certificates runs correctly, it dereferences symlinks outside of /etc/ssl/certs
+            for f in /etc/ssl/certs/*.pem /etc/ssl/certs/*.crt; do
+              if [ -L "$f" ]; then
+                origin=$(readlink -f "$f")
+                originPath=${origin%/*}
+                if [ "$originPath" != "/etc/ssl/certs" ]; then
+                  echo "Error: $f is a symlink pointing outside of /etc/ssl/certs to $origin"
+                  exit 1
+                fi
+              fi
+            done
+                        
 
 update:
   enabled: true
