Adding Tests for workhorse
Signed-off-by: Aditvil-Dev <aditya.tirmanwar@chainguard.dev>

diff --git a/gitlab-17.1.yaml b/gitlab-17.1.yaml
--- a/gitlab-17.1.yaml
+++ b/gitlab-17.1.yaml
@@ -28,7 +28,7 @@ subpackages:
         with:
           modroot: ./workhorse
           packages: ./cmd/gitlab-workhorse
-          output: workhorse
+          output: gitlab-workhorse
       - uses: strip
 
   - name: ${{package.name}}-resize-image
@@ -37,7 +37,7 @@ subpackages:
         with:
           modroot: ./workhorse
           packages: ./cmd/gitlab-resize-image
-          output: resize-image
+          output: gitlab-resize-image
       - uses: strip
 
   - name: ${{package.name}}-zip-cat
@@ -46,7 +46,7 @@ subpackages:
         with:
           modroot: ./workhorse
           packages: ./cmd/gitlab-zip-cat
-          output: zip-cat
+          output: gitlab-zip-cat
       - uses: strip
 
   - name: ${{package.name}}-zip-metadata
@@ -55,7 +55,7 @@ subpackages:
         with:
           modroot: ./workhorse
           packages: ./cmd/gitlab-zip-metadata
-          output: zip-metadata
+          output: gitlab-zip-metadata
       - uses: strip
 
 update:
@@ -65,6 +65,55 @@ update:
     identifier: 373181
 
 test:
+  environment:
+    contents:
+      packages:
+        - curl
+        - redis
+        - ${{package.name}}-workhorse
   pipeline:
     - runs: |
-        workhorse --version
+        #!/bin/bash
+
+        set -e
+
+        WORKHORSE_CONFIG=/tmp/workhorse-config.toml
+
+        tee $WORKHORSE_CONFIG <<EOL
+        [redis]
+        URL = "redis://localhost:6379"
+
+        [metadata]
+          zip_reader_limit_bytes = 104857600
+
+        [image_resizer]
+          max_scaler_procs = 4
+          max_filesize = 250000
+
+        [[listeners]]
+          network = "tcp"
+          addr = "127.0.0.1:8181"
+        EOL
+
+        # Start Redis
+        redis-server --daemonize yes
+
+        # Start gitlab-workhorse with the configuration file
+        gitlab-workhorse -config $WORKHORSE_CONFIG &
+        PID=$!
+
+        sleep 5
+        # Check if the workhorse server is running
+        if ! kill -0 $WORKHORSE_PID > /dev/null 2>&1; then
+            echo "Workhorse server failed to start"
+            exit 1
+        fi
+
+        # Test the health endpoint
+        HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$WORKHORSE_PORT/-/health)
+        if [ "$HTTP_RESPONSE" -ne 200 ]; then
+          echo "Failed to get a valid response from the health endpoint"
+          echo "HTTP response code: $HTTP_RESPONSE"
+          kill $PID
+          exit 1
+        fi
