feat: Add verification for base-images-tag to ensure consistency with upstream - Added a pipeline step to verify that BASE_IMAGES_TAG matches the expected upstream value. - The build does not fail automatically if the extracted tag is incorrect, so a manual check is necessary. - This ensures consistency with the upstream configuration and prevents accidental mismatches. - If the expected and extracted tags do not match, the build will fail with an explicit error message.
Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>

diff --git a/gitlab-runner-17.8.yaml b/gitlab-runner-17.8.yaml
--- a/gitlab-runner-17.8.yaml
+++ b/gitlab-runner-17.8.yaml
@@ -46,6 +46,19 @@ pipeline:
       tag: v${{package.version}}
       expected-commit: 690ce25c4e607e5f993cf439439ad6acc77952ba
 
+  - name: Verify base-images-tag matches the expected upstream value
+    runs: |
+      # The build does not fail automatically if the extracted tag does not match the expected tag.
+      # Therefore, we manually verify that BASE_IMAGES_TAG matches the expected upstream value.
+      # This ensures consistency with the upstream configuration
+
+      BASE_IMAGES_TAG=$(cat ./.gitlab/ci/_common.gitlab-ci.yml | sed -n 's/.*RUNNER_IMAGES_VERSION: "\([0-9.]*\)".*/\1/p')
+
+      if [ "${{vars.base-images-tag}}" != "${BASE_IMAGES_TAG}" ]; then
+        echo "Expected BASE_IMAGES_TAG: ${{vars.base-images-tag}} but got: $BASE_IMAGES_TAG"
+        exit 1
+      fi
+
   - uses: go/build
     with:
       packages: .
