add gitlab-certificates (#22949)
Signed-off-by: Sam Singh Anantha <samsinghanantha@gmail.com>

diff --git a/gitlab-cng.yaml b/gitlab-cng.yaml
--- a/gitlab-cng.yaml
+++ b/gitlab-cng.yaml
@@ -5,7 +5,7 @@
 package:
   name: gitlab-cng
   version: 17.1.1
-  epoch: 0
+  epoch: 1
   description: Cloud Native container images per component of GitLab
   copyright:
     - license: MIT
@@ -69,6 +69,35 @@ subpackages:
         - gomplate
         - procps
         - xtail
+
+  - name: "${{package.name}}-certificates"
+    pipeline:
+      - runs: |
+          cd ./certificates
+          for x in $(find scripts/ -type f); do
+            mkdir -p ${{targets.subpkgdir}}/$(dirname $x)
+            cp -r $x ${{targets.subpkgdir}}/$x
+          done
+          ./scripts/bundle-certificates
+    dependencies:
+      runtime:
+        - ca-certificates
+        - gitlab-cng-base
+    test:
+      pipeline:
+        - name: Test bundle-certificates script
+          runs: |
+            # if bundle-certificates runs correctly, it dereferences symlinks outside of /etc/ssl/certs
+            for f in /etc/ssl/certs/*.pem /etc/ssl/certs/*.crt; do
+              if [ -L "$f" ]; then
+                origin=$(readlink -f "$f")
+                originPath=${origin%/*}
+                if [ "$originPath" != "/etc/ssl/certs" ]; then
+                  echo "Error: $f is a symlink pointing outside of /etc/ssl/certs to $origin"
+                  exit 1
+                fi
+              fi
+            done
 
 update:
   enabled: true
