Merge pull request #57359 from egibs/fix-trivy-cves
trivy, trivy-fips, trivy-operator, trivy-operator-fips: remediate GHSA-4vrq-3vrq-g6gg, GHSA-4c29-8rgm-jvjj, GHSA-jhf3-xxhw-2wpp, and GHSA-gm2x-2g9h-ccm8

Export:  8f8ef9fa60adfd87e3df8b8a4ae226e451aa1d47

diff --git a/glibc.yaml b/glibc.yaml
--- a/glibc.yaml
+++ b/glibc.yaml
@@ -3,7 +3,7 @@ package:
   name: glibc
   version: "2.43"
   # Every glibc update causes build disruption; always announce on #eng-psa
-  epoch: 4
+  epoch: 6
   description: "the GNU C library"
   copyright:
     - license: LGPL-2.1-or-later
@@ -58,6 +58,9 @@ vars:
   # someone from the OS team!                                     #
   ########################### STOP!!! #############################
   glibc-expected-commit: ce1013a197eb4a3b8ff2b07e0672f4d0b976ce7c
+  # We remove unnecessary charsets that could otherwise increase the
+  # attack surface of the package.
+  charsets-to-remove: "IBM1390 IBM1399"
 
 pipeline:
   - uses: git-checkout
@@ -312,20 +315,39 @@ subpackages:
     description: "GLIBC iconv tables"
     pipeline:
       - runs: |
+          # Cleanup unnecessary character sets
+          for ch in ${{vars.charsets-to-remove}}; do
+            rm -v "${{targets.destdir}}/usr/lib/gconv/${ch}.so"
+          done
+
           mkdir -p "${{targets.subpkgdir}}"/usr/lib
           mv "${{targets.destdir}}"/usr/lib/gconv "${{targets.subpkgdir}}"/usr/lib/
 
           mkdir -p "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/iconvconfig "${{targets.subpkgdir}}"/usr/bin
+          mv "${{targets.destdir}}"/usr/bin/iconv "${{targets.subpkgdir}}"/usr/bin
     test:
       pipeline:
         - uses: test/tw/help-check
           with:
-            bins: iconvconfig
+            bins: |
+              iconvconfig
+              iconv
         - uses: test/tw/ver-check
           with:
-            bins: iconvconfig
+            bins: |
+              iconvconfig
+              iconv
             version: ${{package.version}}
+        - name: Check if unnecessary charsets are not being shipped
+          runs: |
+            set -euo pipefail
+            for ch in ${{vars.charsets-to-remove}}; do
+              if iconv -f "${ch}" -t UTF-8 /dev/null ; then
+                echo "Charset $ch is available while it shouldn't be."
+                exit 1
+              fi
+            done
     dependencies:
       runtime:
         - merged-lib
@@ -424,7 +446,6 @@ subpackages:
           mv "${{targets.destdir}}"/usr/bin/gencat "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/getconf "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/getent "${{targets.subpkgdir}}"/usr/bin
-          mv "${{targets.destdir}}"/usr/bin/iconv "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/locale "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/pldd "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/libexec "${{targets.subpkgdir}}"/usr
@@ -436,7 +457,6 @@ subpackages:
               gencat
               getconf
               getent
-              iconv
               locale
               pldd
         - uses: test/tw/ver-check
@@ -445,7 +465,6 @@ subpackages:
               gencat
               getconf
               getent
-              iconv
               locale
               pldd
 
