create go-slim subpackage
Signed-off-by: Michael Paul <31833332+MickeyPvX@users.noreply.github.com>

diff --git a/go-1.24.yaml b/go-1.24.yaml
--- a/go-1.24.yaml
+++ b/go-1.24.yaml
@@ -1,7 +1,7 @@
 package:
   name: go-1.24
   version: "1.24.4"
-  epoch: 0
+  epoch: 1
   description: "the Go programming language"
   copyright:
     - license: BSD-3-Clause
@@ -112,6 +112,82 @@ subpackages:
       - runs: |
           find "${{targets.destdir}}/usr/lib/go/pkg/tool" -type f -name "${{range.key}}" \
             -exec install -Dm755 \{\} "${{targets.contextdir}}/usr/bin/${{range.key}}" \;
+
+  - name: "go-slim"
+    description: Go without CGO or runtime deps
+    pipeline:
+      - runs: |
+          mkdir -p "${{targets.subpkgdir}}"/usr/lib/go
+          mkdir -p "${{targets.subpkgdir}}"/usr/bin
+
+          cp -r "${{targets.destdir}}"/usr/lib/go/* "${{targets.subpkgdir}}"/usr/lib/go/
+
+          for bin in go gofmt; do
+            ln -s /usr/lib/go/bin/$bin "${{targets.subpkgdir}}"/usr/bin/
+          done
+    test:
+      pipeline:
+        - name: Test Go installation
+          runs: |
+            # Write a simple "Hello World" Go program
+            cat <<EOF > hello.go
+            package main
+            import "fmt"
+            func main() {
+                fmt.Println("Hello World")
+            }
+            EOF
+
+            # Format the Go program
+            go fmt hello.go
+
+            # Run the Go program and check the output
+            go run hello.go | grep "Hello World"
+            go version
+            go help
+            gofmt --help
+        - name: Test Go cross-compilation
+          runs: |
+            # Build the Go program for a different OS/architecture
+            GOOS=freebsd GOARCH=amd64 go build hello.go
+        - name: Test telemetry settings
+          runs: |
+            fail() { echo "FAIL:" "$@" 1>&2; exit 1; }
+
+            tmpd=$(mktemp -d)
+            trap "rm -R '$tmpd'" EXIT
+            export HOME="$tmpd/home"
+            mkdir "$HOME"
+
+            out=$(go telemetry) || fail "'go telemetry' exited $?"
+            [ "$out" = "off" ] ||
+              fail "go telemetry output '$out'. expected 'off'"
+
+            cfgdir="$HOME/.config/go/telemetry"
+            if [ -d "$cfgdir" ]; then
+              fail "$cfgdir was created by running 'go telemetry'"
+            fi
+
+            go telemetry on ||
+              fail "'go telemetry on' exited $?"
+            out=$(go telemetry) || fail "'go telemetry' after 'on' exited $?"
+            [ "$out" = "on" ] ||
+              fail "go telemetry after 'on' output '$out'. expected 'on'"
+
+            [ -f "$cfgdir/mode" ] ||
+              fail "ERROR: 'go telemetry on' did not write ~/${cfgdir#$HOME/}"
+
+            go telemetry local ||
+              fail "'go telemetry local' exited $?"
+            out=$(go telemetry) || fail "'go telemetry' after 'local' exited $?"
+            [ "$out" = "local" ] ||
+              fail "go telemetry after 'local' output '$out'. expected 'on'"
+
+            go telemetry off ||
+              fail "explicit 'go telemetry off' exited $?"
+            out=$(go telemetry) || fail "'go telemetry' after explicit off exited $?"
+            [ "$out" = "off" ] ||
+              fail "go telemetry after explicit off output '$out'. expected 'off'"
 
 update:
   enabled: true
