Add a md5sum test to go-fips-1.22.
The expectation is was that a md5sum test should fail to run
because openssl fips woudl reject acccess to that entry point.

As implemented here, the md5 program does not get any openssl use
and "successfully" runs to completion.

diff --git a/go-fips-1.22.yaml b/go-fips-1.22.yaml
--- a/go-fips-1.22.yaml
+++ b/go-fips-1.22.yaml
@@ -14,6 +14,11 @@ package:
       - binutils-gold # Needed for cgo linking due to upstream issue #15696 which forces use of the gold linker.
       - build-base
 
+vars:
+  # https://github.com/chainguard-images/images-private/pull/2752/files
+  # uses a different symbol ('_Cfunc__goboringcrypto_')
+  uses-boring-crypto-symbol: "v2._Cfunc_go_openssl"
+
 environment:
   contents:
     packages:
@@ -189,8 +194,8 @@ test:
         CGO_ENABLED=1 go build .
 
         go tool nm ./sha256 > nm.out
-        if ! grep -q v2._Cfunc_go_openssl nm.out; then
-            echo "built sha256 was missing v2._Cfunc_go_openssl symbol"
+        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
+            echo "built sha256 was missing ${{vars.uses-boring-crypto-symbol}} symbol"
             cat nm.out
             exit 1
         fi
@@ -198,5 +203,45 @@ test:
         # you can't actually run this here because you'd need the fips provider.
         #expected=e6f9203564e78f0a61c829906c1a8fe1303767d06f2b96d6185f10950baa44ae
         #found=$(./sha256 "Go Cubs Go")
-        #
         #[ "$found" = "$expected" ]
+
+    - name: "md5 test"
+      runs: |
+        export HOME=$PWD
+        export GOPATH=$PWD
+
+        rm -Rf md5
+        mkdir md5
+        cd md5
+        cat >md5.go <<"EOF"
+        package main
+
+        import (
+            "crypto/md5"
+            "fmt"
+            "os"
+        )
+
+        func main() {
+            fmt.Printf("%x\n", md5.Sum([]byte(os.Args[1])))
+        }
+        EOF
+
+        go mod init example.com/go/md5
+        go mod tidy
+
+        CGO_ENABLED=1 go build .
+
+        expected=a893dd5ec835031e6b4aef10b5427b74
+        found=$(./md5 "Go Cubs Go")
+        [ "$expected" = "$found" ] || {
+          echo "found unexpected result ($found). expected md5=$expected"
+          exit 1
+        }
+
+        go tool nm ./md5 > nm.out
+        if ! grep -q "${{vars.uses-boring-crypto-symbol}}" nm.out; then
+            echo "built md5 was missing ${{vars.uses-boring-crypto-symbol}} symbol"
+            cat nm.out
+            exit 1
+        fi
