Add a test to golang-1.22-fips to use sha256.
My understanding is that this should create a binary that
depends on openssl.

diff --git a/go-fips-1.22.yaml b/go-fips-1.22.yaml
--- a/go-fips-1.22.yaml
+++ b/go-fips-1.22.yaml
@@ -169,3 +169,41 @@ test:
         }
         EOF
         go run /tmp/main.go
+    - name: "sha256 test"
+      runs: |
+        export HOME=$PWD
+        export GOPATH=$PWD
+
+        mkdir sha256
+        cd sha256
+        cat >sha256.go <<"EOF"
+        package main
+
+        import (
+            "crypto/sha256"
+            "fmt"
+            "os"
+        )
+
+        func main() {
+            fmt.Printf("%x\n", sha256.Sum256([]byte(os.Args[1])))
+        }
+        EOF
+
+        go mod init example.com/go/sha256
+        go mod tidy
+
+        CGO_ENABLED=1 go build .
+
+        go tool nm ./sha256 > nm.out
+        if ! grep -q v2._Cfunc_go_openssl nm.out; then
+            echo "built sha256 was missing v2._Cfunc_go_openssl symbol"
+            cat nm.out
+            exit 1
+        fi
+
+        # you can't actually run this here because you'd need the fips provider.
+        #expected=e6f9203564e78f0a61c829906c1a8fe1303767d06f2b96d6185f10950baa44ae
+        #found=$(./sha256 "Go Cubs Go")
+        #
+        #[ "$found" = "$expected" ]
