add functional test
Signed-off-by: Aditvil-Dev <aditya.tirmanwar@chainguard.dev>

diff --git a/gst-libav.yaml b/gst-libav.yaml
--- a/gst-libav.yaml
+++ b/gst-libav.yaml
@@ -1,6 +1,6 @@
 package:
   name: gst-libav
-  version: "1.25.1"
+  version: "1.26.0"
   epoch: 0
   description: GStreamer plugin for using the encoders, decoders, muxers, and demuxers provided by FFmpeg.
   copyright:
@@ -22,7 +22,7 @@ pipeline:
     with:
       repository: https://github.com/GStreamer/gstreamer
       tag: ${{package.version}}
-      expected-commit: ca9d85c3b7a12cda2c19e4404410b81a1c8c2e0b
+      expected-commit: d31ce8e5e1aacf8f5e5beabb5c81ce2e4da5c202
 
   - runs: |
       cd subprojects/gst-libav
@@ -61,7 +61,44 @@ update:
     tag-filter-prefix: "1."
 
 test:
+  environment:
+    contents:
+      packages:
+        - git
   pipeline:
     - uses: test/ldd-check
       with:
         packages: ${{package.name}}
+    - name: Clone GStreamer repo and run tests
+      runs: |
+        git clone --depth 1 https://github.com/GStreamer/gstreamer.git
+        TEST_DIR=/home/build/gstreamer/subprojects/gst-libav/tests/files
+        cd $TEST_DIR
+
+        # 1. Basic plugin check
+        gst-inspect-1.0 libav
+        if [ $? -ne 0 ]; then
+          echo "ERROR: libav plugin is missing!"
+          exit 1
+        fi
+
+        # 2. Fetch APE filename
+        APE_FILE=$(ls *.ape)
+        if [ -z "$APE_FILE" ]; then
+          echo "ERROR: No APE file found in test directory!"
+          exit 1
+        fi
+
+        # 3. APE demuxing test
+        gst-launch-1.0 filesrc location="$APE_FILE" ! avdemux_ape ! fakesink
+        if [ $? -ne 0 ]; then
+          echo "ERROR: APE demuxing failed!"
+          exit 1
+        fi
+
+        # 6. FFmpeg version check
+        gst-inspect-1.0 libav | grep -i ffmpeg
+        if [ $? -ne 0 ]; then
+          echo "ERROR: FFmpeg version check failed!"
+          exit 1
+        fi
