Adjustments to align with other versions

diff --git a/ingress-nginx-controller-1.13.yaml b/ingress-nginx-controller-1.13.yaml
--- a/ingress-nginx-controller-1.13.yaml
+++ b/ingress-nginx-controller-1.13.yaml
@@ -2,7 +2,7 @@
 package:
   name: ingress-nginx-controller-1.13
   version: "1.13.0"
-  # There are manual changes to review between each package update. See 'vars:' section
+  # There are manual changes to review between each package update. See 'vars:' section.
   epoch: 0
   description: "Ingress-NGINX Controller for Kubernetes"
   copyright:
@@ -50,16 +50,6 @@ package:
       - ssdeep
       - wolfi-baselayout
       - yaml-cpp
-
-var-transforms:
-  - from: ${{package.version}}
-    match: ^(\d+\.\d+)\.\d+$
-    replace: "$1"
-    to: nginx-ingress-major-minor
-  - from: ${{package.version}}
-    match: ^(\d+)\.\d+\.\d+$
-    replace: "$1"
-    to: nginx-ingress-major
 
 environment:
   contents:
@@ -147,23 +137,36 @@ environment:
       - zeromq-dev
       - zlib-dev
 
+var-transforms:
+  - from: ${{package.version}}
+    match: ^(\d+\.\d+)\.\d+$
+    replace: "$1"
+    to: nginx-ingress-major-minor
+  - from: ${{package.version}}
+    match: ^(\d+)\.\d+\.\d+$
+    replace: "$1"
+    to: nginx-ingress-major
+
 vars:
   # These environment variables need updated for each new release. Retrieve their
   # correct values from here, replacing <package-version> with the package version.
   #   - https://github.com/kubernetes/ingress-nginx/blob/controller-v<package-version>/images/nginx/rootfs/build.sh
   # On occasion, these versions may be bumped ahead of upstream (above link), to
   # remediate vulnerabilities.
+  # NOTE: When updating this, the hardcoded string downstream in images-private
+  # also needs to be updated: https://github.com/chainguard-images/images-private/blob/ea364a2ecc436c035765d3b45564f8597cf9b09a/images/ingress-nginx-controller/main.tf#L14
   NGINX_VERSION: "1.25.5"
   NDK_VERSION: "0.3.3"
   SETMISC_VERSION: "0.33"
   MORE_HEADERS_VERSION: "0.37"
   NGINX_DIGEST_AUTH: "1.0.0"
   NGINX_SUBSTITUTIONS: "e12e965ac1837ca709709f9a26f572a54d83430e"
-  OWASP_MODSECURITY_CRS_VERSION: "v4.10.0"
+  OWASP_MODSECURITY_CRS_VERSION: "4.15.0"
   LUA_NGX_VERSION: "0.10.28"
   LUA_STREAM_NGX_VERSION: "0.0.16"
   LUA_UPSTREAM_VERSION: "542be0893543a4e42d89f6dd85372972f5ff2a36"
   GEOIP2_VERSION: "a607a41a8115fecfc05b5c283c81532a3d605425"
+  PKG: "k8s.io/ingress-nginx"
   # Does not do versioning, and repo is seldom updated. Grab the latest master
   # branch git commit SHA: https://github.com/google/ngx_brotli/commits/master
   NGX_BROTLI_SHA: 63ca02abdcf79c9e788d2eedcc388d2335902e52
@@ -172,7 +175,7 @@ vars:
   MODSECURITY_NGINX_VERSION: "a32bd8a28c5e5cdebb00a2c5467b974c62d47850"
   # Instrumentation for nginx plugin: https://github.com/open-telemetry/opentelemetry-cpp-contrib
   # NOTE: THIS IS REALLY REALLY REALLY CRITICAL AND THE CONFIG CAN BREAK IN BACKWARDS COMPATIBLE WAY!!
-  # WE SHOULD ALWAYS USE THE SHA AVAILABLE IN RELEASE-X.Y BRANCH OF UPSTREAM PROJECT (e.g. https://github.com/kubernetes/ingress-nginx/blob/controller-v1.12.1/images/nginx/rootfs/build.sh#L528)
+  # WE SHOULD ALWAYS USE THE SHA AVAILABLE IN RELEASE-X.Y BRANCH OF UPSTREAM PROJECT (e.g. https://github.com/kubernetes/ingress-nginx/blob/controller-v1.13.x/images/nginx/rootfs/build.sh#L528)
   OTEL_SHA: "8933841f0a7f8737f61404cf0a64acf6b079c8a5"
 
 pipeline:
@@ -182,6 +185,81 @@ pipeline:
       tag: controller-v${{package.version}}
       expected-commit: 9dc73d17c76e2289408ebff2f3446b8b13c3e72e
 
+  - name: Verify all the vars are up to date with the upstream
+    runs: |
+      # Extract and verify all versions from upstream build.sh file
+      # https://github.com/kubernetes/ingress-nginx/blob/controller-v${{package.version}}/images/nginx/rootfs/build.sh
+
+      echo ${{vars.nginx-ingress-major-minor}}
+      echo ${{vars.nginx-ingress-major}}
+
+      for var_pair in \
+        "NGINX_VERSION:${{vars.NGINX_VERSION}}" \
+        "NDK_VERSION:${{vars.NDK_VERSION}}" \
+        "SETMISC_VERSION:${{vars.SETMISC_VERSION}}" \
+        "MORE_HEADERS_VERSION:${{vars.MORE_HEADERS_VERSION}}" \
+        "NGINX_DIGEST_AUTH:${{vars.NGINX_DIGEST_AUTH}}" \
+        "NGINX_SUBSTITUTIONS:${{vars.NGINX_SUBSTITUTIONS}}" \
+        "OWASP_MODSECURITY_CRS_VERSION:${{vars.OWASP_MODSECURITY_CRS_VERSION}}" \
+        "LUA_NGX_VERSION:${{vars.LUA_NGX_VERSION}}" \
+        "LUA_STREAM_NGX_VERSION:${{vars.LUA_STREAM_NGX_VERSION}}" \
+        "LUA_UPSTREAM_VERSION:${{vars.LUA_UPSTREAM_VERSION}}" \
+        "GEOIP2_VERSION:${{vars.GEOIP2_VERSION}}" \
+        "NGX_BROTLI_SHA:${{vars.NGX_BROTLI_SHA}}" \
+        "MODSECURITY_NGINX_VERSION:${{vars.MODSECURITY_NGINX_VERSION}}" \
+        "OTEL_SHA:${{vars.OTEL_SHA}}"; do
+
+        var_name="${var_pair%:*}"
+        expected_value="${var_pair#*:}"
+
+        # Handle special cases with custom verification logic
+        case "$var_name" in
+          "NGX_BROTLI_SHA")
+            # Get latest master commit from ngx_brotli repo
+            upstream_value=$(curl -s https://api.github.com/repos/google/ngx_brotli/commits/master | grep '"sha"' | head -1 | cut -d'"' -f4)
+            ;;
+          "MODSECURITY_NGINX_VERSION")
+            # Get MODSECURITY_VERSION tag from upstream build.sh, then resolve to commit SHA
+            upstream_tag=$(grep "^export MODSECURITY_VERSION=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Use the tags API which includes commit info directly
+            upstream_value=$(curl -s "https://api.github.com/repos/owasp-modsecurity/ModSecurity-nginx/tags" | grep -A5 "\"name\": \"$upstream_tag\"" | grep '"sha"' | cut -d'"' -f4)
+            ;;
+          "OTEL_SHA")
+            # Extract OTEL_SHA from upstream build.sh using OPENTELEMETRY_CONTRIB_COMMIT variable
+            upstream_value=$(grep "^export OPENTELEMETRY_CONTRIB_COMMIT=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            ;;
+          "LUA_STREAM_NGX_VERSION")
+            # Get commit SHA from upstream build.sh, then resolve to tag
+            upstream_commit=$(grep "^export ${var_name}=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Find which tag contains this commit as an ancestor
+            upstream_value=""
+            for tag in $(curl -s "https://api.github.com/repos/openresty/stream-lua-nginx-module/tags" | grep '"name"' | head -10 | cut -d'"' -f4); do
+              # Check if this commit is reachable from the tag (commit is ancestor of tag)
+              compare_result=$(curl -s "https://api.github.com/repos/openresty/stream-lua-nginx-module/compare/$upstream_commit...$tag" 2>/dev/null)
+              if echo "$compare_result" | grep -q '"status": "ahead"' || echo "$compare_result" | grep -q '"status": "identical"'; then
+                # The tag contains this commit (either identical or tag is ahead)
+                upstream_value=$(echo "$tag" | sed 's/^v//')
+                break
+              fi
+            done
+            ;;
+          *)
+            # Standard extraction from build.sh
+            upstream_value=$(grep "^export ${var_name}=" ./images/nginx/rootfs/build.sh | cut -d= -f2)
+            # Strip leading 'v' from upstream value if it's a version triple (x.y.z) or double (x.y)
+            if echo "$upstream_value" | grep -q "^v[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?$"; then
+              upstream_value="${upstream_value#v}"
+            fi
+            ;;
+        esac
+
+        if [ "$expected_value" != "$upstream_value" ]; then
+          echo "WARNING: Expected $var_name: $expected_value from melange.yaml but found $upstream_value upstream" >&2
+          # We avoid failing the build because sometimes we bump versions higher than upstream
+          sleep 5 # To make it more noticeable
+        fi
+      done
+
   - uses: git-checkout
     with:
       repository: https://github.com/owasp-modsecurity/ModSecurity-nginx
@@ -190,41 +268,26 @@ pipeline:
       destination: ModSecurity-nginx-${{vars.MODSECURITY_NGINX_VERSION}}
       depth: -1
 
-  - name: Build ingress-nginx controller from source
-    runs: |
-      # need to retag the repo because we've made changes and the module builds based on the git tags
-      git tag v${{package.version}}
+  # need to retag the repo because we've made changes and the module builds based on the git tags
+  - runs: git tag v${{package.version}}
 
-      export PKG="k8s.io/ingress-nginx"
-      export COMMIT_SHA=$(git rev-parse --short HEAD)
-      export REPO_INFO=$(git config --get remote.origin.url)
+  - uses: go/build
+    with:
+      packages: ${{vars.PKG}}/cmd/dbg
+      output: nginx-dbg
+      ldflags: -X ${{vars.PKG}}/version.RELEASE=controller-v${{package.version}} -X ${{vars.PKG}}/version.COMMIT=$(git rev-parse --short HEAD) -X ${{vars.PKG}}/version.REPO=$(git config --get remote.origin.url)
 
-      mkdir -p ${{targets.destdir}}
+  - uses: go/build
+    with:
+      packages: ${{vars.PKG}}/cmd/waitshutdown
+      output: waitshutdown
+      ldflags: -X ${{vars.PKG}}/version.RELEASE=controller-v${{package.version}} -X ${{vars.PKG}}/version.COMMIT=$(git rev-parse --short HEAD) -X ${{vars.PKG}}/version.REPO=$(git config --get remote.origin.url)
 
-      export CGO_ENABLED=0
-
-      go build -x -v \
-      -trimpath -ldflags="-buildid= -w \
-      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
-      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
-      -X ${PKG}/version.REPO=${REPO_INFO}" \
-      -o "${{targets.destdir}}/usr/bin/nginx-dbg" ${PKG}/cmd/dbg
-
-      go build -x -v \
-      -trimpath -ldflags="-buildid= -w \
-      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
-      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
-      -X ${PKG}/version.REPO=${REPO_INFO}" \
-      -o "${{targets.destdir}}/usr/bin/waitshutdown" ${PKG}/cmd/waitshutdown
-
-      go build -x -v \
-      -trimpath -ldflags="-buildid= -w \
-      -X ${PKG}/version.RELEASE=controller-v${{package.version}} \
-      -X ${PKG}/version.COMMIT=${COMMIT_SHA} \
-      -X ${PKG}/version.REPO=${REPO_INFO}" \
-      -o "${{targets.destdir}}/usr/bin/nginx-ingress-controller" ${PKG}/cmd/nginx
-
-      getcap ${{targets.destdir}}/usr/bin/nginx-ingress-controller
+  - uses: go/build
+    with:
+      packages: ${{vars.PKG}}/cmd/nginx
+      output: nginx-ingress-controller
+      ldflags: -X ${{vars.PKG}}/version.RELEASE=controller-v${{package.version}} -X ${{vars.PKG}}/version.COMMIT=$(git rev-parse --short HEAD) -X ${{vars.PKG}}/version.REPO=$(git config --get remote.origin.url)
 
   - uses: fetch
     with:
@@ -322,7 +385,7 @@ pipeline:
       # Download owasp modsecurity crs
       cd ${{targets.destdir}}/etc/nginx/
 
-      git clone -b ${{vars.OWASP_MODSECURITY_CRS_VERSION}} https://github.com/coreruleset/coreruleset owasp-modsecurity-crs
+      git clone -b v${{vars.OWASP_MODSECURITY_CRS_VERSION}} https://github.com/coreruleset/coreruleset owasp-modsecurity-crs
       cd owasp-modsecurity-crs
 
       mv crs-setup.conf.example crs-setup.conf
@@ -370,7 +433,7 @@ pipeline:
 
       cd "$BUILD_PATH/nginx-${{vars.NGINX_VERSION}}"
 
-      for p in $(ls $BUILD_PATH/images/nginx-1.25/rootfs/patches/*.patch); do
+      for p in $(ls $BUILD_PATH/images/nginx/rootfs/patches/*.patch); do
         echo "Patching $p..."
         patch -p1 $p
       done
@@ -701,23 +764,27 @@ subpackages:
           output: kube-webhook-certgen
           modroot: ./images/kube-webhook-certgen/rootfs
           packages: .
+    test:
+      pipeline:
+        - runs: |
+            /usr/bin/kube-webhook-certgen version
 
   - name: ingress-nginx-opentelemetry-plugin-${{vars.nginx-ingress-major-minor}}
     description: OTel plugin for ingress nginx controller ${{vars.nginx-ingress-major-minor}}
     dependencies:
+      provides:
+        - ingress-nginx-opentelemetry-plugin=${{package.full-version}}
       runtime:
         - grpc
         - libprotobuf
         - merged-usrsbin
         - wolfi-baselayout
-      provides:
-        - ingress-nginx-opentelemetry-plugin=${{package.full-version}}
     pipeline:
       - name: Validate Open Telemetry version
         runs: |
           expected_sha=$(grep -E "^export OPENTELEMETRY_CONTRIB_COMMIT" images/nginx/rootfs/build.sh | awk -F '=' '{print $2}')
           [[ "${{vars.OTEL_SHA}}" == "${expected_sha}" ]] || \
-            { echo "OTel version does not match."; exit 1; }
+            { echo "OTel version does not match. Expected ${expected_sha}, found ${{vars.OTEL_SHA}}"; exit 1; }
       - uses: git-checkout
         with:
           repository: https://github.com/open-telemetry/opentelemetry-cpp-contrib
