iso-codes: introduce tests
Introduce tests, previously missing.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/iso-codes.yaml b/iso-codes.yaml
--- a/iso-codes.yaml
+++ b/iso-codes.yaml
@@ -51,3 +51,30 @@ update:
   enabled: true
   release-monitor:
     identifier: 1406
+
+test:
+  pipeline:
+    - name: "verify we have some .mo files"
+      runs: |
+        dir="/usr/share/locale/"
+        if ! find "${dir}" -name '*.mo' | grep -q . ; then
+          echo "FAIL: no .mo files found at '${dir}', this is unexpected" >&2
+          exit 1
+        fi
+        echo "PASS: we have some .mo files at '${dir}'"
+    - name: "verify we have some .json files"
+      runs: |
+        dir="/usr/share/iso-codes/"
+        if ! find "${dir}" -name '*.json' | grep -q . ; then
+          echo "FAIL: no .json files found at '${dir}', this is unexpected" >&2
+          exit 1
+        fi
+        echo "PASS: we have some .json files at '${dir}'"
+    - name: "verify we have some .xml files"
+      runs: |
+        dir="/usr/share/xml/iso-codes/"
+        if ! find "${dir}" -name '*.xml' | grep -q . ; then
+          echo "FAIL: no .xml files found at '${dir}', this is unexpected" >&2
+          exit 1
+        fi
+        echo "PASS: we have some .xml files at '${dir}'"
