add runtime deps from image to package, switch to git checkout and add tests
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/jenkins.yaml b/jenkins.yaml
--- a/jenkins.yaml
+++ b/jenkins.yaml
@@ -1,13 +1,21 @@
 package:
   name: jenkins
   version: "2.448"
-  epoch: 0
-  description:
+  epoch: 1
+  description: Open-source CI/CD application.
   copyright:
     - license: MIT
   dependencies:
     runtime:
+      # Jenkins requires both bash and busybox.
+      - bash
+      - busybox
+      - coreutils
+      - glibc-locale-en
+      - openjdk-17-jre
+      - openjdk-17-default-jvm
       - ttf-dejavu
+      - tzdata
 
 environment:
   contents:
@@ -31,10 +39,11 @@ environment:
       - tzdata
 
 pipeline:
-  - uses: fetch
+  - uses: git-checkout
     with:
-      uri: https://github.com/jenkinsci/jenkins/archive/refs/tags/jenkins-${{package.version}}.tar.gz
-      expected-sha256: c79961ef5a86d9279e41a846e3b3e062e0383c0be256d59882bd510f4fb11fcc
+      repository: https://github.com/jenkinsci/jenkins
+      tag: jenkins-${{package.version}}
+      expected-commit: e4ac97f4cfd9b3a0769ac09170b0e25530bed82d
 
   - uses: patch
     with:
@@ -57,3 +66,38 @@ update:
   github:
     identifier: jenkinsci/jenkins
     strip-prefix: jenkins-
+  ignore-regex-patterns:
+    - '*-rc'
+
+test:
+  pipeline:
+    - runs: |
+          cleanup() {
+            echo "Cleaning up..."
+            kill $JENKINS_PID
+          }
+          trap cleanup EXIT
+
+          /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war --version
+
+          echo "Launching Jenkins and performing log validation..."
+          /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war > jenkins.log 2>&1 &
+          JENKINS_PID=$!
+          TIMEOUT=60
+
+          while ! grep -q "Jenkins is fully up and running" jenkins.log && [ $TIMEOUT -gt 0 ]; do
+            sleep 1
+            TIMEOUT=$((TIMEOUT-1))
+          done
+
+          # Check for timeout without Jenkins being fully up
+          if [ $TIMEOUT -eq 0 ]; then
+            echo "Attempted to launch Jenkins in melange test, but log validation failed."
+            exit 1
+          fi
+
+          # Perform checks for FAIL in the logs
+          if grep -Eq "FAIL|FAILURE|ERROR" jenkins.log; then
+            echo "Successfully launched Jenkins in melange tests, but errors where found in the logs."
+            exit 1
+          fi
