Add melange tests
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/jenkins-plugin-manager.yaml b/jenkins-plugin-manager.yaml
--- a/jenkins-plugin-manager.yaml
+++ b/jenkins-plugin-manager.yaml
@@ -42,3 +42,22 @@ update:
   enabled: true
   github:
     identifier: jenkinsci/plugin-installation-manager-tool
+
+test:
+  environment:
+    contents:
+      packages:
+        - openjdk-17
+        - openjdk-17-default-jvm
+  pipeline:
+    - name: "Check jenkins-plugin-manager Installation"
+      runs: |
+        if [ -f "/usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar" ]; then
+          echo "jenkins-plugin-manager JAR found."
+        else
+          echo "jenkins-plugin-manager JAR not found!" && exit 1
+        fi
+    - name: "Test jenkins-plugin-manager Basic Functionality"
+      runs: |
+        java -jar /usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar --help || (echo "jenkins-plugin-manager test failed!" && exit 1)
+        java -jar /usr/share/java/jenkins-plugin-manager/jenkins-plugin-manager.jar --list || (echo "Plugin list test failed!" && exit 1)
