lint
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/jenkins.yaml b/jenkins.yaml
--- a/jenkins.yaml
+++ b/jenkins.yaml
@@ -12,8 +12,8 @@ package:
       - busybox
       - coreutils
       - glibc-locale-en
-      - openjdk-17-jre
       - openjdk-17-default-jvm
+      - openjdk-17-jre
       - ttf-dejavu
       - tzdata
 
@@ -72,32 +72,32 @@ update:
 test:
   pipeline:
     - runs: |
-          cleanup() {
-            echo "Cleaning up..."
-            kill $JENKINS_PID
-          }
-          trap cleanup EXIT
+        cleanup() {
+          echo "Cleaning up..."
+          kill $JENKINS_PID
+        }
+        trap cleanup EXIT
 
-          /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war --version
+        /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war --version
 
-          echo "Launching Jenkins and performing log validation..."
-          /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war > jenkins.log 2>&1 &
-          JENKINS_PID=$!
-          TIMEOUT=60
+        echo "Launching Jenkins and performing log validation..."
+        /usr/bin/java -Duser.home=/var/jenkins_home -jar /usr/share/java/jenkins/jenkins.war > jenkins.log 2>&1 &
+        JENKINS_PID=$!
+        TIMEOUT=60
 
-          while ! grep -q "Jenkins is fully up and running" jenkins.log && [ $TIMEOUT -gt 0 ]; do
-            sleep 1
-            TIMEOUT=$((TIMEOUT-1))
-          done
+        while ! grep -q "Jenkins is fully up and running" jenkins.log && [ $TIMEOUT -gt 0 ]; do
+          sleep 1
+          TIMEOUT=$((TIMEOUT-1))
+        done
 
-          # Check for timeout without Jenkins being fully up
-          if [ $TIMEOUT -eq 0 ]; then
-            echo "Attempted to launch Jenkins in melange test, but log validation failed."
-            exit 1
-          fi
+        # Check for timeout without Jenkins being fully up
+        if [ $TIMEOUT -eq 0 ]; then
+          echo "Attempted to launch Jenkins in melange test, but log validation failed."
+          exit 1
+        fi
 
-          # Perform checks for FAIL in the logs
-          if grep -Eq "FAIL|FAILURE|ERROR" jenkins.log; then
-            echo "Successfully launched Jenkins in melange tests, but errors where found in the logs."
-            exit 1
-          fi
+        # Perform checks for FAIL in the logs
+        if grep -Eq "FAIL|FAILURE|ERROR" jenkins.log; then
+          echo "Successfully launched Jenkins in melange tests, but errors where found in the logs."
+          exit 1
+        fi
