change all destdir and subpkgdir to contextdir, enforce in lint
Signed-off-by: Jason Hall <jason@chainguard.dev>

diff --git a/k3s.yaml b/k3s.yaml
--- a/k3s.yaml
+++ b/k3s.yaml
@@ -109,8 +109,8 @@ pipeline:
       # Move the "inner" k3s binary out of the bundle dir to avoid packaging it
       # twice. Give it a weird but semi-descriptive name to discourage users from
       # calling it directly
-      mkdir -p "${{targets.destdir}}"/bin/
-      mv bin/k3s "${{targets.destdir}}"/bin/_k3s-inner
+      mkdir -p "${{targets.contextdir}}"/bin/
+      mv bin/k3s "${{targets.contextdir}}"/bin/_k3s-inner
 
       # Modify the packaging script to exclusively use symlinks to our moved "inner" binary
       sed -i 's|ln -s k3s bin/$i|ln -s /bin/_k3s-inner bin/$i|g' ./scripts/package-cli
@@ -123,10 +123,10 @@ pipeline:
       # Finally, install the "outer" k3s multicall binary. This should only
       # contain the go runtime plus the self extracting multicall logic, and
       # should be a relatively small binary (~<15Mb).
-      install -Dm755 dist/artifacts/k3s* "${{targets.destdir}}"/bin/k3s
+      install -Dm755 dist/artifacts/k3s* "${{targets.contextdir}}"/bin/k3s
 
       # Assert a max multicall size since it's a good sign that packaging happened correctly.
-      [ $(stat -c%s "${{targets.destdir}}"/bin/k3s) -le $((15 * 1024 * 1024)) ] || { echo "Error: multicall k3s exceeds 15MB" >&2; exit 1; }
+      [ $(stat -c%s "${{targets.contextdir}}"/bin/k3s) -le $((15 * 1024 * 1024)) ] || { echo "Error: multicall k3s exceeds 15MB" >&2; exit 1; }
   - uses: strip
 
 subpackages:
@@ -174,7 +174,7 @@ subpackages:
           echo "Pulling images locally..."
           echo $images
 
-          _images_path="${{targets.subpkgdir}}"/var/lib/rancher/k3s/agent/images
+          _images_path="${{targets.contextdir}}"/var/lib/rancher/k3s/agent/images
           mkdir -p $_images_path
 
           crane pull $images $_images_path/k3s-airgap-images-$_arch.tar
