keycloak: attempt to run with nonroot
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/keycloak.yaml b/keycloak.yaml
--- a/keycloak.yaml
+++ b/keycloak.yaml
@@ -138,57 +138,68 @@ subpackages:
             - keycloak
             - keycloak-compat
             - keycloak-bitnami-compat
+        accounts:
+          groups:
+            - groupname: nonroot
+              gid: 65532
+          users:
+            - username: nonroot
+              gid: 65532
+              uid: 65532
+          run-as: 65532
         environment:
           PGDATA: /tmp/test_db
           PGUSER: bn_keycloak
           PGDB: bitnami_keycloak
           ALLOW_EMPTY_PASSWORD: yes
       pipeline:
-        - name: "Test database creation"
-          with:
-            setup: echo "127.0.0.1 postgresql" >> /etc/hosts
-          runs: |
-            useradd $PGUSER
-            sudo -u $PGUSER initdb -D $PGDATA
-            sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start
-            sudo -u $PGUSER createdb $PGDB
-            sudo -u $PGUSER psql -lqt | cut -d \| -f 1 | grep -qw $PGDB
-        - name: "start daemon on localhost"
-          uses: test/daemon-check-output
-          with:
-            setup: |
-              #!/bin/sh -e
-              echo "127.0.0.1 postgresql" >> /etc/hosts
-              echo "$(hostname) postgresql" >> /etc/hosts
-              useradd keycloak
-            start: |
-              #!/bin/sh -e
-              export BITNAMI_APP_NAME=keycloak
-              export APP_VERSION=${{package.version}}
-              export PATH=/opt/bitnami/keycloak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-              export KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
-              /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
-            timeout: 60
-            expected_output: |
-              Welcome to the Bitnami keycloak container
-              ** keycloak setup finished! **
-              server listening on
-              Keycloak ${{package.version}}
-              Running the server in development mode
-            post: |
-              #!/bin/sh -e
-              apk add curl
-              url=http://localhost:9000/health/ready
-              response=$(curl -fsS --retry-all-errors --retry 3 --retry-max-time 60 "$url") || {
-                echo "curl ${url} failed $?"
-                exit 1
-              }
-              echo "$response" | jq .status | grep -q UP || {
-                echo "response from $url did not contain \"UP\""
-                echo "response: $response"
-                exit 1
-              }
-              echo "$url had expected output: $response"
+        - working-directory: /home/nonroot
+          pipeline:
+            - name: "Test database creation"
+              with:
+                setup: echo "127.0.0.1 postgresql" >> /etc/hosts
+              runs: |
+                useradd $PGUSER
+                sudo -u $PGUSER initdb -D $PGDATA
+                sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start
+                sudo -u $PGUSER createdb $PGDB
+                sudo -u $PGUSER psql -lqt | cut -d \| -f 1 | grep -qw $PGDB
+            - name: "start daemon on localhost"
+              uses: test/daemon-check-output
+              with:
+                setup: |
+                  #!/bin/sh -e
+                  echo "127.0.0.1 postgresql" >> /etc/hosts
+                  echo "$(hostname) postgresql" >> /etc/hosts
+                  useradd keycloak
+                start: |
+                  #!/bin/sh -e
+                  export BITNAMI_APP_NAME=keycloak
+                  export APP_VERSION=${{package.version}}
+                  export PATH=/opt/bitnami/keycloak/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+                  export KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
+                  /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh
+                timeout: 60
+                expected_output: |
+                  Welcome to the Bitnami keycloak container
+                  ** keycloak setup finished! **
+                  server listening on
+                  Keycloak ${{package.version}}
+                  Running the server in development mode
+                post: |
+                  #!/bin/sh -e
+                  apk add curl
+                  url=http://localhost:9000/health/ready
+                  response=$(curl -fsS --retry-all-errors --retry 3 --retry-max-time 60 "$url") || {
+                    echo "curl ${url} failed $?"
+                    exit 1
+                  }
+                  echo "$response" | jq .status | grep -q UP || {
+                    echo "response from $url did not contain \"UP\""
+                    echo "response: $response"
+                    exit 1
+                  }
+                  echo "$url had expected output: $response"
 
 test:
   pipeline:
