chore(kubernetes-1.34): adapt changes from main
Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

diff --git a/kubernetes-1.34.yaml b/kubernetes-1.34.yaml
--- a/kubernetes-1.34.yaml
+++ b/kubernetes-1.34.yaml
@@ -100,30 +100,6 @@ subpackages:
         - runs: |
             stat /usr/share/bash-completion/completions/kubectl-${{vars.kubernetes-version}}
 
-  - name: kubectl-${{vars.kubernetes-version}}-bitnami-compat
-    description: "compat package with bitnami/kubectl image"
-    dependencies:
-      provides:
-        - kubectl-bitnami-compat=${{package.full-version}}
-      runtime:
-        - bash
-        - busybox
-        - coreutils
-    pipeline:
-      - runs: |
-          mkdir -p "${{targets.subpkgdir}}/opt/bitnami/kubectl/bin"
-          ln -s /usr/bin/kubectl "${{targets.subpkgdir}}/opt/bitnami/kubectl/bin/kubectl"
-          mkdir -p "${{targets.subpkgdir}}/opt/bitnami/common/bin"
-          ln -s /usr/bin/yq "${{targets.subpkgdir}}/opt/bitnami/common/bin/yq"
-    test:
-      pipeline:
-        - name: Check kubectl bitnami compat symlink
-          runs: |
-            readlink -f /opt/bitnami/kubectl/bin/kubectl | grep "/usr/bin/kubectl"
-        - name: Check yq bitnami compat symlink
-          runs: |
-            readlink -f /opt/bitnami/common/bin/yq | grep "/usr/bin/yq"
-
   - name: kubectl-${{vars.kubernetes-version}}-iamguarded-compat
     description: "compat package with iamguarded/kubectl image"
     dependencies:
@@ -176,8 +152,6 @@ subpackages:
   - name: kubelet-${{vars.kubernetes-version}}
     description: An agent that runs on each node in a Kubernetes cluster making sure that containers are running in a Pod
     dependencies:
-      provides:
-        - kubelet=${{package.full-version}}
       runtime:
         - ip6tables
     pipeline:
@@ -314,6 +288,25 @@ subpackages:
       - runs: |
           mkdir -p ${{targets.subpkgdir}}/usr/bin
           ln -s ${{range.key}}-${{vars.kubernetes-version}} ${{targets.subpkgdir}}/usr/bin/${{range.key}}
+    test:
+      pipeline:
+        - name: "Check symlink /usr/bin/${{range.key}} points to the expected binary /usr/bin/${{range.key}}-${{vars.kubernetes-version}}"
+          runs: |
+            readlink="$(readlink -f /usr/bin/${{range.key}})"
+            expected="/usr/bin/${{range.key}}-${{vars.kubernetes-version}}"
+            if ! echo "$readlink" | grep -q "$expected" ; then
+                echo "FAIL: unexpected link. Expected: [$expected] but got:" >&2
+                echo "$readlink" >&2
+                exit 1
+            fi
+        - uses: test/virtualpackage
+          with:
+            virtual-pkg-name: "${{range.key}}-default"
+            real-pkg-name: "${{subpkg.name}}"
+        - uses: test/virtualpackage
+          with:
+            virtual-pkg-name: "${{range.key}}"
+            real-pkg-name: "${{subpkg.name}}"
 
   - name: kube-proxy-${{vars.kubernetes-version}}-default-compat
     description: kube-proxy-default compatibility package
@@ -326,7 +319,7 @@ subpackages:
         - runs: stat /usr/local/bin/kube-proxy
 
   - name: kubernetes-${{vars.kubernetes-version}}-default
-    description: "Compatibility package to set ${{vars.kubernetes-version}} as the default kubernetes, and add packages to their shortened path"
+    description: "Compatibility meta package to set ${{vars.kubernetes-version}} as the default kubernetes, and add packages to their shortened path"
     dependencies:
       runtime:
         - kubectl-${{vars.kubernetes-version}}-default
@@ -340,6 +333,9 @@ subpackages:
     checks:
       disabled:
         - empty
+    test:
+      pipeline:
+        - uses: test/metapackage
 
 data:
   - name: components
