snyk-cli: build with nodejs-22
Signed-off-by: Colin Watson <colin.watson@chainguard.dev>


Export:  40692bad1f28b3ff1960d2c43e1fd2074d6d9802

diff --git a/libgsf.yaml b/libgsf.yaml
--- a/libgsf.yaml
+++ b/libgsf.yaml
@@ -1,6 +1,6 @@
 package:
   name: libgsf
-  version: "1.14.56"
+  version: "1.14.58"
   epoch: 0 # go/wolfi-rsc/libgsf
   description: Utility library for reading and writing structured file formats
   copyright:
@@ -42,7 +42,7 @@ pipeline:
   - uses: git-checkout
     with:
       repository: https://gitlab.gnome.org/GNOME/libgsf.git
-      expected-commit: fcf5c273c186069d579738acb12ca724b7a1445e
+      expected-commit: cc743384f0c51a5e5bbc94a22f81851bfece6af0
       tag: LIBGSF_${{vars.mangled-package-version}}
 
   - runs: |
@@ -116,13 +116,18 @@ test:
         - bzip2-dev
         - zlib-dev
   pipeline:
+    - uses: git-checkout
+      with:
+        repository: https://gitlab.gnome.org/GNOME/libgsf.git
+        expected-commit: cc743384f0c51a5e5bbc94a22f81851bfece6af0
+        tag: LIBGSF_${{vars.mangled-package-version}}
     - uses: test/tw/ver-check
       with:
-        bins: gsf gsf-vba-dump
+        bins: gsf
         version: ${{package.version}}
     - uses: test/tw/help-check
       with:
-        bins: gsf gsf-vba-dump
+        bins: gsf
     - uses: test/tw/ldd-check
     - name: Test libgsf compile and link
       runs: |
@@ -156,3 +161,16 @@ test:
 
         # List the contents of the OLE file
         gsf list /tmp/test.ole | grep -F "testfile.txt"
+    - name: Test gsf-vba-dump CLI functionality
+      runs: |
+        vba_dump_out="$(mktemp)"
+        result=0
+        gsf-vba-dump samples/vba-in-word.doc >"$vba_dump_out"
+        if grep -q 'Sub Macro1' "$vba_dump_out"; then
+          echo "PASS: gsf-vba-dump produced expected output"
+        else
+          echo "FAIL: gsf-vba-dump did not produce expected output" >&2
+          cat "$vba_dump_out" >&2
+          result=1
+        fi
+        exit $result
