Merge pull request #93694 from markusboehme/linux-pam/reset-vendor-dir
fix(linux-pam): install vendor configs at /etc, not /usr/share/pam

Export:  3d5185891472e82722d7762d0928cea74ca67794

diff --git a/linux-pam.yaml b/linux-pam.yaml
--- a/linux-pam.yaml
+++ b/linux-pam.yaml
@@ -1,7 +1,7 @@
 package:
   name: linux-pam
   version: "1.7.2"
-  epoch: 2
+  epoch: 3
   description: Linux PAM (Pluggable Authentication Modules for Linux)
   copyright:
     - license: BSD-3-Clause
@@ -42,7 +42,8 @@ pipeline:
             -Dmandir=/usr/share/man \
             -Dinfodir=/usr/share/info \
             -Dlocalstatedir=/var \
-            -Dsbindir=/usr/bin
+            -Dsbindir=/usr/bin \
+            -Dvendordir=
 
   - uses: meson/compile
 
@@ -179,5 +180,22 @@ test:
 
         # Verify tmpfiles configuration
         stat /usr/lib/tmpfiles.d/pam-faillock.conf
+
+        # Verify default configuration files are provided at the usual location.
+        conf_files=$(find /etc/security -type f -name '*.conf' -print)
+        if [ -z "$conf_files" ]; then
+          echo 'FAIL: default configuration files not found'
+          exit 1
+        fi
+
+        # Verify default configuration files don't contain deviant directives.
+        fails=0
+        for conf in $conf_files; do
+          if grep -q -v -e '^[[:space:]]*$' -e '^[[:space:]]*#' "$conf"; then
+            echo "FAIL: configuration file '$conf' contains non-default directive"
+            fails=$(( fails + 1 ))
+          fi
+        done
+        [ "$fails" -eq 0 ] || exit 1
     - uses: test/tw/ldd-check
     - uses: test/no-docs
