bump epochs to actually build jdbc
Signed-off-by: James Petersen <james.petersen@chainguard.dev>

diff --git a/logstash.yaml b/logstash.yaml
--- a/logstash.yaml
+++ b/logstash.yaml
@@ -17,7 +17,7 @@
 package:
   name: logstash
   version: 8.12.1
-  epoch: 2
+  epoch: 3
   description: Logstash - transport and process your logs, events, or other data
   copyright:
     - license: Apache-2.0
@@ -94,9 +94,19 @@ pipeline:
 
   - name: Re-inject default plugins that have been patched
     runs: |
-      bin/logstash-plugin install \
-        $(find / -type f -name "logstash-integration-jdbc-*.gem") \
-        $(find / -type f -name "logstash-filter-xml-*.gem")
+      for gem in \
+        "logstash-integration-jdbc" \
+        "logstash-filter-xml";
+      do
+        echo "Searching for gem search=$gem-*.gem"
+        gem_path=$(find /usr/share/jruby -type f -name "$gem-*.gem")
+        if [ -z "$gem_path" ]; then
+          echo "Could not find gem gem_path=$gem_path gem=$gem"
+          exit 1
+        fi
+        echo "Installing gem gem_path=$gem_path"
+        bin/logstash-plugin install "$gem_path"
+      done
 
   - name: Build tarball distribution
     runs: |
@@ -104,10 +114,16 @@ pipeline:
 
   - name: Package distribution
     runs: |
+      tarball=$(find . -type f -name "logstash-oss-${{package.version}}-SNAPSHOT-no-jdk.tar.gz")
+      if [ -z $tarball ]; then
+        echo "Could not find logstash-oss tarball, nothing to unpack"
+        exit 1
+      fi
+
       mkdir -p ${{targets.contextdir}}/${LS_DESTINATION}
       tar --strip-components 1 \
         -C ${{targets.contextdir}}/${LS_DESTINATION} \
-        -xf $(find . -type f -name "logstash-oss-${{package.version}}-SNAPSHOT-no-jdk.tar.gz")
+        -xf $tarball
 
       mkdir -p ${{targets.contextdir}}/usr/bin/$name
       for i in ${{targets.contextdir}}/${LS_DESTINATION}/bin/*; do
@@ -139,8 +155,9 @@ subpackages:
           install -m644 "${src}/pipeline/default.conf"         "${dst}/pipeline/default.conf"
           install -m755 "${src}/bin/docker-entrypoint"         "${{targets.contextdir}}/usr/bin/docker-entrypoint"
     dependencies:
-      runtime:
-        - ${{package.name}}-base
+      replaces:
+        - ${{package.name}}
+        - ${{package.name}}-with-output-opensearch
 
   - name: ${{package.name}}-env2yaml
     description: Merge environment variables into logstash.yml
@@ -168,8 +185,19 @@ subpackages:
     pipeline:
       - name: Re-inject default plugins that have been patched
         runs: |
-          bin/logstash-plugin install \
-            $(find / -type f -name "logstash-output-opensearch-*.gem")
+          for gem in \
+            "logstash-output-opensearch";
+          do
+            echo "Searching for gem search=$gem-*.gem"
+            gem_path=$(find /usr/share/jruby -type f -name "$gem-*.gem")
+            if [ -z "$gem_path" ]; then
+              echo "Could not find gem gem_path=$gem_path gem=$gem"
+              exit 1
+            fi
+            echo "Installing gem gem_path=$gem_path"
+            bin/logstash-plugin install "$gem_path"
+          done
+
       - name: Build tarball distribution
         runs: |
           ./gradlew assembleOssTarDistribution -Pjdk_bundle_os=linux
@@ -190,8 +218,11 @@ subpackages:
           # Hack-fix to reduce CVE count: https://github.com/elastic/logstash/pull/3855
           rm -rf ${{targets.contextdir}}/${LS_DESTINATION}/vendor/bundle/jruby/*/gems/ruby-maven-libs-*/maven-home/lib
     dependencies:
-      provides:
-        - ${{package.name}}-base=${{package.full-version}}
+      replaces:
+        - ${{package.name}}
+      runtime:
+        - bash # some helper scripts use bash
+        - openjdk-17-jre
     test:
       environment:
         contents:
