Improve test.

diff --git a/lsof.yaml b/lsof.yaml
--- a/lsof.yaml
+++ b/lsof.yaml
@@ -66,5 +66,20 @@ update:
 
 test:
   pipeline:
-    - name: version test
-      runs: /usr/bin/lsof -v
+    - name: Verify lsof installation
+      runs: |
+        set +x
+        fail() { echo "FAIL:" "$@"; exit 1; }
+
+        # both -h and -v output to stderr
+        lsof -h 2>&1 || fail "'lsof -h' exited $?"
+        echo "PASS: 'lsof -h' exited 0"
+
+        # output of 4.99.3 shows 4.99.0, and appears maybe to be by design.
+        # so only check for major.minor in output.
+        ver="${{package.version}}"
+        majmin=${ver%.*}
+        out=$(lsof -v 2>&1) || fail "'lsof -v' exited $?"
+        echo "$out" | grep -q -F -- "$majmin" ||
+          fail "'lsof -v' output did not include '$majmin': $out"
+        echo "PASS: 'lsof -v' contained version '$majmin' in output"
