resolve conflicts

diff --git a/Makefile.old b/Makefile.old
--- a/Makefile.old
+++ b/Makefile.old
@@ -206,12 +206,15 @@ $(compile_targets): compile/%:
 
 .PHONY: dev-container
 dev-container:
+	mkdir -p "${PWD}/.tmp"
 	docker run $(DOCKER_PLATFORM_ARG) --pull=always --privileged --rm -it \
 		--entrypoint="/bin/bash" \
 	    -v "${PWD}:${PWD}" \
+	    -v /var/run/docker.sock:/var/run/docker.sock \
 	    -w "${PWD}" \
 	    -e SOURCE_DATE_EPOCH=0 \
-	    -e HTTP_AUTH \
+	    -e TMPDIR="${PWD}/.tmp" \
+	    -e "HTTP_AUTH=basic:apk.cgr.dev:user:$(shell chainctl auth token --audience apk.cgr.dev)" \
 	    ghcr.io/wolfi-dev/sdk:latest -il
 
 PACKAGES_CONTAINER_FOLDER ?= /work/packages
@@ -302,9 +305,13 @@ check-bootstrap:
 		-k ${BOOTSTRAP_KEY} \
 		-r ${BOOTSTRAP_REPO}
 
-authget = tok=$$(chainctl auth token --audience=$(1)) || \
-  { echo "failed token from $(1) for target $@"; exit 1; }; \
+authget = if [ -n "$$HTTP_AUTH" ] && echo "$$HTTP_AUTH" | grep -q "$(1)"; then \
+    tok=$$(echo "$$HTTP_AUTH" | cut -d: -f4-); \
+  else \
+    tok=$$(chainctl auth token --audience=$(1)) || \
+      { echo "failed token from $(1) for target $@"; exit 1; }; \
+  fi; \
   mkdir -p $$(dirname $(2)) && \
   echo "auth-download[$(1)] to $(2) from $(3)" && \
   curl --fail -LS --silent -o $(2).tmp --user "user:$$tok" $(3) && \
-	mv "$(2).tmp" "$(2)"
+  mv "$(2).tmp" "$(2)"
