tests
Signed-off-by: Kaiming Zhang <kaiming.zhang@chainguard.dev>

diff --git a/modelmesh-runtime-adapter.yaml b/modelmesh-runtime-adapter.yaml
--- a/modelmesh-runtime-adapter.yaml
+++ b/modelmesh-runtime-adapter.yaml
@@ -47,4 +47,25 @@ pipeline:
 
   - name: TEST
     runs: |
-      exit 1
+      export CONTAINER_MEM_REQ_BYTES=1
+      if ! (mlserver-adapter | grep "MLServer runtime adapter started"); then
+        echo "mlserver-adapter failed"
+        exit 1
+      fi &
+      if ! (ovms-adapter | grep "OVMS Runtime started"); then
+        echo "ovms-adapter failed"
+        exit 1
+      fi &
+      if ! (torchserve-adapter | grep "TorchServe runtime adapter started" ); then
+        echo "torchserve-adapter failed"
+        exit 1
+      fi &
+      if ! (triton-adapter | grep "Triton runtime adapter started"); then
+        echo "triton-adapter failed"
+        exit 1
+      fi &
+      if ! (puller | grep "starting clean up of cached clients"); then
+        echo "puller failed"
+        exit 1
+      fi &
+      echo "All tests passed"
