chore(neuvector-db): Migrate to NeuVector package
This has fallen behind as we don't currently have automatation to cover
something like this. Move it to the main NeuVector package so that
it at least recieves updates when NeuVector updates

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/neuvector.yaml b/neuvector.yaml
--- a/neuvector.yaml
+++ b/neuvector.yaml
@@ -12,6 +12,7 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
+      - crane
       - glibc-dev
       - go
       - jansson-dev
@@ -165,6 +166,29 @@ subpackages:
       pipeline:
         - runs: |
             controller --help 2>&1 |pcregrep -M 'START.*\nUsage'
+
+  - name: neuvector-db
+    description: "NeuVector vulnerability database for the SUSE NeuVector Container Security Platform"
+    pipeline:
+      - runs: |
+          # Fetch NeuVector scanner
+          crane export neuvector/scanner:latest scanner.tar
+
+          # Extract image
+          mkdir -p scanner
+          tar xvf scanner.tar -C scanner
+
+          # Install DB
+          mkdir -p ${{targets.contextdir}}/etc/neuvector/db
+          cp scanner/etc/neuvector/db/cvedb ${{targets.contextdir}}/etc/neuvector/db/cvedb
+    test:
+      pipeline:
+        - runs: |
+            if [[ -f "/etc/neuvector/db/cvedb" ]]; then
+              echo "CVE DB found!" && exit 0
+            else
+              echo "CVE DB not found!" && exit 1
+            fi
 
 update:
   enabled: true
