fix: add neuvector-db to neuvector-scanner as subpackage. This address issues of the database not being built every day and adds versioning to the database, based on the scanner version.
Signed-off-by: Kyle Steere <kyle.steere@chainguard.dev>

diff --git a/neuvector-scanner.yaml b/neuvector-scanner.yaml
--- a/neuvector-scanner.yaml
+++ b/neuvector-scanner.yaml
@@ -8,15 +8,17 @@ package:
   dependencies:
     runtime:
       - ca-certificates
-      - neuvector-db
-      - neuvector-scanner-monitor
       - neuvector-scanner-task
       - neuvector-sigstore-interface
+    provides:
+      - neuvector-db
+      - neuvector-scanner-monitor
 
 environment:
   contents:
     packages:
       - busybox
+      - crane
 
 pipeline:
   - uses: git-checkout
@@ -59,6 +61,33 @@ subpackages:
           mkdir -p ${{targets.contextdir}}/usr/local/bin
           install -Dm755 monitor/monitor ${{targets.contextdir}}/usr/local/bin/monitor
 
+  - name: neuvector-db
+    description: NeuVector vulnerability database for the SUSE NeuVector Container Security Platform
+    pipeline:
+      - runs: |
+          # Fetch NeuVector scanner from docker hub
+          # https://hub.docker.com/r/neuvector/scanner/tags
+          # we don't use the dbgen tool for this since it's very slow and 
+          # super flaky. Extracting is faster and is more reliable.
+          # This may change in the future if neuvector isn't published to DH
+          crane export neuvector/scanner:${{package.version}} scanner.tar
+
+          # Extract image
+          mkdir -p scanner
+          tar xvf scanner.tar -C scanner
+
+          # Install DB
+          mkdir -p ${{targets.contextdir}}/etc/neuvector/db
+          cp scanner/etc/neuvector/db/cvedb ${{targets.contextdir}}/etc/neuvector/db/cvedb
+    test:
+      pipeline:
+        - runs: |
+            if [[ -f "/etc/neuvector/db/cvedb" ]]; then
+              echo "CVE DB found!" && exit 0
+            else
+              echo "CVE DB not found!" && exit 1
+            fi
+
 test:
   pipeline:
     - runs: |
@@ -68,6 +97,9 @@ test:
 
 update:
   enabled: true
+  schedule:
+    period: daily
+    reason: NeuVector scanner is updated daily for database updates
   git:
     tag-filter-prefix: v
     strip-prefix: v
