add tests for neuvector-prometheus-exporter
Signed-off-by: Furkan Türkal <furkan.turkal@chainguard.dev>

diff --git a/neuvector-prometheus-exporter.yaml b/neuvector-prometheus-exporter.yaml
--- a/neuvector-prometheus-exporter.yaml
+++ b/neuvector-prometheus-exporter.yaml
@@ -17,7 +17,10 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
+      - py3-gpep517
+      - py3-pip
       - py3-setuptools
+      - py3-wheel
       - python-3
       - wolfi-base
 
@@ -28,16 +31,40 @@ pipeline:
       repository: https://github.com/neuvector/prometheus-exporter.git
       tag: v${{package.version}}
 
-  - runs: |
-      install -dm755 "${{targets.destdir}}"/usr/bin
-      install -m 755 ./nv_exporter.py "${{targets.destdir}}"/usr/bin/nv_exporter.py
+  - runs: install -m 755 ./nv_exporter.py "${{targets.destdir}}"/usr/bin/nv_exporter.py
 
   - uses: strip
 
 test:
+  environment:
+    contents:
+      packages:
+        - python3
+        - py3-pip
   pipeline:
+    # Test that all the runtime dependencies are importable
     - runs: |
-        python3 nv_exporter.py -h
+        #!/bin/bash
+        set -euo pipefail
+        # List all the runtime required packages by removing the version constraints
+        # Also replace '-' with '_' in package names, otherwise 'charset-normalizer' will fail
+        pip freeze | cut -d"=" -f1 | awk '{print $1}' | tr '-' '_' > requirements.txt
+        cat requirements.txt
+        set -x
+        while IFS= read -r pkg; do
+          if [[ -n $pkg ]]; then
+            python3 -c "import $pkg"
+          fi
+        done < requirements.txt
+    # Test that the script can be run
+    - runs: python3 /usr/bin/nv_exporter.py --help
+    # Test that the entrypoint is working
+    - runs: |
+        export CTRL_API_SERVICE="dummy:7777"
+        export EXPORTER_PORT=8068
+        export CTRL_USERNAME=admin
+        export CTRL_PASSWORD=admin
+        python3 /usr/bin/nv_exporter.py | grep -q "Failed to resolve 'dummy'"
 
 update:
   enabled: true
@@ -46,4 +73,3 @@ update:
     strip-prefix: v
     tag-filter: v
     use-tag: true
-  
