datadog-agent{,-fips}-7.76: Adjust integrations-core commit
Signed-off-by: Sergio Durigan Junior <sergiodj@chainguard.dev>


Export:  2413cea6340b382feb7f0716d0c69ed61e521a9e

diff --git a/nextcloud-server-32.yaml b/nextcloud-server-32.yaml
--- a/nextcloud-server-32.yaml
+++ b/nextcloud-server-32.yaml
@@ -1,8 +1,8 @@
 #nolint:valid-pipeline-git-checkout-tag
 package:
-  name: nextcloud-server-33
-  version: "33.0.0"
-  epoch: 0
+  name: nextcloud-server-32
+  version: "32.0.6"
+  epoch: 0 # go/wolfi-rsc/nextcloud-server-32
   description: "Nextcloud server, a safe home for all your data"
   copyright:
     - license: AGPL-3.0-or-later
@@ -128,7 +128,7 @@ pipeline:
   - uses: fetch
     with:
       uri: https://download.nextcloud.com/server/releases/nextcloud-${{package.version}}.tar.bz2
-      expected-sha256: 6f7730902269c879f9f2ad4aa0a227cb16b5408ee46f093f68bd32633f741abf
+      expected-sha256: 44bc33fc0e31a650bb520bb123c0aaa6519b7f7b9386133d561ade77e53f7130
       directory: ${{targets.destdir}}/usr/src/nextcloud
       delete: true
 
@@ -147,13 +147,10 @@ pipeline:
       mkdir -p ${{targets.destdir}}/${PHP_INI_DIR}/conf.d
       mkdir -p ${{targets.destdir}}/etc/apache2/conf-available
 
-  # This commit must include a $major-version/ directory (e.g. 33/) matching the
-  # Nextcloud major version. Check https://github.com/nextcloud/docker for a
-  # commit that has the directory before bumping the package version.
   - uses: fetch
     with:
-      uri: https://github.com/nextcloud/docker/archive/145c97aed6dc421dfe55aecb759c0afe8a604c9e.tar.gz
-      expected-sha256: d5dc249648776785520481797da7f68d67fac8001d40922e687568ea7544e20e
+      uri: https://github.com/nextcloud/docker/archive/1f87830fd6f478c993248475979472aab1787a75.tar.gz
+      expected-sha256: d81f923488495594076c0baaeb6a741f14eeb842e389e65e95f3d7871791bb35
       directory: ./nextcloud-docker
       extract: true
       delete: true
@@ -269,7 +266,7 @@ update:
     identifier: nextcloud/server
     use-tag: true
     strip-prefix: v
-    tag-filter: v33.
+    tag-filter: v32.
 
 test:
   environment:
@@ -277,6 +274,8 @@ test:
       packages:
         - wait-for-it
         - curl
+        - crane
+        - gnutar
         - tini
         - procps
     accounts:
@@ -304,6 +303,62 @@ test:
         grep -i 'ServerRoot "/usr/local/apache2"' /etc/apache2/httpd.conf
         grep -i 'DocumentRoot "//var/www/html"' /etc/apache2/httpd.conf
         apachectl -S # Final sanity check to ensure the config files are valid
+    - name: Ensure the PHP modules match Nextcloud image
+      runs: |
+        /bin/bash -c '
+        set -eo pipefail
+
+        # Sometimes the tag is not available yet, so its ok to use the previous one
+        # e.g. 31.0.4 -> 31.0.3
+        tag=${{package.version}}
+        crane manifest nextcloud:$tag >/dev/null 2>&1 || tag=${tag%.*}.$(( ${tag##*.} - 1 ))
+
+        required_modules=$(crane export nextcloud:$tag - | \
+          tar -tvf - | \
+          grep "usr/local/lib/php/extensions/.*\.so$" | \
+          awk -F"/" "{print \$NF}" | \
+          sed "s/\.so\$//" | \
+          sort -u)
+
+        echo "Modules required by nextcloud:$tag:"
+        echo "$required_modules"
+
+        loaded_modules=$(php -m | tr "[:upper:]" "[:lower:]" | sed "s/zend opcache/opcache/")
+
+        missing_modules=()
+        while read -r module; do
+          if ! grep -iq "^${module}$" <<< "$loaded_modules"; then
+            missing_modules+=("$module")
+          fi
+        done <<< "$required_modules"
+
+        if [ ${#missing_modules[@]} -ne 0 ]; then
+          echo "Missing PHP modules: ${missing_modules[*]}"
+          exit 1
+        else
+          echo "All required PHP modules are loaded!"
+        fi
+        '
+    - name: Ensure the apache2-foreground loads the modules
+      runs: |
+        # Those modules are scraped from the upstream image `nextcloud:latest`: `apache2-foreground -e debug`
+        set -e
+        apache2-foreground -e debug 2>&1 | tee /tmp/apache2-foreground.log &>/dev/null 2>&1 &
+        PID=$!
+        sleep 5
+        set +e
+        wait $PID || true
+        kill $PID 2>/dev/null || true
+        sleep 5
+        OUTPUT=$(cat /tmp/apache2-foreground.log)
+        for m in mpm_prefork authn_file authn_core authz_host authz_groupfile authz_user authz_core access_compat auth_basic reqtimeout filter mime log_config env headers setenvif version unixd status autoindex dir alias deflate negotiation rewrite remoteip php; do
+          if ! echo "$OUTPUT" | grep -qi "loaded module $m"; then
+            echo "Module $m is not enabled."
+            echo "Output: $OUTPUT"
+            exit 1
+          fi
+        done
+        kill -KILL $(pidof apache2 httpd) 2>/dev/null || true # Ensure that all of the subprocesses are killed
     - working-directory: /var/www/html
       pipeline:
         - name: "start daemon on localhost"
