nginx-mainline: use mainline versions correctly
Signed-off-by: kranurag7 <81210977+kranurag7@users.noreply.github.com>

diff --git a/nginx-mainline.yaml b/nginx-mainline.yaml
--- a/nginx-mainline.yaml
+++ b/nginx-mainline.yaml
@@ -1,7 +1,8 @@
 package:
   name: nginx-mainline
+  # MAINLINE VERSIONS MUST USE ODD MINOR VERSIONS (e.g., 1.27.x, 1.29.x)
   # Must also bump njs at the same time
-  version: "1.28.0"
+  version: "1.29.0"
   epoch: 0
   description: HTTP and reverse proxy server (mainline version)
   copyright:
@@ -39,6 +40,12 @@ environment:
       - zeromq-dev
       - zlib-dev
 
+var-transforms:
+  - from: ${{package.version}}
+    match: '^(\d+)\.(\d+)\.(\d+)'
+    replace: '$2'
+    to: minor-version
+
 data:
   - name: modules
     items:
@@ -53,11 +60,21 @@ data:
 # TODO look at adding extra modules like alpine does https://git.alpinelinux.org/aports/tree/main/nginx/APKBUILD#n149
 # Also note the nginx inc config https://hg.nginx.org/pkg-oss/file/tip/alpine
 pipeline:
+  - name: validate-mainline-version
+    runs: |
+      # Ensure mainline version is odd (e.g., 1.27.x, 1.29.x)
+      MINOR=${{vars.minor-version}}
+      if [ $((MINOR % 2)) -eq 0 ]; then
+        echo "ERROR: nginx-mainline must use odd minor versions (e.g., 1.27.x, 1.29.x)"
+        echo "Current version: ${{package.version}} has even minor version: $MINOR"
+        exit 1
+      fi
+      echo "Version validation passed: ${{package.version}} is a valid mainline version"
   - uses: git-checkout
     with:
       repository: https://github.com/nginx/nginx.git
       tag: release-${{package.version}}
-      expected-commit: 481d28cb4e04c8096b9b6134856891dc52ecc68f
+      expected-commit: 235f409907fd60eb2d8f6ecdc0e5cb163dd6d45f
       destination: nginx-mainline
   - name: configure
     working-directory: nginx-mainline
@@ -320,5 +337,6 @@ update:
   github:
     identifier: nginx/nginx
     use-tag: true
-    tag-filter: release-1.28
+    # MAINLINE VERSIONS MUST USE ODD MINOR VERSIONS (e.g., 1.27.x, 1.29.x)
+    tag-filter: release-1.29
     strip-prefix: release-
