add functional test to all the subpackages and trim down some packages
Signed-off-by: YashPimple <yashpimple22@gmail.com>

diff --git a/op-geth.yaml b/op-geth.yaml
--- a/op-geth.yaml
+++ b/op-geth.yaml
@@ -8,16 +8,13 @@ package:
     - license: GPL-3.0-or-later
   dependencies:
     runtime:
-      - busybox
+      - coreutils
 
 environment:
   contents:
     packages:
       - ca-certificates
-      - gcc
-      - git
       - linux-headers
-      - zlib-dev
 
 pipeline:
   - uses: git-checkout
@@ -66,24 +63,15 @@ subpackages:
         - runs: |
             clef --version
             clef --help
-      # Cannot create a functional test because clef requires an interactive shell and dynamic input
-        # - runs: |
-        #     cat <<EOF > .clef_init.exp
-        #     #!/usr/bin/expect -f
-        #     spawn ./build/bin/clef init
-        #     expect "Enter 'ok' to proceed:"
-        #     send "ok\r"
-        #     expect "Password:"
-        #     send "1234567890\r"
-        #     expect "Repeat password:"
-        #     send "1234567890\r"
-        #     expect eof
-        #     EOF
-          
-        #     chmod +x .clef_init.exp
-        #     ./clef_init.exp
-
-        #     test -f /root/.clef/masterseed.json && echo "Clef init successful" || { echo "Clef init failed"; exit 1; }
+        - name: "Run clef init"
+          runs: |
+            apk add cmd:script
+            script -q -c "clef init" /dev/null <<EOF
+            ok
+            1234567890
+            1234567890
+            EOF
+            test -f /root/.clef/masterseed.json && echo "Clef init successful" || { echo "Clef init failed"; exit 1; }
 
   - name: ${{package.name}}-abigen
     pipeline:
@@ -157,6 +145,7 @@ subpackages:
         - runs: |
             evm --version
             evm --help
+            evm run --code 0x 2>/dev/null && echo "Success" || echo "Failed"
 
   - name: ${{package.name}}-rlpdump
     pipeline:
@@ -168,6 +157,8 @@ subpackages:
       pipeline:
         - runs: |
             rlpdump --help
+            echo "c0" | rlpdump | grep -q '"c"' && echo "rlpdump stdin test passed" || { echo "rlpdump stdin test failed"; exit 1; } # Test: Decode hex "c0" using stdin and validate output
+            rlpdump -hex c0 | grep -q '\[\]' && echo "rlpdump hex test passed" || { echo "rlpdump hex test failed"; exit 1; }
 
 test:
   pipeline:
@@ -175,6 +166,19 @@ test:
       runs: |
         geth version | grep -qi "${{package.version}}-stable"
         geth --help
+    - runs: |
+        geth --dev --nodiscover --maxpeers 0 --http --http.addr "127.0.0.1" --http.port "8545" --http.api "eth,net,web3" --allow-insecure-unlock &
+        GETH_PID=$!
+        sleep 5  # Wait for Geth to initialize
+
+        if ps | grep -q "[g]eth"; then
+          echo "Geth started successfully"
+        else
+          echo "Failed to start Geth"
+          exit 1
+        fi
+
+        kill $GETH_PID
 
 update:
   enabled: true
