opentelemetry-java-contrib: refresh package
Bump to java 21, required by some of the plugins on aarch64.

Introduce subpackage tests.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/opentelemetry-java-contrib.yaml b/opentelemetry-java-contrib.yaml
--- a/opentelemetry-java-contrib.yaml
+++ b/opentelemetry-java-contrib.yaml
@@ -12,9 +12,10 @@ environment:
       - bash
       - busybox
       - ca-certificates-bundle
-      - openjdk-17-default-jdk
+      - openjdk-21
+      - openjdk-21-default-jdk
   environment:
-    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
+    JAVA_HOME: /usr/lib/jvm/java-21-openjdk
 
 pipeline:
   - uses: git-checkout
@@ -62,6 +63,17 @@ subpackages:
       - runs: |
           mkdir -p ${{targets.contextdir}}/usr/share/java/${{range.key}}
           mv /home/build/${{range.key}}/build/libs/opentelemetry-${{range.key}}-${{package.version}}.jar ${{targets.contextdir}}/usr/share/java/${{range.key}}
+    test:
+      pipeline:
+        - name: "verify jars are included"
+          runs: |
+            dir="/usr/share/java/${{range.key}}"
+            file="*.jar"
+            if ! find "${dir}" -name "${file}" | grep -q . ; then
+              echo "FAIL: unable to find any ${file} in ${dir}" >&2
+              exit 1
+            fi
+            echo "PASS: found some ${file} in ${dir}"
 
   - range: contrib-components
     name: ${{package.name}}-${{range.key}}-compat
@@ -69,6 +81,20 @@ subpackages:
       - runs: |
           mkdir -p ${{targets.contextdir}}/opt
           ln -sf /usr/share/java/${{range.key}}/opentelemetry-${{range.key}}-${{package.version}}.jar ${{targets.contextdir}}/opt/opentelemetry-${{range.key}}-${{package.version}}.jar
+    test:
+      pipeline:
+        - name: "verify links are correctly configured"
+          runs: |
+            dest="/usr/share/java/${{range.key}}/opentelemetry-${{range.key}}-${{package.version}}.jar"
+            link_name="/opt/opentelemetry-${{range.key}}-${{package.version}}.jar"
+            link="$(readlink ${link_name})"
+            if [ "${link}" != "${dest}" ] ; then
+              echo "FAIL: link ${link_name} doesn't point to the expected destination" >&2
+              echo "FAIL: expected: ${link_name} -> ${dest}" >&2
+              echo "FAIL: got: ${link_name} -> ${link}" >&2
+              exit 1
+            fi
+            echo "PASS: link ${link_name} points to ${dest} as expected"
 
 update:
   enabled: true
@@ -78,4 +104,4 @@ update:
 
 test:
   pipeline:
-    - uses: test/emptypackage
+    - uses: test/tw/byproductpackage
