opentelemetry-cpp: refresh package tests
Refresh package tests.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/opentelemetry-cpp.yaml b/opentelemetry-cpp.yaml
--- a/opentelemetry-cpp.yaml
+++ b/opentelemetry-cpp.yaml
@@ -63,6 +63,9 @@ subpackages:
         - opentelemetry-cpp
     pipeline:
       - uses: split/static
+    test:
+      pipeline:
+        - uses: test/tw/staticpackage
 
   - name: opentelemetry-cpp-dev
     description: The OpenTelemetry C++ Client development files
@@ -79,6 +82,15 @@ subpackages:
 test:
   pipeline:
     - uses: test/tw/ldd-check
+    - name: "verify .so files exist"
+      runs: |
+        dir="/usr/lib"
+        name="*.so"
+        if ! find "${dir}" -name "${name}" -type f | grep -q . ; then
+          echo "FAIL: no ${name} files found in ${dir}" >&2
+          exit 1
+        fi
+        echo "PASS: some ${name} files found in ${dir}"
 
 update:
   enabled: true
