opentelemetry-cpp: refresh package tests
Refresh package tests.

Drop the -static package, as is empty.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/opentelemetry-cpp.yaml b/opentelemetry-cpp.yaml
--- a/opentelemetry-cpp.yaml
+++ b/opentelemetry-cpp.yaml
@@ -1,10 +1,12 @@
 package:
   name: opentelemetry-cpp
   version: "1.24.0"
-  epoch: 0
+  epoch: 1
   description: The OpenTelemetry C++ Client
   copyright:
     - license: Apache-2.0
+  dependencies:
+    provider-priority: 0
 
 var-transforms:
   - from: ${{package.version}}
@@ -69,23 +71,30 @@ subpackages:
     test:
       pipeline:
         - uses: test/tw/ldd-check
-
-  - name: opentelemetry-cpp-static
-    description: The OpenTelemetry C++ Client static libraries
-    pipeline:
-      - uses: split/static
+        - name: "verify .so files exist"
+          runs: |
+            dir="/usr/lib"
+            name="*.so"
+            if ! find "${dir}" -name "${name}" -type f | grep -q . ; then
+              echo "FAIL: no ${name} files found in ${dir}" >&2
+              exit 1
+            fi
+            echo "PASS: some ${name} files found in ${dir}"
 
   - name: opentelemetry-cpp-dev
     description: The OpenTelemetry C++ Client development files
     dependencies:
       runtime:
         - libopentelemetry-cpp${{vars.soversion}}=${{package.full-version}}
-        - opentelemetry-cpp-static=${{package.full-version}}
     pipeline:
       - uses: split/dev
     test:
       pipeline:
         - uses: test/pkgconf
+
+test:
+  pipeline:
+    - uses: test/tw/byproductpackage
 
 update:
   enabled: true
