added tests for basic java packages

diff --git a/openjdk-18.yaml b/openjdk-18.yaml
--- a/openjdk-18.yaml
+++ b/openjdk-18.yaml
@@ -238,3 +238,36 @@ subpackages:
 update:
   enabled: false
   exclude-reason: This version is EOL and only built to enable bootstrapping
+
+test:
+  environment:
+    contents:
+      packages:
+        - openjdk-18-default-jdk
+        - openjdk-18-jmods
+    environment:
+      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
+  pipeline:
+    # Test a basic Hello World
+    - name: Display Java version
+      runs: |
+        java -version
+    - name: Check JDK version
+      runs: |
+        version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
+        if [[ "$version" != "18"* ]]; then
+          echo "Expected Java version 18, but got $version"
+          exit 1
+        fi
+    - working-directory: basic
+      runs: |
+        echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
+        javac HelloWorld.java
+        java HelloWorld
+    # Test a basic HTTP connection
+    - working-directory: basic
+      runs: |
+        # echo 'import java.net.HttpURLConnection; import java.net.URL; public class HttpTest { public static void main(String[] args) { try { URL url = new URL("http://example.com"); HttpURLConnection con = (HttpURLConnection) url.openConnection(); con.setRequestMethod("GET"); int status = con.getResponseCode(); if (status != 200) { System.out.println("Failed to connect, status code: " + status); System.exit(1); } System.out.println("HTTP connection successful"); } catch (Exception e) { System.out.println("Exception: " + e.getMessage()); System.exit(1); } } }' > RequestTest.java
+        echo 'import java.net.http.*; import java.net.URI; public class RequestTest { public static void main(String[] args) throws Exception { HttpClient client = HttpClient.newHttpClient(); HttpRequest request = HttpRequest.newBuilder().uri(URI.create("http://example.com")).build(); HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString()); if (response.statusCode() != 200) { System.out.println("Failed to perform HTTP request, status code: " + response.statusCode()); System.exit(1); } System.out.println("HTTP request successful"); } }' > RequestTest.java
+        javac RequestTest.java
+        java RequestTest
