add missing group to test
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/osixia-docker-openldap.yaml b/osixia-docker-openldap.yaml
--- a/osixia-docker-openldap.yaml
+++ b/osixia-docker-openldap.yaml
@@ -72,6 +72,19 @@ test:
     contents:
       packages:
         - ${{package.name}}-compat
+    # We will set the required accounts and permissions in the Apko manifest.
+    # This is a workaround to avoid permission errors when running slapd.
+    # The chown and chmod commands below will be defined in the image.
+    accounts:
+      groups:
+        - groupname: openldap
+          gid: 911
+        - groupname: docker_env
+          gid: 911
+      users:
+        - username: openldap
+          gid: 911
+          uid: 911
     environment:
       LDAP_ORGANISATION: "foo"
       LDAP_DOMAIN: "bar"
@@ -79,4 +92,18 @@ test:
       CONTAINER_SERVICE_DIR: "/container/service"
       CONTAINER_STATE_DIR: "/container/run/state"
   pipeline:
-    - runs: python -m trace --count -C . /container/tool/run --loglevel=trace
+    # We will set the required accounts and permissions in the Apko manifest.
+    - runs: chown -R openldap:openldap /etc/openldap /var/lib/openldap
+    # Ensure core functionality (slapd) is working with openldap user.
+    - runs: |
+        slapd -d 1 -h 'ldap:/// ldapi:///' -u openldap -g openldap > /tmp/slapd.log 2>&1 &
+        PID=$!
+        sleep 5 # ensure that enough time is given for the logs to get written
+        if ! cat /tmp/slapd.log | grep -i 'slapd starting'; then
+          cat /tmp/slapd.log
+          exit 1
+        fi
+        kill $PID
+    # Ensure that the container image entrypoint is working.
+    - runs: |
+        python -m trace --count -C . /container/tool/run --loglevel=trace
