verbose readlink, flip the if-else check
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/pdns-5.2.yaml b/pdns-5.2.yaml
--- a/pdns-5.2.yaml
+++ b/pdns-5.2.yaml
@@ -241,8 +241,17 @@ subpackages:
     test:
       pipeline:
         - runs: |
-            test "$(readlink /usr/local/sbin/pdns_recursor)" = "/usr/bin/pdns_recursor"
-            test "$(readlink /usr/local/sbin/rec_control)" = "/usr/bin/rec_control"
+            for bin in pdns_recursor rec_control; do
+              found="$(readlink -fv /usr/local/sbin/${bin})"
+              expected="/usr/bin/${bin}"
+              if [ $found != $expected ]; then
+                echo "Invalid symlink for $bin!"
+                echo "Expected: $expected"
+                echo "Found: $found"
+                exit 1
+              fi
+              echo "Valid symlink for $bin. Found: $found"
+            done
 
   - range: backends
     name: ${{package.name}}-backend-${{range.key}}
@@ -277,10 +286,10 @@ subpackages:
         - runs: |
             # saxfr is a special case, it requires IP-address, port, zone to run and does not have a --help option.
             # So we handle it separately.
-            if [ "${{range.key}}" != "saxfr" ]; then
-              ${{range.key}} --help
-            else
+            if [ "${{range.key}}" = "saxfr" ]; then
               saxfr 127.0.0.1 53 example.com
+            else
+              "${{range.key}}" --help
             fi
 
   - name: ${{package.name}}-backends-all
