Add melange tests
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/perl-namespace-autoclean.yaml b/perl-namespace-autoclean.yaml
--- a/perl-namespace-autoclean.yaml
+++ b/perl-namespace-autoclean.yaml
@@ -53,3 +53,34 @@ update:
   enabled: true
   release-monitor:
     identifier: 6572
+
+test:
+  pipeline:
+    - name: "Check Perl Module Installation"
+      runs: |
+        if perl -Mnamespace::autoclean -e 'print $namespace::autoclean::VERSION' >/dev/null 2>&1; then
+          echo "perl-namespace-autoclean installed successfully."
+        else
+          echo "perl-namespace-autoclean installation failed!" && exit 1
+        fi
+    - name: "Basic Functionality Test"
+      runs: |
+        cat <<EOF > test_autoclean.pl
+        #!/usr/bin/perl
+        use strict;
+        use warnings;
+        use Test::More tests => 1;
+        use List::Util qw(sum);
+        use namespace::autoclean;
+
+        {
+            package MyPackage;
+            sub new { return bless {}, shift; }
+            sub calculate { return sum(1, 2, 3); }
+        }
+
+        my \$obj = MyPackage->new();
+        ok(!MyPackage->can('sum'), 'sum is no longer available after namespace::autoclean');
+        EOF
+
+        perl test_autoclean.pl || (echo "Basic functionality test failed!" && exit 1)
