Symlink PG binaries to /usr/local
Signed-off-by: Aditvil-Dev <aditya.tirmanwar@chainguard.dev>

diff --git a/pgadmin4-17.yaml b/pgadmin4-17.yaml
--- a/pgadmin4-17.yaml
+++ b/pgadmin4-17.yaml
@@ -3,7 +3,7 @@
 package:
   name: pgadmin4-17
   version: "8.14"
-  epoch: 0
+  epoch: 1
   description: "pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source database in the world."
   copyright:
     - license: PostgreSQL
@@ -113,6 +113,13 @@ pipeline:
       # allow site-packages
       sed -i "s|include-system-site-packages = false|include-system-site-packages = true|g" ${{targets.destdir}}/pgadmin4/venv/pyvenv.cfg
 
+      # Copy the PG binaries
+      mkdir  -p ${{targets.destdir}}/usr/local/pgsql-${{vars.pg-version}}
+      ln -sf  /usr/libexec/postgresql${{vars.pg-version}}/pg_dump ${{targets.destdir}}/usr/local/pgsql-${{vars.pg-version}}/
+      ln -sf  /usr/libexec/postgresql${{vars.pg-version}}/pg_dumpall ${{targets.destdir}}/usr/local/pgsql-${{vars.pg-version}}/
+      ln -sf  /usr/libexec/postgresql${{vars.pg-version}}/pg_restore ${{targets.destdir}}/usr/local/pgsql-${{vars.pg-version}}/
+      ln -sf  /usr/libexec/postgresql${{vars.pg-version}}/psql ${{targets.destdir}}/usr/local/pgsql-${{vars.pg-version}}/
+
 test:
   environment:
     contents:
@@ -138,6 +145,16 @@ test:
         sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
         createdb testdb
         psql -lqt | cut -d \| -f 1 | grep -qw testdb
+    - name: "Verify PostgreSQL binaries"
+      runs: |
+        BINARIES=(pg_dump pg_dumpall pg_restore psql)
+        for BIN in "${BINARIES[@]}"; do
+          if [ ! -L "/usr/local/pgsql-${{vars.pg-version}}/$BIN" ]; then
+            echo "Binary $BIN is missing or not linked correctly"
+            exit 1
+          fi
+        done
+        echo "All PostgreSQL binaries are installed and linked correctly."
     - name: "Start pgAdmin4 Server"
       uses: test/daemon-check-output
       working-directory: /pgadmin4
