remove usage of git-checkout from test-pipelines
Signed-off-by: Aditvil-Dev <aditya.tirmanwar@chainguard.dev>

diff --git a/pgaudit-17.yaml b/pgaudit-17.yaml
--- a/pgaudit-17.yaml
+++ b/pgaudit-17.yaml
@@ -1,8 +1,6 @@
-# pgAudit 17.0 is intended to support PostgreSQL 17.
-# https://github.com/pgaudit/pgaudit/blob/master/README.md#postgresql-version-compatibility
 package:
   name: pgaudit-17
-  version: "17.1"
+  version: '17.1'
   epoch: 3
   description: PostgreSQL Audit Extension
   copyright:
@@ -19,7 +17,6 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      # NOTE: align with clang version in postgresql-*-dev
       - clang-19
       - glibc-dev
       - krb5-dev
@@ -32,14 +29,17 @@ pipeline:
       tag: ${{package.version}}
       expected-commit: 538f89a93d8fd0d8913f3d740cacaea7b7eb66d9
 
-  - runs: |
-      mkdir -p ${{targets.destdir}}/usr/share/postgresql/extension
+  - runs: 'mkdir -p ${{targets.destdir}}/usr/share/postgresql/extension
+
       make USE_PGXS=1 DESTDIR=${{targets.destdir}} PG_CONFIG=/usr/bin/pg_config install
+
+    '
 
 test:
   environment:
     contents:
       packages:
+        - git
         - glibc-locales
         - make
         - postgresql-17
@@ -52,30 +52,16 @@ test:
       PGUSER: wolfi
   pipeline:
     - uses: test/tw/ldd-check
-    - uses: git-checkout
-      with:
-        repository: https://github.com/pgaudit/pgaudit.git
-        tag: ${{package.version}}
-        expected-commit: 538f89a93d8fd0d8913f3d740cacaea7b7eb66d9
-    - runs: |
-        # Based on upstream tests in https://github.com/pgaudit/pgaudit/tree/main/test
-        useradd $PGUSER
-        sudo -u $PGUSER initdb -D $PGDATA
-        echo "shared_preload_libraries = 'pgaudit'" >> ${PGDATA}/postgresql.conf
-        if ! sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start; then
-          echo "!!! SERVER STARTUP FAILED"
-          cat /tmp/logfile
-          exit 1
-        fi
+    - name: Clone pgaudit repo and run tests
+      runs: 'git clone --branch ${{package.version}} --depth 1 https://github.com/pgaudit/pgaudit.git
 
-        if ! make installcheck USE_PGXS=1; then
-          echo "!!! INSTALLCHECK FAILED"
-          cat regression.diffs
-          exit 1
-        fi
+        cd pgaudit
+
+        # Original test commands would go here'
+    - runs: "# Based on upstream tests in https://github.com/pgaudit/pgaudit/tree/main/test\nuseradd $PGUSER\nsudo -u $PGUSER initdb -D $PGDATA\necho \"shared_preload_libraries = 'pgaudit'\" >> ${PGDATA}/postgresql.conf\nif ! sudo -u $PGUSER pg_ctl -D $PGDATA -l /tmp/logfile start; then\n  echo \"!!! SERVER STARTUP FAILED\"\n  cat /tmp/logfile\n  exit 1\nfi\n\nif ! make installcheck USE_PGXS=1; then\n  echo \"!!! INSTALLCHECK FAILED\"\n  cat regression.diffs\n  exit 1\nfi\n"
 
 update:
   enabled: true
   github:
     identifier: pgaudit/pgaudit
-    tag-filter-prefix: 17.
+    tag-filter-prefix: 17.0
