test: Introduce basic test
Signed-off-by: Joshua Powers <joshua.powers@chainguard.dev>

diff --git a/php-8.3-pecl-mongodb.yaml b/php-8.3-pecl-mongodb.yaml
--- a/php-8.3-pecl-mongodb.yaml
+++ b/php-8.3-pecl-mongodb.yaml
@@ -56,6 +56,27 @@ pipeline:
 
   - uses: strip
 
+test:
+  environment:
+    contents:
+      packages:
+        - php-${{vars.phpMM}}
+  pipeline:
+    - name: Verify Extension is Loaded
+      runs: |
+        echo "<?php
+        if (!extension_loaded('mongodb')) {
+            die('The MongoDB PHP extension is not loaded. Please install or enable it.\n');
+        }
+        ?>" > test.php
+        php test.php
+        if [ $? -ne 0 ]; then
+          echo "Test failed: Unable to use mongodb extension."
+          exit 1
+        else
+          echo "Test passed: mongodb extension is functional."
+        fi
+
 update:
   enabled: true
   release-monitor:
