add src directory
Signed-off-by: Sanjay Kumar <sanjay.kumar@chainguard.dev>

diff --git a/php-8.4-ddtrace.yaml b/php-8.4-ddtrace.yaml
--- a/php-8.4-ddtrace.yaml
+++ b/php-8.4-ddtrace.yaml
@@ -8,6 +8,7 @@ package:
   dependencies:
     runtime:
       - ${{package.name}}-config
+      - ${{package.name}}-src
       - php-${{vars.phpMM}}
 
 var-transforms:
@@ -54,12 +55,25 @@ subpackages:
       - runs: |
           mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
           echo "extension=ddtrace.so" > "${{targets.subpkgdir}}/etc/php/conf.d/ddtrace.ini"
+          echo "datadog.trace.sources_path=\"/usr/share/dd-trace-php/src\"" >> "${{targets.subpkgdir}}/etc/php/conf.d/ddtrace.ini"
+
+  - name: ${{package.name}}-src
+    description: "Datadog PHP tracer source files"
+    dependencies:
+      runtime:
+        - php-${{vars.phpMM}}
+    pipeline:
+      - runs: |
+          mkdir -p "${{targets.subpkgdir}}/usr/share/dd-trace-php"
+          cp -r src "${{targets.subpkgdir}}/usr/share/dd-trace-php/"
 
 test:
   environment:
     contents:
       packages:
         - php-${{vars.phpMM}}
+        - ${{package.name}}-config
+        - ${{package.name}}-src
   pipeline:
     - name: Verify Extension is Loaded
       runs: |
@@ -92,6 +106,15 @@ test:
           exit 1
         else
           echo "Test passed: ddtrace extension is functional."
+        fi
+    - name: Test PHP Class Availability
+      runs: |
+        php -r 'if (!class_exists("DDTrace\\GlobalTracer")) exit(1);'
+        if [ $? -ne 0 ]; then
+          echo "Test failed: DDTrace\\GlobalTracer class is not available."
+          exit 1
+        else
+          echo "Test passed: DDTrace\\GlobalTracer class is available."
         fi
     - uses: test/tw/ldd-check
 
