Merge branch 'azurite' of github.com:bigpod98/stereo into azurite
Export:  b1bf01911e0e053c86774c78a054230f60adeeaf

diff --git a/php-8.3-pdo_snowflake.yaml b/php-8.3-pdo_snowflake.yaml
--- a/php-8.3-pdo_snowflake.yaml
+++ b/php-8.3-pdo_snowflake.yaml
@@ -1,7 +1,7 @@
 package:
   name: php-8.3-pdo_snowflake
   version: "4.0.0"
-  epoch: 1 # go/wolfi-rsc/php-8.3-pdo_snowflake
+  epoch: 0 # go/wolfi-rsc/php-8.3-pdo_snowflake
   description: "Snowflake driver that uses the PHP Data Objects (PDO) extension"
   copyright:
     - license: Apache-2.0
@@ -83,7 +83,13 @@ test:
   pipeline:
     - name: Verify Extension is Loaded
       runs: |
-        php -m | grep -F 'pdo_snowflake'
+        php -m | grep -i 'pdo_snowflake'
+        if [ $? -ne 0 ]; then
+          echo "Test failed: pdo snowflake extension is not loaded."
+          exit 1
+        else
+          echo "Test passed: pdo snowflake extension is loaded."
+        fi
     - uses: test/tw/ldd-check
 
 update:
