test(prism): test the mock and proxy servers
Adding more functional tests to the prism package. For the mock server, we're testing the mocked endpoints and the request validation feature. For the proxy server, we're testing request forwarding, and its ability to mock requests that are not implemented upstream. Also changed the test spec files to make them more focused.

https://github.com/chainguard-dev/image-requests/issues/3751
Signed-off-by: Sam Singh Anantha <samsinghanantha@gmail.com>

diff --git a/prism.yaml b/prism.yaml
--- a/prism.yaml
+++ b/prism.yaml
@@ -92,21 +92,98 @@ test:
         - nodejs
         - npm
         - coreutils
+        - curl
   pipeline:
-    - name: Test version
+    - name: Test help
       runs: |
         ls -la /usr/src/prism/packages/cli/dist/index.js
         prism help
     - name: Test version
       runs: |
         prism --version | tee >(grep "${{package.version}}")
-    - name: Test mock
+    - name: Test mock & proxy servers
       runs: |
         # From "Mocking" in prism README (https://github.com/stoplightio/prism/blob/master/README.md#mocking)
-        timeout 5s prism mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml \
-        | tee >(grep "Prism is listening")
-    - name: Test proxy
-      runs: |
+        # Start the mock server
+        prism mock petstore-mock-spec.yaml &
+        sleep 2
+        MOCK_BASE_URL="http://127.0.0.1:4010/pets"
+        
+        # Setup test method
+        check_status() {
+          if [ "$1" -eq "$2" ]; then
+            echo "Test passed for: $3 (Expected: $2, Got: $1)"
+          else
+            echo "Test failed for: $3 (Expected: $2, Got: $1)"
+            exit 1
+          fi
+        }
+        # Test the mock API endpoints
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$MOCK_BASE_URL?limit=10&tags=dog")
+        check_status $response 200 "GET /pets with limit and tags"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$MOCK_BASE_URL")
+        check_status $response 200 "GET /pets without parameters"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$MOCK_BASE_URL?limit=abc")
+        check_status $response 422 "GET /pets with invalid limit"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$MOCK_BASE_URL" \
+          -H "Content-Type: application/json" \
+          -d '{"name": "Fluffy", "tag": "dog"}')
+        check_status $response 200 "POST /pets (Create a new pet)"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$MOCK_BASE_URL" \
+          -H "Content-Type: application/json" \
+          -d '{"tag": "cat"}')
+        check_status $response 422 "POST /pets without required field"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$MOCK_BASE_URL/123")
+        check_status $response 200 "GET /pets/123 (Fetch by ID)"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$MOCK_BASE_URL/abc")
+        check_status $response 422 "GET /pets/abc with invalid ID"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" -H "Prefer: code=404" "$MOCK_BASE_URL/999")
+        check_status $response 404 "GET /pets/999 but force 404"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "$MOCK_BASE_URL/1")
+        check_status $response 204 "DELETE /pets/123 (Delete by ID)"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE "$MOCK_BASE_URL/abc")
+        check_status $response 422 "DELETE /pets/abc with invalid ID"
+
+        response=$(curl -s -D - -o /dev/null -X POST "$MOCK_BASE_URL" \
+          -H "Content-Type: application/json" \
+          -d '{"tag":"dog"}')
+        validation_error=$(echo "$response" | grep "sl-violations")
+        if [[ "$validation_error" == *"required property 'name'"* ]]; then
+          echo "Validation method is working as expected"
+        else
+          echo "Validation method is failing"
+          exit 1
+        fi
+        
+        # Test the proxy server
         # From "Validation Proxy" in prism README (https://github.com/stoplightio/prism/blob/master/README.md/#validation-proxy)
-        timeout 5s prism proxy petstore.oas2.yaml https://petstore.swagger.io/v2 \
-        | tee >(grep "Prism is listening")
+        # Start the proxy server
+        prism proxy petstore-proxy-spec.yaml http://localhost:4010 --errors -p 3000 &
+        sleep 2
+        PROXY_BASE_URL="http://localhost:3000/pets"
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" "$PROXY_BASE_URL")
+        check_status $response 200 "GET /pets via proxy"
+
+        # this returns a 501 because the mock specification does not have a PUT method
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT "$MOCK_BASE_URL/123" \
+          -H "Content-Type: application/json" \
+          -d '{"name": "Fluffy", "tag": "dog"}')
+        check_status $response 501 "PUT /pets/123 via proxy"
+
+        # when the same put request is made to the proxy, it returns a 200, because it mocks the unimplemeted request
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT "$PROXY_BASE_URL/123" \
+          -H "Content-Type: application/json" \
+          -d '{"name": "Fluffy", "tag": "dog"}')
+        check_status $response 200 "PUT /pets/123 via proxy"
+        
+
