Add prometheus http_server test to the melange build file
Co-authored-by: Mark McCormick <mark.mccormick@chainguard.dev>
Signed-off-by: Lionel Herbet <lionel.herbet@orange.com>

diff --git a/prometheus-jmx-exporter.yaml b/prometheus-jmx-exporter.yaml
--- a/prometheus-jmx-exporter.yaml
+++ b/prometheus-jmx-exporter.yaml
@@ -50,3 +50,29 @@ update:
   github:
     identifier: prometheus/jmx_exporter
     strip-prefix: parent-
+
+test:
+  environment:
+    contents:
+      packages:
+        - openjdk-11
+        - openjdk-11-default-jvm
+        - ${{package.name}}-httpserver
+  pipeline:
+    - name: Create a sample config files
+      runs: |
+        echo -e "rules:\n- pattern: \".*\"" > agent-config.yaml
+        echo -e "hostPort: localhost:1234\nrules:\n- pattern: \".*\"" > server-config.yaml
+    - name: Verify agent jar
+      runs: |
+        java -javaagent:/usr/lib/prometheus/jmx_prometheus_javaagent.jar=1234:agent-config.yaml --version
+    - name: Verify httpserver jar
+      runs: |
+        java -jar /usr/lib/prometheus/jmx_prometheus_httpserver.jar 1234 server-config.yaml > output.log 2>&1 &
+        sleep 10
+        if ! grep -q 'io.prometheus.jmx.WebServer | Running' output.log; then
+          echo "Expected log message not found" >&2
+          cat output.log
+          exit 1
+        fi
+
