5 more automated test blocks
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-alabaster.yaml b/py3-alabaster.yaml
--- a/py3-alabaster.yaml
+++ b/py3-alabaster.yaml
@@ -35,3 +35,21 @@ update:
   enabled: true
   github:
     identifier: bitprophet/alabaster
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="alabaster"
+        OUTPUT=$(python -c "import $LIBRARY" 2>&1)
+
+        if echo "$OUTPUT" | grep -q "No module named"; then
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-annotated-types.yaml b/py3-annotated-types.yaml
--- a/py3-annotated-types.yaml
+++ b/py3-annotated-types.yaml
@@ -46,3 +46,21 @@ update:
   github:
     identifier: annotated-types/annotated-types
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="annotated_types"
+        OUTPUT=$(python -c "import $LIBRARY" 2>&1)
+
+        if echo "$OUTPUT" | grep -q "No module named"; then
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-antlr4-python3-runtime.yaml b/py3-antlr4-python3-runtime.yaml
--- a/py3-antlr4-python3-runtime.yaml
+++ b/py3-antlr4-python3-runtime.yaml
@@ -44,3 +44,21 @@ update:
   enabled: true
   github:
     identifier: antlr/antlr4
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="antlr4_python3_runtime"
+        OUTPUT=$(python -c "import $LIBRARY" 2>&1)
+
+        if echo "$OUTPUT" | grep -q "No module named"; then
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
