yamming
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-click-aliases.yaml b/py3-click-aliases.yaml
--- a/py3-click-aliases.yaml
+++ b/py3-click-aliases.yaml
@@ -42,3 +42,22 @@ update:
     identifier: click-contrib/click-aliases
     strip-prefix: v
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="click_aliases"
+        IMPORT_STATEMENT="Max retries reached."
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-gcsfs.yaml b/py3-gcsfs.yaml
--- a/py3-gcsfs.yaml
+++ b/py3-gcsfs.yaml
@@ -44,3 +44,22 @@ update:
   manual: false
   github:
     identifier: fsspec/gcsfs
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="gcsfs"
+        IMPORT_STATEMENT="import gcsfs"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-glom.yaml b/py3-glom.yaml
--- a/py3-glom.yaml
+++ b/py3-glom.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-glom
   version: 23.5.0
   epoch: 0
-  description: "Python's nested data operator (and CLI), for all your declarative restructuring needs. Got data? Glom it!"
+  description: Python's nested data operator (and CLI), for all your declarative restructuring needs. Got data? Glom it!
   copyright:
     - license: BSD-3-Clause
   dependencies:
@@ -44,3 +44,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 120576
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="glom"
+        IMPORT_STATEMENT="import glom"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-google-cloud-storage.yaml b/py3-google-cloud-storage.yaml
--- a/py3-google-cloud-storage.yaml
+++ b/py3-google-cloud-storage.yaml
@@ -45,3 +45,22 @@ update:
   github:
     identifier: googleapis/python-storage
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="google_cloud_storage"
+        IMPORT_STATEMENT="import google-cloud-storage"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-gpep517.yaml b/py3-gpep517.yaml
--- a/py3-gpep517.yaml
+++ b/py3-gpep517.yaml
@@ -1,8 +1,8 @@
 package:
   name: py3-gpep517
-  version: "15"
+  version: '15'
   epoch: 2
-  description: "PEP517 build system support for distros"
+  description: PEP517 build system support for distros
   copyright:
     - license: MIT
   dependencies:
@@ -39,3 +39,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 255912
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="gpep517"
+        IMPORT_STATEMENT="from gpep517 import __version__"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-greenlet.yaml b/py3-greenlet.yaml
--- a/py3-greenlet.yaml
+++ b/py3-greenlet.yaml
@@ -36,3 +36,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 6870
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="greenlet"
+        IMPORT_STATEMENT="import greenlet"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-grpcio-reflection.yaml b/py3-grpcio-reflection.yaml
--- a/py3-grpcio-reflection.yaml
+++ b/py3-grpcio-reflection.yaml
@@ -40,3 +40,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 30542
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="grpcio_reflection"
+        IMPORT_STATEMENT="from grpcio-reflection import reflection"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
