py3-sqlglot: add basic test

diff --git a/py3-sqlglot.yaml b/py3-sqlglot.yaml
--- a/py3-sqlglot.yaml
+++ b/py3-sqlglot.yaml
@@ -2,7 +2,7 @@
 package:
   name: py3-sqlglot
   version: 24.0.0
-  epoch: 0
+  epoch: 1
   description: An easily customizable SQL parser and transpiler
   copyright:
     - license: MIT
@@ -32,9 +32,24 @@ pipeline:
     runs: python setup.py build
 
   - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+    runs: python setup.py install --prefix=/usr --root="${{targets.contextdir}}"
 
   - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="sqlglot"
+        IMPORT_STATEMENT="import sqlglot"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
