test PR
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-aiosignal.yaml b/py3-aiosignal.yaml
--- a/py3-aiosignal.yaml
+++ b/py3-aiosignal.yaml
@@ -5,37 +5,56 @@ package:
   epoch: 3
   description: 'aiosignal: a list of registered asynchronous callbacks'
   copyright:
-    - license: Apache-2.0
+  - license: Apache-2.0
   dependencies:
     runtime:
-      - py3-frozenlist
-      - python3
+    - py3-frozenlist
+    - python3
 
 environment:
   contents:
     packages:
-      - build-base
-      - busybox
-      - ca-certificates-bundle
-      - py3-setuptools
-      - python3
-      - wolfi-base
+    - build-base
+    - busybox
+    - ca-certificates-bundle
+    - py3-setuptools
+    - python3
+    - wolfi-base
 
 pipeline:
-  - uses: fetch
-    with:
-      expected-sha256: 54cd96e15e1649b75d6c87526a6ff0b6c1b0dd3459f43d9ca11d48c339b68cfc
-      uri: https://files.pythonhosted.org/packages/source/a/aiosignal/aiosignal-${{package.version}}.tar.gz
+- uses: fetch
+  with:
+    expected-sha256: 54cd96e15e1649b75d6c87526a6ff0b6c1b0dd3459f43d9ca11d48c339b68cfc
+    uri: 
+      https://files.pythonhosted.org/packages/source/a/aiosignal/aiosignal-${{package.version}}.tar.gz
 
-  - name: Python Build
-    runs: python setup.py build
+- name: Python Build
+  runs: python setup.py build
 
-  - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+- name: Python Install
+  runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-  - uses: strip
+- uses: strip
 
 update:
   enabled: true
   release-monitor:
     identifier: 41889
+test:
+  environment:
+    contents:
+      packages:
+      - busybox
+  pipeline:
+  - runs: |
+      LIBRARY="aiosignal"
+      python3 -c "import $LIBRARY" 2>/dev/null
+      status=$?
+
+      if [ $status -eq 0 ]; then
+          echo "Library '$LIBRARY' is installed and can be imported successfully."
+          exit 0  # Exit with a status code of 0, indicating success
+      else
+          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+          exit 1  # Exit with a non-zero status code, indicating failure
+      fi
