fix(py3-cassandra-medusa): remove if case on test
Signed-off-by: Furkan Türkal <furkan.turkal@chainguard.dev>

diff --git a/py3-cassandra-medusa.yaml b/py3-cassandra-medusa.yaml
--- a/py3-cassandra-medusa.yaml
+++ b/py3-cassandra-medusa.yaml
@@ -108,8 +108,5 @@ test:
         fail() { echo "$@" 1>&2; exit 1; }
         out=$(/usr/share/medusa/.venv/bin/python3 -m medusa.service.grpc.server 2>&1)
         status=$?
-        if [ $status -ne 0 ]; then
-          fail "medusa.service.grpc.server exited $status: $out"
-        fi
-        echo "$out" | grep -q '/etc/medusa/medusa.ini' || fail "medusa.service.grpc.server output did not contain expected 'medusa.ini' message!"
-        echo "medusa.service.grpc.server started successfully."
+        echo "$out" | grep -q '/etc/medusa/medusa.ini' || fail "medusa.service.grpc.server output did not contain expected 'medusa.ini' message. Exit status $status: $out"
+        echo "medusa.service.grpc.server exited with expected error message"
