slight changes to automation/syntax creation
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-aiofiles.yaml b/py3-aiofiles.yaml
--- a/py3-aiofiles.yaml
+++ b/py3-aiofiles.yaml
@@ -44,8 +44,9 @@ test:
         LIBRARY="aiofiles"
         IMPORT_STATEMENT="import aiofiles"
 
-         if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
             exit 1
         else
             echo "Library '$LIBRARY' is installed and can be imported successfully."
diff --git a/py3-aiohttp.yaml b/py3-aiohttp.yaml
--- a/py3-aiohttp.yaml
+++ b/py3-aiohttp.yaml
@@ -83,8 +83,9 @@ test:
         LIBRARY="aiohttp"
         IMPORT_STATEMENT="import aiohttp"
 
-         if ! python -c "$IMPORT_STATEMENT"; then
-            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
             exit 1
         else
             echo "Library '$LIBRARY' is installed and can be imported successfully."
