WIP: 10 Python package tests.
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-imagesize.yaml b/py3-imagesize.yaml
--- a/py3-imagesize.yaml
+++ b/py3-imagesize.yaml
@@ -40,3 +40,22 @@ update:
   github:
     identifier: shibukawa/imagesize_py
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="imagesize"
+        IMPORT_STATEMENT="import imagesize"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-isodate.yaml b/py3-isodate.yaml
--- a/py3-isodate.yaml
+++ b/py3-isodate.yaml
@@ -40,3 +40,22 @@ update:
   github:
     use-tag: true
     identifier: gweis/isodate
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="isodate"
+        IMPORT_STATEMENT="import isodate"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-itables.yaml b/py3-itables.yaml
--- a/py3-itables.yaml
+++ b/py3-itables.yaml
@@ -41,3 +41,22 @@ update:
   github:
     identifier: mwouts/itables
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="itables"
+        IMPORT_STATEMENT="import itables"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-jaraco.classes.yaml b/py3-jaraco.classes.yaml
--- a/py3-jaraco.classes.yaml
+++ b/py3-jaraco.classes.yaml
@@ -5,7 +5,7 @@ package:
   epoch: 0
   description: Utility functions for Python class constructs
   copyright:
-    - license: "MIT"
+    - license: MIT
   dependencies:
     runtime:
       - py3-more-itertools
@@ -41,3 +41,22 @@ update:
     identifier: jaraco/jaraco.classes
     use-tag: true
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="jaraco.classes"
+        IMPORT_STATEMENT="from jaraco.classes import properties"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-javaproperties.yaml b/py3-javaproperties.yaml
--- a/py3-javaproperties.yaml
+++ b/py3-javaproperties.yaml
@@ -36,3 +36,22 @@ update:
   github:
     identifier: jwodder/javaproperties
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="javaproperties"
+        IMPORT_STATEMENT="import javaproperties"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
