Adding 10 Python packages.
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-httplib2.yaml b/py3-httplib2.yaml
--- a/py3-httplib2.yaml
+++ b/py3-httplib2.yaml
@@ -40,3 +40,22 @@ update:
     identifier: httplib2/httplib2
     strip-prefix: v
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="httplib2"
+        IMPORT_STATEMENT="import httplib2"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-humanfriendly.yaml b/py3-humanfriendly.yaml
--- a/py3-humanfriendly.yaml
+++ b/py3-humanfriendly.yaml
@@ -1,7 +1,7 @@
 # Generated from https://pypi.org/project/humanfriendly/
 package:
   name: py3-humanfriendly
-  version: "10.0"
+  version: '10.0'
   epoch: 2
   description: Human friendly output for text interfaces using Python
   copyright:
@@ -40,3 +40,22 @@ update:
   github:
     identifier: xolox/python-humanfriendly
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="humanfriendly"
+        IMPORT_STATEMENT="import humanfriendly"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-idna.yaml b/py3-idna.yaml
--- a/py3-idna.yaml
+++ b/py3-idna.yaml
@@ -1,7 +1,7 @@
 # Generated from https://pypi.org/project/idna/
 package:
   name: py3-idna
-  version: "3.6"
+  version: '3.6'
   epoch: 1
   description: Internationalized Domain Names in Applications (IDNA)
   copyright:
@@ -35,3 +35,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 5487
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="idna"
+        IMPORT_STATEMENT="import idna"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-iniconfig.yaml b/py3-iniconfig.yaml
--- a/py3-iniconfig.yaml
+++ b/py3-iniconfig.yaml
@@ -37,3 +37,22 @@ update:
     identifier: pytest-dev/iniconfig
     tag-filter: v
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="iniconfig"
+        IMPORT_STATEMENT="from iniconfig import SectionWrapper"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
