a LOT of changes
Signed-off-by: Kaiming Zhang <kaiming.zhang@chainguard.dev>

diff --git a/py3-asn1-modules.yaml b/py3-asn1-modules.yaml
--- a/py3-asn1-modules.yaml
+++ b/py3-asn1-modules.yaml
@@ -7,8 +7,8 @@ package:
     - license: BSD-3-Clause
   dependencies:
     runtime:
-      - py3-asn1
-      - python3
+      - py3-supported-asn1
+      - py3-supported-python
 
 environment:
   contents:
@@ -16,9 +16,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: asn1-modules
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -27,13 +37,39 @@ pipeline:
       tag: v${{package.version}}
       expected-commit: 98b1e268a30be4b2d6efa5c69eae772edc442c7e
 
-  - name: Python Build
-    runs: python setup.py build
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-asn1
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        runs: python${{range.key}} setup.py build
 
-  - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+      - name: Python Install
+        runs: python${{range.key}} setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="asn1-modules"
+        IMPORT_STATEMENT="import pyasn1_modules"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
diff --git a/py3-google-auth-oauthlib.yaml b/py3-google-auth-oauthlib.yaml
--- a/py3-google-auth-oauthlib.yaml
+++ b/py3-google-auth-oauthlib.yaml
@@ -2,7 +2,7 @@
 package:
   name: py3-google-auth-oauthlib
   version: 1.2.1
-  epoch: 0
+  epoch: 1
   description: Google Authentication Library
   copyright:
     - license: Apache-2.0
@@ -18,9 +18,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python-3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: google-auth-oauthlib
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -29,10 +39,37 @@ pipeline:
       repository: https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib
       tag: v${{package.version}}
 
-  - name: Python Build
-    uses: python/build-wheel
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-google-auth
+        - py${{range.key}}-requests-oauthlib
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        uses: python${{range.key}}/build-wheel
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="google_auth_oauthlib"
+        IMPORT_STATEMENT="import google_auth_oauthlib"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
diff --git a/py3-google-auth.yaml b/py3-google-auth.yaml
--- a/py3-google-auth.yaml
+++ b/py3-google-auth.yaml
@@ -20,9 +20,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: google-auth
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -31,13 +41,43 @@ pipeline:
       tag: v${{package.version}}
       expected-commit: c6d99030b8d972105913006bd052cf762b94a976
 
-  - name: Python Build
-    runs: python setup.py build
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-asn1-modules
+        - py${{range.key}}-cachetools
+        - py${{range.key}}-rsa
+        - py${{range.key}}-six
+        - py${{range.key}}-urllib3
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        runs: python${{range.key}} setup.py build
 
-  - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+      - name: Python Install
+        runs: python${{range.key}} setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="google.auth"
+        IMPORT_STATEMENT="import google.auth"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
diff --git a/py3-oauthlib.yaml b/py3-oauthlib.yaml
--- a/py3-oauthlib.yaml
+++ b/py3-oauthlib.yaml
@@ -1,7 +1,7 @@
 package:
   name: py3-oauthlib
   version: 3.2.2
-  epoch: 3
+  epoch: 4
   description: A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
   copyright:
     - license: BSD-3-Clause
@@ -15,9 +15,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: oauthlib
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -26,13 +36,39 @@ pipeline:
       tag: v${{package.version}}
       expected-commit: e6c33e41a8ce6dadff387cdc4613a55b63d1827e
 
-  - name: Python Build
-    runs: python setup.py build
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-six
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        runs: python${{range.key}} setup.py build
 
-  - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+      - name: Python Install
+        runs: python${{range.key}} setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="oauthlib"
+        IMPORT_STATEMENT="import oauthlib"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
diff --git a/py3-pyasn1.yaml b/py3-pyasn1.yaml
--- a/py3-pyasn1.yaml
+++ b/py3-pyasn1.yaml
@@ -2,7 +2,7 @@
 package:
   name: py3-pyasn1
   version: 0.6.0
-  epoch: 0
+  epoch: 1
   description: Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)
   copyright:
     - license: BSD-2-Clause
@@ -16,9 +16,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python-3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: pyasn1
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -27,14 +37,41 @@ pipeline:
       repository: https://github.com/pyasn1/pyasn1
       tag: v${{package.version}}
 
-  - name: Python Build
-    uses: python/build-wheel
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-six
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        uses: python/build-wheel
+        with:
+          python: python${{range.key}}
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="pyasn1"
+        IMPORT_STATEMENT="import pyasn1"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
-  manual: false
   github:
     identifier: pyasn1/pyasn1
     strip-prefix: v
diff --git a/py3-requests-oauthlib.yaml b/py3-requests-oauthlib.yaml
--- a/py3-requests-oauthlib.yaml
+++ b/py3-requests-oauthlib.yaml
@@ -7,9 +7,9 @@ package:
     - license: ISC
   dependencies:
     runtime:
-      - py3-oauthlib
-      - py3-requests
-      - python3
+      - py3-supported-oauthlib
+      - py3-supported-requests
+      - py3-supported-python
 
 environment:
   contents:
@@ -17,11 +17,21 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-oauthlib
-      - py3-requests
-      - py3-setuptools
-      - python3
+      - py3-supported-oauthlib
+      - py3-supported-requests
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: requests-oauthlib
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: git-checkout
@@ -30,13 +40,40 @@ pipeline:
       tag: v${{package.version}}
       expected-commit: 7af9125a4fb3a21fbff4b829449a090469cf32b4
 
-  - name: Python Build
-    runs: python setup.py build
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-oauthlib
+        - py${{range.key}}-requests
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - name: Python Build
+        runs: python${{range.key}} setup.py build
 
-  - name: Python Install
-    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+      - name: Python Install
+        runs: python${{range.key}} setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="requests-oauthlib"
+        IMPORT_STATEMENT="import requests_oauthlib"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
diff --git a/py3-rsa.yaml b/py3-rsa.yaml
--- a/py3-rsa.yaml
+++ b/py3-rsa.yaml
@@ -1,14 +1,14 @@
 package:
   name: py3-rsa
   version: 4.9
-  epoch: 4
+  epoch: 5
   description: "Pure-Python3 RSA implementation"
   copyright:
     - license: Apache-2.0
   dependencies:
     runtime:
-      - py3-asn1
-      - python3
+      - py3-supported-asn1
+      - py3-supported-python
 
 environment:
   contents:
@@ -16,9 +16,19 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
-      - py3-setuptools
-      - python3
+      - py3-supported-setuptools
+      - py3-supported-python
       - wolfi-base
+
+vars:
+  pypi-package: rsa
+
+data:
+  - name: py-versions
+    items:
+      3.10: "310"
+      3.11: "311"
+      3.12: "312"
 
 pipeline:
   - uses: fetch
@@ -26,13 +36,39 @@ pipeline:
       uri: https://files.pythonhosted.org/packages/source/r/rsa/rsa-${{package.version}}.tar.gz
       expected-sha256: e38464a49c6c85d7f1351b0126661487a7e0a14a50f1675ec50eb34d4f20ef21
 
-  - runs: |
-      python3 setup.py build
+subpackages:
+  - range: py-versions
+    name: py${{range.key}}-${{vars.pypi-package}}
+    description: ${{vars.pypi-package}} installed for python${{range.key}}
+    dependencies:
+      runtime:
+        - py${{range.key}}-asn1
+      provides:
+        - py3-${{vars.pypi-package}}
+      provider-priority: ${{range.value}}
+    pipeline:
+      - runs: |
+          python${{range.key}} setup.py build
 
-  - runs: |
-      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
+      - runs: |
+          python${{range.key}} setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
 
-  - uses: strip
+      - uses: strip
+
+test:
+  pipeline:
+    - runs: |
+        LIBRARY="rsa"
+        IMPORT_STATEMENT="import rsa"
+
+        if ! python${{range.key}} -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python${{range.key}} -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
 
 update:
   enabled: true
