10 new Python package tests.
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-entrypoints.yaml b/py3-entrypoints.yaml
--- a/py3-entrypoints.yaml
+++ b/py3-entrypoints.yaml
@@ -1,11 +1,11 @@
 # Generated from https://pypi.org/project/entrypoints/
 package:
   name: py3-entrypoints
-  version: "0.4"
+  version: '0.4'
   epoch: 1
   description: Discover and load entry points from installed packages.
   copyright:
-    - license: "MIT License"
+    - license: MIT License
   dependencies:
     runtime:
       - python-3
@@ -37,3 +37,22 @@ update:
   manual: false
   github:
     identifier: takluyver/entrypoints
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="entrypoints"
+        IMPORT_STATEMENT="import entrypoints"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-face.yaml b/py3-face.yaml
--- a/py3-face.yaml
+++ b/py3-face.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-face
   version: 22.0.0
   epoch: 1
-  description: "A command-line application framework (and CLI parser). Friendly for users, full-featured for developers."
+  description: A command-line application framework (and CLI parser). Friendly for users, full-featured for developers.
   copyright:
     - license: BSD-3-Clause
   dependencies:
@@ -43,3 +43,22 @@ update:
   github:
     identifier: mahmoud/face
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="face"
+        IMPORT_STATEMENT="import face"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-fastavro.yaml b/py3-fastavro.yaml
--- a/py3-fastavro.yaml
+++ b/py3-fastavro.yaml
@@ -38,3 +38,22 @@ update:
   manual: false
   github:
     identifier: fastavro/fastavro
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="fastavro"
+        IMPORT_STATEMENT="import fastavro"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-fasteners.yaml b/py3-fasteners.yaml
--- a/py3-fasteners.yaml
+++ b/py3-fasteners.yaml
@@ -1,7 +1,7 @@
 # Generated from https://pypi.org/project/fasteners/
 package:
   name: py3-fasteners
-  version: "0.19"
+  version: '0.19'
   epoch: 1
   description: A python package that provides useful locks
   copyright:
@@ -37,3 +37,22 @@ update:
   manual: false
   github:
     identifier: harlowja/fasteners
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="fasteners"
+        IMPORT_STATEMENT="import fasteners"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-ffwd.yaml b/py3-ffwd.yaml
--- a/py3-ffwd.yaml
+++ b/py3-ffwd.yaml
@@ -32,3 +32,22 @@ pipeline:
 #archived but needed by cassandra-medussa
 update:
   enabled: false
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="ffwd"
+        IMPORT_STATEMENT="import ffwd"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-filelock.yaml b/py3-filelock.yaml
--- a/py3-filelock.yaml
+++ b/py3-filelock.yaml
@@ -45,3 +45,22 @@ update:
   github:
     identifier: benediktschmitt/py-filelock
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="filelock"
+        IMPORT_STATEMENT="from filelock import FileLock"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-forestci.yaml b/py3-forestci.yaml
--- a/py3-forestci.yaml
+++ b/py3-forestci.yaml
@@ -1,6 +1,6 @@
 package:
   name: py3-forestci
-  version: "0.6"
+  version: '0.6'
   epoch: 3
   description: 'forestci: confidence intervals for scikit-learn forest algorithms'
   copyright:
@@ -40,3 +40,22 @@ update:
   enabled: true
   github:
     identifier: scikit-learn-contrib/forest-confidence-interval
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="forestci"
+        IMPORT_STATEMENT="import forestci"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-frozenlist.yaml b/py3-frozenlist.yaml
--- a/py3-frozenlist.yaml
+++ b/py3-frozenlist.yaml
@@ -35,3 +35,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 41138
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="frozenlist"
+        IMPORT_STATEMENT="from frozenlist import FrozenList"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
