Adding 10 Python package tests - #3
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-cppy.yaml b/py3-cppy.yaml
--- a/py3-cppy.yaml
+++ b/py3-cppy.yaml
@@ -50,3 +50,22 @@ update:
   enabled: true
   github:
     identifier: nucleic/cppy
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="cppy"
+        IMPORT_STATEMENT="import cppy"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
