py3-referencing/0.33.0 package update

diff --git a/py3-referencing.yaml b/py3-referencing.yaml
--- a/py3-referencing.yaml
+++ b/py3-referencing.yaml
@@ -1,52 +1,47 @@
 package:
-  name: py3-referencing
-  version: 0.32.1
-  epoch: 0
-  description: "Cross-specification JSON referencing (JSON Schema, OpenAPI, and the one you just made up!)."
-  copyright:
-    - license: MIT
-  dependencies:
-    runtime:
-      - py3-attrs
-      - py3-rpds-py
-      - python3
-
+    name: py3-referencing
+    version: 0.33.0
+    epoch: 0
+    description: "Cross-specification JSON referencing (JSON Schema, OpenAPI, and the one you just made up!)."
+    copyright:
+        - license: MIT
+    dependencies:
+        runtime:
+            - py3-attrs
+            - py3-rpds-py
+            - python3
 environment:
-  contents:
-    packages:
-      - busybox
-      - ca-certificates-bundle
-      - py3-gpep517
-      - py3-pip
-      - py3-setuptools
-      - py3-wheel
-      - python3
-      - wolfi-base
-
+    contents:
+        packages:
+            - busybox
+            - ca-certificates-bundle
+            - py3-gpep517
+            - py3-pip
+            - py3-setuptools
+            - py3-wheel
+            - python3
+            - wolfi-base
 pipeline:
-  - uses: git-checkout
-    with:
-      repository: https://github.com/python-jsonschema/referencing
-      tag: v${{package.version}}
-      expected-commit: adb7c6717209a790f9661c14d1afc5ca09689dc8
-
-  - runs: |
-      # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
-      export SOURCE_DATE_EPOCH=315532800
-      python3 -m pip install -U hatchling hatch-vcs
-      git submodule update --init
-      python3 -m gpep517 build-wheel \
-        --wheel-dir dist \
-        --output-fd 3 3>&1 >&2
-      python3 -m installer \
-        -d "${{targets.destdir}}" \
-        dist/referencing-${{package.version}}-*.whl
-
-  - uses: strip
-
+    - uses: git-checkout
+      with:
+        repository: https://github.com/python-jsonschema/referencing
+        tag: v${{package.version}}
+        expected-commit: 16305060454f89ec04ff6f346704553cb2763f87
+    - runs: |
+        # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
+        export SOURCE_DATE_EPOCH=315532800
+        python3 -m pip install -U hatchling hatch-vcs
+        git submodule update --init
+        python3 -m gpep517 build-wheel \
+          --wheel-dir dist \
+          --output-fd 3 3>&1 >&2
+        python3 -m installer \
+          -d "${{targets.destdir}}" \
+          dist/referencing-${{package.version}}-*.whl
+    - uses: strip
 update:
-  enabled: true
-  github:
-    identifier: python-jsonschema/referencing
-    tag-filter: v
-    strip-prefix: v
+    enabled: true
+    github:
+        identifier: python-jsonschema/referencing
+        tag-filter: v
+        strip-prefix: v
