Python package tests
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-argon2-cffi-bindings.yaml b/py3-argon2-cffi-bindings.yaml
--- a/py3-argon2-cffi-bindings.yaml
+++ b/py3-argon2-cffi-bindings.yaml
@@ -43,3 +43,22 @@ update:
   manual: false
   github:
     identifier: hynek/argon2-cffi-bindings
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="argon2_cffi_bindings"
+        IMPORT_STATEMENT="import argon2-cffi-bindings"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-asn1.yaml b/py3-asn1.yaml
--- a/py3-asn1.yaml
+++ b/py3-asn1.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-asn1
   version: 0.4.8
   epoch: 6
-  description: "Python3 ASN1 library"
+  description: Python3 ASN1 library
   copyright:
     - license: BSD-2-Clause
   dependencies:
@@ -38,3 +38,22 @@ update:
   github:
     identifier: etingof/pyasn1
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="asn1"
+        IMPORT_STATEMENT="import asn1"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-awscrt.yaml b/py3-awscrt.yaml
--- a/py3-awscrt.yaml
+++ b/py3-awscrt.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-awscrt
   version: 0.20.4
   epoch: 0
-  description: "Python bindings for the AWS Common Runtime"
+  description: Python bindings for the AWS Common Runtime
   copyright:
     - license: Apache-2.0
   dependencies:
@@ -52,3 +52,22 @@ update:
     identifier: awslabs/aws-crt-python
     use-tag: true
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="awscrt"
+        IMPORT_STATEMENT="from awscrt import io,"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-azure-storage-blob.yaml b/py3-azure-storage-blob.yaml
--- a/py3-azure-storage-blob.yaml
+++ b/py3-azure-storage-blob.yaml
@@ -46,3 +46,22 @@ update:
     identifier: Azure/azure-sdk-for-python
     strip-prefix: azure-storage-blob_
     tag-filter: azure-storage-blob_
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="azure_storage_blob"
+        IMPORT_STATEMENT="HTTP error occurred: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/dagster-io/dagster/b6cd6e371de35bb20d58fd7a1756b58e13cbc2a8/python_modules/libraries/dagster-azure/dagster_azure/utils.py"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-botocore.yaml b/py3-botocore.yaml
--- a/py3-botocore.yaml
+++ b/py3-botocore.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-botocore
   version: 1.34.48
   epoch: 0
-  description: "The low-level, core functionality of Boto3"
+  description: The low-level, core functionality of Boto3
   copyright:
     - license: Apache-2.0
   dependencies:
@@ -41,3 +41,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 29738
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="botocore"
+        IMPORT_STATEMENT="import botocore"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
