Adding 10 Python packages.
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-httpx.yaml b/py3-httpx.yaml
--- a/py3-httpx.yaml
+++ b/py3-httpx.yaml
@@ -5,7 +5,7 @@ package:
   epoch: 0
   description: The next generation HTTP client.
   copyright:
-    - license: "BSD-3-Clause"
+    - license: BSD-3-Clause
   dependencies:
     runtime:
       - py3-certifi
@@ -44,7 +44,26 @@ pipeline:
 update:
   enabled: true
   ignore-regex-patterns:
-    - '.*\.dev.*'
+    - .*\.dev.*
   github:
     identifier: encode/httpx
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="httpx"
+        IMPORT_STATEMENT="import httpx"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-ipaddress.yaml b/py3-ipaddress.yaml
--- a/py3-ipaddress.yaml
+++ b/py3-ipaddress.yaml
@@ -40,3 +40,22 @@ update:
     identifier: phihag/ipaddress
     strip-prefix: v
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="ipaddress"
+        IMPORT_STATEMENT="import ipaddress"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
