additional tests
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-gunicorn.yaml b/py3-gunicorn.yaml
--- a/py3-gunicorn.yaml
+++ b/py3-gunicorn.yaml
@@ -42,3 +42,22 @@ update:
   github:
     identifier: benoitc/gunicorn
     use-tag: false
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="gunicorn"
+        IMPORT_STATEMENT="import gunicorn"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-h5py.yaml b/py3-h5py.yaml
--- a/py3-h5py.yaml
+++ b/py3-h5py.yaml
@@ -1,7 +1,7 @@
 package:
   name: py3-h5py
-  description: 'Read and write HDF5 files from Python'
-  url: 'https://www.h5py.org'
+  description: Read and write HDF5 files from Python
+  url: https://www.h5py.org
   version: 3.10.0
   epoch: 1
   copyright:
@@ -54,3 +54,22 @@ update:
   github:
     identifier: h5py/h5py
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="h5py"
+        IMPORT_STATEMENT="import h5py"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-hatch.yaml b/py3-hatch.yaml
--- a/py3-hatch.yaml
+++ b/py3-hatch.yaml
@@ -5,7 +5,7 @@ package:
   epoch: 0
   description: Modern, extensible Python project management
   copyright:
-    - license: "MIT"
+    - license: MIT
   dependencies:
     runtime:
       - py3-click
@@ -55,3 +55,22 @@ update:
     identifier: pypa/hatch
     strip-prefix: hatch-v
     tag-filter: hatch-v
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="hatch"
+        IMPORT_STATEMENT="import hatch"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-hatchling.yaml b/py3-hatchling.yaml
--- a/py3-hatchling.yaml
+++ b/py3-hatchling.yaml
@@ -2,7 +2,7 @@ package:
   name: py3-hatchling
   version: 1.21.1
   epoch: 0
-  description: "Modern, extensible Python build backend"
+  description: Modern, extensible Python build backend
   copyright:
     - license: BSD-3-Clause
   dependencies:
@@ -37,3 +37,22 @@ update:
   enabled: true
   release-monitor:
     identifier: 185085
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="hatchling"
+        IMPORT_STATEMENT="import hatchling"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-html5lib.yaml b/py3-html5lib.yaml
--- a/py3-html5lib.yaml
+++ b/py3-html5lib.yaml
@@ -1,6 +1,6 @@
 package:
   name: py3-html5lib
-  version: "1.1"
+  version: '1.1'
   epoch: 2
   description: HTML parser based on the WHATWG HTML specification
   copyright:
@@ -41,3 +41,22 @@ update:
   github:
     identifier: html5lib/html5lib-python
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="html5lib"
+        IMPORT_STATEMENT="import html5lib"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
diff --git a/py3-httpcore.yaml b/py3-httpcore.yaml
--- a/py3-httpcore.yaml
+++ b/py3-httpcore.yaml
@@ -49,3 +49,22 @@ update:
   github:
     identifier: encode/httpcore
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        LIBRARY="httpcore"
+        IMPORT_STATEMENT="import httpcore"
+
+        if ! python -c "$IMPORT_STATEMENT"; then
+            echo "Failed to import library '$LIBRARY'."
+            python -c "$IMPORT_STATEMENT" 2>&1
+            exit 1
+        else
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        fi
