fixing yam
Signed-off-by: Anthony Feddersen <afeddersen@chainguard.dev>

diff --git a/py3-absl-py.yaml b/py3-absl-py.yaml
--- a/py3-absl-py.yaml
+++ b/py3-absl-py.yaml
@@ -4,50 +4,55 @@ package:
   epoch: 1
   description: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
   copyright:
-  - license: Apache-2.0
+    - license: Apache-2.0
   dependencies:
     runtime:
-    - python3
+      - python3
+
 environment:
   contents:
     packages:
-    - build-base
-    - busybox
-    - ca-certificates-bundle
-    - py3-setuptools
-    - python3
-    - wolfi-base
+      - build-base
+      - busybox
+      - ca-certificates-bundle
+      - py3-setuptools
+      - python3
+      - wolfi-base
+
 pipeline:
-- uses: git-checkout
-  with:
-    repository: https://github.com/abseil/abseil-py/
-    tag: v${{package.version}}
-    expected-commit: 8abdd60755e5b6ebfa2b383cf6eaa0d9315335bd
-- name: Python Build
-  runs: python setup.py build
-- name: Python Install
-  runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
-- uses: strip
+  - uses: git-checkout
+    with:
+      repository: https://github.com/abseil/abseil-py/
+      tag: v${{package.version}}
+      expected-commit: 8abdd60755e5b6ebfa2b383cf6eaa0d9315335bd
+
+  - name: Python Build
+    runs: python setup.py build
+
+  - name: Python Install
+    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+
+  - uses: strip
+
 update:
   enabled: true
   github:
     identifier: abseil/abseil-py
     strip-prefix: v
+
 test:
   environment:
     contents:
       packages:
-      - busybox
+        - busybox
   pipeline:
-  - runs: |
-      LIBRARY="absl-py"
-      python3 -c "import $LIBRARY" 2>/dev/null
-      status=$?
+    - runs: |
+        LIBRARY="absl-py"
+        python -c "import $LIBRARY" 2>/dev/null
 
-      if [ $status -eq 0 ]; then
-          echo "Library '$LIBRARY' is installed and can be imported successfully."
-          exit 0  # Exit with a status code of 0, indicating success
-      else
-          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
-          exit 1  # Exit with a non-zero status code, indicating failure
-      fi
+        if [ $? -eq 0 ]; then
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        else
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
diff --git a/py3-agate.yaml b/py3-agate.yaml
--- a/py3-agate.yaml
+++ b/py3-agate.yaml
@@ -5,60 +5,59 @@ package:
   epoch: 0
   description: A data analysis library that is optimized for humans instead of machines.
   copyright:
-  - license: MIT
+    - license: MIT
   dependencies:
     runtime:
-    - py3-babel
-    - py3-isodate
-    - py3-leather
-    - py3-parsedatetime
-    - py3-python-slugify
-    - py3-pytimeparse
-    - python3
+      - py3-babel
+      - py3-isodate
+      - py3-leather
+      - py3-parsedatetime
+      - py3-python-slugify
+      - py3-pytimeparse
+      - python3
 
 environment:
   contents:
     packages:
-    - busybox
-    - ca-certificates-bundle
-    - py3-build
-    - py3-installer
-    - py3-setuptools
-    - python3
-    - wolfi-base
+      - busybox
+      - ca-certificates-bundle
+      - py3-build
+      - py3-installer
+      - py3-setuptools
+      - python3
+      - wolfi-base
 
 pipeline:
-- uses: git-checkout
-  with:
-    expected-commit: b18899053a33e890f9ee9f9fa90e99dbdf03fb21
-    repository: https://github.com/wireservice/agate
-    tag: ${{package.version}}
+  - uses: git-checkout
+    with:
+      expected-commit: b18899053a33e890f9ee9f9fa90e99dbdf03fb21
+      repository: https://github.com/wireservice/agate
+      tag: ${{package.version}}
 
-- name: Python Build
-  uses: python/build-wheel
+  - name: Python Build
+    uses: python/build-wheel
 
-- uses: strip
+  - uses: strip
 
 update:
   enabled: true
   github:
     use-tag: true
     identifier: wireservice/agate
+
 test:
   environment:
     contents:
       packages:
-      - busybox
+        - busybox
   pipeline:
-  - runs: |
-      LIBRARY="agate"
-      python3 -c "import $LIBRARY" 2>/dev/null
-      status=$?
+    - runs: |
+        LIBRARY="agate"
+        python -c "import $LIBRARY" 2>/dev/null
 
-      if [ $status -eq 0 ]; then
-          echo "Library '$LIBRARY' is installed and can be imported successfully."
-          exit 0  # Exit with a status code of 0, indicating success
-      else
-          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
-          exit 1  # Exit with a non-zero status code, indicating failure
-      fi
+        if [ $? -eq 0 ]; then
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        else
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
diff --git a/py3-aiofiles.yaml b/py3-aiofiles.yaml
--- a/py3-aiofiles.yaml
+++ b/py3-aiofiles.yaml
@@ -5,50 +5,48 @@ package:
   epoch: 0
   description: File support for asyncio.
   copyright:
-  - license: Apache-2.0
+    - license: Apache-2.0
   dependencies:
     runtime:
-    - python3
+      - python3
 
 environment:
   contents:
     packages:
-    - build-base
-    - busybox
-    - ca-certificates-bundle
-    - wolfi-base
+      - build-base
+      - busybox
+      - ca-certificates-bundle
+      - wolfi-base
 
 pipeline:
-- uses: fetch
-  with:
-    expected-sha256: 84ec2218d8419404abcb9f0c02df3f34c6e0a68ed41072acfb1cef5cbc29051a
-    uri: 
-      https://files.pythonhosted.org/packages/source/a/aiofiles/aiofiles-${{package.version}}.tar.gz
+  - uses: fetch
+    with:
+      expected-sha256: 84ec2218d8419404abcb9f0c02df3f34c6e0a68ed41072acfb1cef5cbc29051a
+      uri: https://files.pythonhosted.org/packages/source/a/aiofiles/aiofiles-${{package.version}}.tar.gz
 
-- name: Python Build
-  uses: python/build-wheel
+  - name: Python Build
+    uses: python/build-wheel
 
-- uses: strip
+  - uses: strip
 
 update:
   enabled: true
   release-monitor:
     identifier: 12743
+
 test:
   environment:
     contents:
       packages:
-      - busybox
+        - busybox
   pipeline:
-  - runs: |
-      LIBRARY="aiofiles"
-      python3 -c "import $LIBRARY" 2>/dev/null
-      status=$?
+    - runs: |
+        LIBRARY="aiofiles"
+        python -c "import $LIBRARY" 2>/dev/null
 
-      if [ $status -eq 0 ]; then
-          echo "Library '$LIBRARY' is installed and can be imported successfully."
-          exit 0  # Exit with a status code of 0, indicating success
-      else
-          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
-          exit 1  # Exit with a non-zero status code, indicating failure
-      fi
+        if [ $? -eq 0 ]; then
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        else
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
diff --git a/py3-aiohttp.yaml b/py3-aiohttp.yaml
--- a/py3-aiohttp.yaml
+++ b/py3-aiohttp.yaml
@@ -5,89 +5,87 @@ package:
   epoch: 0
   description: Async http client/server framework (asyncio)
   copyright:
-  - license: Apache-2.0
+    - license: Apache-2.0
   dependencies:
     runtime:
-    - py3-attrs
-    - py3-charset-normalizer
-    - py3-multidict
-    - py3-async-timeout
-    - py3-yarl
-    - py3-frozenlist
-    - py3-aiosignal
-    - py3-idna-ssl
-    - py3-asynctest
-    - py3-typing-extensions
-    - python3
+      - py3-attrs
+      - py3-charset-normalizer
+      - py3-multidict
+      - py3-async-timeout
+      - py3-yarl
+      - py3-frozenlist
+      - py3-aiosignal
+      - py3-idna-ssl
+      - py3-asynctest
+      - py3-typing-extensions
+      - python3
 
 environment:
   contents:
     packages:
-    - build-base
-    - busybox
-    - ca-certificates-bundle
-    - cython~0
-    - llhttp-dev
-    - py3-aiosignal
-    - py3-async-timeout
-    - py3-asynctest
-    - py3-attrs
-    - py3-charset-normalizer
-    - py3-frozenlist
-    - py3-idna-ssl
-    - py3-multidict
-    - py3-setuptools
-    - py3-typing-extensions
-    - py3-yarl
-    - python3-dev
-    - wolfi-base
+      - build-base
+      - busybox
+      - ca-certificates-bundle
+      - cython~0
+      - llhttp-dev
+      - py3-aiosignal
+      - py3-async-timeout
+      - py3-asynctest
+      - py3-attrs
+      - py3-charset-normalizer
+      - py3-frozenlist
+      - py3-idna-ssl
+      - py3-multidict
+      - py3-setuptools
+      - py3-typing-extensions
+      - py3-yarl
+      - python3-dev
+      - wolfi-base
 
 pipeline:
-- uses: fetch
-  with:
-    expected-sha256: dd3067e326d6274f4d293920104f1df205b7ad20fcfd23ef3d407965b8fd664b
-    uri: 
-      https://github.com/aio-libs/aiohttp/archive/v${{package.version}}/aiohttp-${{package.version}}.tar.gz
+  - uses: fetch
+    with:
+      expected-sha256: dd3067e326d6274f4d293920104f1df205b7ad20fcfd23ef3d407965b8fd664b
+      uri: https://github.com/aio-libs/aiohttp/archive/v${{package.version}}/aiohttp-${{package.version}}.tar.gz
 
-- uses: patch
-  with:
-    patches: unbundle-llhttp.patch
+  - uses: patch
+    with:
+      patches: unbundle-llhttp.patch
 
-- runs: |
-    mkdir -p .git
-    python tools/gen.py
-    python -m cython -3 aiohttp/*.pyx -I aiohttp
-    rm -rf .git
+  - runs: |
+      mkdir -p .git
+      python tools/gen.py
+      python -m cython -3 aiohttp/*.pyx -I aiohttp
+      rm -rf .git
 
-- name: Python Build
-  runs: |
-    python setup.py build
+  - name: Python Build
+    runs: |
+      python setup.py build
 
-- name: Python Install
-  runs: |
-    python setup.py install --prefix=/usr --root="${{targets.destdir}}"
+  - name: Python Install
+    runs: |
+      python setup.py install --prefix=/usr --root="${{targets.destdir}}"
 
-- uses: strip
+  - uses: strip
 
 update:
   enabled: true
   release-monitor:
     identifier: 6713
+
 test:
   environment:
     contents:
       packages:
-      - busybox
+        - busybox
   pipeline:
-  - runs: |
-      LIBRARY="aiohttp"
-      python3 -c "import $LIBRARY" 2>/dev/null
-      status=$?
+    - runs: |
+        LIBRARY="aiohttp"
+        python -c "import $LIBRARY" 2>/dev/null
 
-      if [ $status -eq 0 ]; then
-          echo "Library '$LIBRARY' is installed and can be imported successfully."
-          exit 0  # Exit with a status code of 0, indicating success
-      else
-          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
-          exit 1  # Exit with a non-zero status code, indicating failure
-      fi
+        if [ $? -eq 0 ]; then
+            echo "Library '$LIBRARY' is installed and can be imported successfully."
+            exit 0
+        else
+            echo "Failed to import library '$LIBRARY'. Please check if it is installed."
+            exit 1
