feat: update PyPy versions to 7.3.19 and add pip installation steps in YAML files for pypy-3.10 and pypy-3.11

diff --git a/pypy-3.10.yaml b/pypy-3.10.yaml
--- a/pypy-3.10.yaml
+++ b/pypy-3.10.yaml
@@ -2,13 +2,13 @@ package:
   name: pypy-3.10
   description: PyPy is a very fast and compliant implementation of the Python language v 3.10
   epoch: 0
-  version: 7.3.18
+  version: 7.3.19
   copyright:
     - license: Apache-2.0
+  options:
+    #  There is a dependency on cmd:pypy because of the pip install step
+    no-depends: true
   dependencies:
-    provides:
-      - pypy3=3.10.999
-      - pypy-3=3.10.999
     runtime:
       - bzip2-dev
       - ncurses
@@ -49,11 +49,7 @@ pipeline:
     with:
       repository: https://github.com/pypy/pypy.git
       tag: release-pypy${{vars.extracted-version}}-v${{package.version}}
-      expected-commit: e90335a7776c7e5f3f2a4f4d52848e447716b814
-
-  - uses: patch
-    with:
-      patches: 0001-refactor-update-type-definitions-and-improve-signal-.patch
+      expected-commit: 64367dfeb2639a9eabdcf1659f804efc47a783ce
 
   - working-directory: pypy/goal
     runs: |
@@ -61,38 +57,40 @@ pipeline:
 
   - runs: |
       mkdir -p ${{targets.contextdir}}/usr/bin
-      install -Dm755 pypy/goal/pypy${{vars.extracted-version}}-c "${{targets.contextdir}}"/usr/bin/pypy3
+      install -Dm755 pypy/goal/pypy${{vars.extracted-version}}-c "${{targets.contextdir}}"/usr/bin/pypy${{vars.extracted-version}}-c
       install -Dm755 pypy/goal/libpypy${{vars.extracted-version}}-c.so "${{targets.contextdir}}"/usr/bin/libpypy${{vars.extracted-version}}-c.so
-
-      # # Install symlinks
-      ln -s pypy3  ${{targets.contextdir}}/usr/bin/pypy
 
       rsync -r --exclude='__pycache__' --exclude='test' --exclude='tests' lib-python/ "${{targets.contextdir}}"/usr/lib-python/
       rsync -r --exclude='__pycache__' --exclude='*.c' --exclude '*.o' lib_pypy/ "${{targets.contextdir}}"/usr/lib_pypy/
       rsync -r --include='*.h' -f 'hide,! */' include/ "${{targets.contextdir}}"/usr/include/
 
+      ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/usr/bin/pypy
+
+  - uses: fetch
+    with:
+      uri: https://bootstrap.pypa.io/get-pip.py
+      expected-sha512: 4e04911474edb9df9dd2c40538fd7b164381c576d65a48c4555de240abc8a9a53f4e381eba6a93a07bc2339181b7530276a1a2648d7cc979dde759718ab20c37
+      extract: false
+      strip-components: 0
+
+  - runs: |
+      "${{targets.contextdir}}"/usr/bin/pypy${{vars.extracted-version}}-c get-pip.py setuptools wheel
+      sed -i '1s|.*|#!/usr/bin/env pypy|' ${{targets.contextdir}}/usr/bin/pip*
+
   - uses: strip
 
 subpackages:
-  - name: ${{package.name}}-dev
-    description: PyPy 3.10 development files
-    dependencies:
-      runtime:
-        - ${{package.name}}
-    pipeline:
-      - runs: |
-          mkdir -p "{{targets.contextdir}}"/usr/include
-          mv "${{targets.destdir}}"/usr/include/pypy-3.10/pyconfig.h "${{targets.contextdir}}"/usr/include/
-
   - name: ${{package.name}}-compat
     description: PyPy 3.10 compatibility layer
     pipeline:
       - runs: |
           mkdir -p ${{targets.contextdir}}/usr/local/bin/
           mkdir -p ${{targets.contextdir}}/opt/pypy/bin
-          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/usr/local/bin/pypy3
           ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/pypy3
+          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/usr/local/bin/pypy3
+          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/pypy
           ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/python
+          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/python3
     test:
       environment:
         contents:
@@ -100,21 +98,27 @@ subpackages:
             - ${{package.name}}
       pipeline:
         - runs: stat /opt/pypy/bin/pypy3
+        - runs: stat /opt/pypy/bin/pypy
         - runs: |
             export PATH=$PATH:/opt/pypy/bin
             pypy3 --version
 
 test:
+  environment:
+    contents:
+      packages:
+        - ${{package.name}}-compat
   pipeline:
     - name: "check version"
       uses: test/daemon-check-output
       with:
-        start: "pypy --version"
+        start: "pypy3 --version"
         timeout: 120
         expected_output: |
           PyPy ${{package.version}}
-    - runs: pypy -c "import os, sys, math, random, datetime; print('Modules OK')"
+    - runs: pypy3 -c "import os, sys, math, random, datetime; print('Modules OK')"
     - runs: |
+        export PATH=$PATH:/opt/pypy/bin
         cat <<EOF >test.py
         import time
 
@@ -133,6 +137,30 @@ test:
         test_pypy_jit()
         EOF
         pypy test.py
+    - runs: |
+        pip --version
+        pip --help
+        pip wheel --help
+        pip3 --version
+        pip3 --help
+        pip3 wheel --help
+    - name: "Check pip installation of a simple package"
+      runs: |
+        pip install requests
+        pypy -c "import requests; print('requests imported successfully')"
+    - name: "Verify pip list and show"
+      runs: |
+        pip list | grep requests
+        pip show requests
+    - name: "Uninstall the test package"
+      runs: |
+        pip uninstall -y requests
+        pypy -c "import requests" && echo "ERROR: requests not uninstalled" && exit 1 || echo "requests successfully uninstalled"
+    - name: "Check pip cache functionality"
+      runs: |
+        pip cache list | head -n 10
+        pip cache remove '*'
+        pip cache dir | xargs ls -al
 
 update:
   enabled: true
