Build Python 3.14 with free-threaded JIT export PYTHON_JIT=1 environment variable to enable it

diff --git a/python-3.14.yaml b/python-3.14.yaml
--- a/python-3.14.yaml
+++ b/python-3.14.yaml
@@ -1,7 +1,7 @@
 package:
   name: python-3.14
   version: "3.14.0"
-  epoch: 2
+  epoch: 3
   description: "the Python programming language"
   copyright:
     - license: PSF-2.0
@@ -19,15 +19,18 @@ environment:
       - busybox
       - bzip2-dev
       - ca-certificates-bundle
+      - clang-19
       - expat-dev
       - gdbm-dev
       - libcap-utils
       - libffi-dev
       - libx11-dev
       - linux-headers
+      - llvm-19
       - mpdecimal-dev
       - ncurses-dev
       - openssl-dev
+      - python3
       - readline-dev
       - sqlite-dev
       - tcl-dev
@@ -72,6 +75,7 @@ pipeline:
          --build=${{host.triplet.gnu}} \
          --target=${{host.triplet.gnu}} \
          --prefix=/usr \
+         --enable-experimental-jit=yes-off \
          --enable-ipv6 \
          --enable-loadable-sqlite-extensions \
          $([ -d /usr/lib/oldglibc ] || echo --enable-optimizations) \
@@ -155,11 +159,51 @@ subpackages:
     test:
       pipeline:
         - uses: test/tw/ldd-check
-        - runs: |
+        - name: Version check
+          runs: |
+            ${{vars.python}} version-check.py ${{package.version}}
+        - name: (free-threaded) Version check
+          runs: |
+            export PYTHON_JIT=1
             ${{vars.python}} version-check.py ${{package.version}}
         - name: Verify venv installs expected packages
           runs: |
             set +x
+            d=$(mktemp -d)
+            echo "$ ${{vars.python}} -m venv $d"
+            ${{vars.python}} -m venv "$d"
+            echo "$ $d/bin/pip list"
+            $d/bin/pip list | tee "$d/list.txt"
+            wd=/usr/share/python-wheels
+            for pkg in pip ; do
+              set -- "$wd"/$pkg-*.whl
+              [ $# -eq 1 ] || {
+                echo "ERROR: found $# wheels in $wd matching $pkg-*.whl";
+                exit 1;
+              }
+              [ -f "$1" ] || {
+                echo "ERROR: $wd/$pkg-*.whl ('$1') was not a file"
+                exit 1
+              }
+              # name is like pip-24.2-py3-none-any.whl. second token is version.
+              wheel=${1}
+              tmp=${wheel##*/}
+              tmp=${tmp#*-}
+              ver=${tmp%%-*}
+              if ! grep -q "${pkg}[ ]\+${ver}$" "$d/list.txt"; then
+                  echo "FAIL: did not find '$pkg==$ver' in venv"
+                  echo "pip list had:"
+                  sed 's,^,>,' "$d/list.txt"
+                  exit 1
+              fi
+              echo "PASS: venv installed '$pkg==$ver'"
+            done
+
+            rm -Rf "$d"
+        - name: (free-threaded) Verify venv installs expected packages
+          runs: |
+            set +x
+            export PYTHON_JIT=1
             d=$(mktemp -d)
             echo "$ ${{vars.python}} -m venv $d"
             ${{vars.python}} -m venv "$d"
@@ -237,6 +281,9 @@ subpackages:
           with:
             python: python${{vars.pyversion}}
             import: tkinter
+        - runs: |
+            export PYTHON_JIT=1
+            python${{vars.pyversion}} -c "import tkinter"
 
   - name: "${{package.name}}-doc"
     description: "python3.14 documentation"
@@ -281,7 +328,20 @@ subpackages:
 
 test:
   pipeline:
-    - runs: |
+    - name: Verify Python names
+      runs: |
+        # main package should provide 'python' and 'python3'.
+        python version-check.py ${{package.version}}
+        python3 version-check.py ${{package.version}}
+        pydoc3 --version
+        pydoc3 --help
+        python --version
+        python --help
+        python3 --version
+        python3 --help
+    - name: (free-threaded) Verify Python names
+      runs: |
+        export PYTHON_JIT=1
         # main package should provide 'python' and 'python3'.
         python version-check.py ${{package.version}}
         python3 version-check.py ${{package.version}}
@@ -293,6 +353,14 @@ test:
         python3 --help
     - name: Verify working python3 -m venv
       runs: |
+        d=$(mktemp -d)
+        python3 -m venv "$d"
+        $d/bin/pip list
+        $d/bin/pip check
+        rm -Rf "$d"
+    - name: (free-threaded) Verify working python3 -m venv
+      runs: |
+        export PYTHON_JIT=1
         d=$(mktemp -d)
         python3 -m venv "$d"
         $d/bin/pip list
