Address feedback

diff --git a/qemu.yaml b/qemu.yaml
--- a/qemu.yaml
+++ b/qemu.yaml
@@ -241,9 +241,17 @@ subpackages:
 
           chmod ugo+x binfmt-install
           ./binfmt-install ${{targets.contextdir}} ${{build.arch}} aarch64 i386 x86_64
-          # keep /usr/share/qemu/binfmt.d which are just inert files
+          # binfmt-install creates .conf files in /usr/share/qemu/binfmt.d and
+          # symlinks to those files in usr/lib/binfmt.d. This package will
+          # contain only the conf files.
+          # Remove the usr/lib/binfmt.d files that are packaged in -user-binfmt below.
           rm -Rf ${{targets.contextdir}}/usr/lib/binfmt.d/
+      - uses: strip
     test:
+      environment:
+        contents:
+          packages:
+            - file
       pipeline:
         - uses: test/tw/ver-check
           with:
@@ -253,6 +261,25 @@ subpackages:
           with:
             bins: qemu-aarch64 qemu-i386 qemu-x86_64
             help-flag: -h
+        - name: "should be static"
+          runs: |
+            set +x
+            errors=""
+            set -- /usr/bin/qemu-*
+            for bin in "$@"; do
+                out=$(file "$bin") || {
+                  echo "ERROR: 'file $bin' exited $?";
+                  errors="${errors} $bin";
+                  continue;
+                }
+                echo "$out" | grep -q static-pie || {
+                  echo "ERROR: 'file $bin' did not contain 'static-pie': $out"
+                  errors=$((errors+1))
+                  continue
+                }
+            done
+            [ -z "$errors" ] || { echo "FATAL: found errors in ${errors}"; exit 1; }
+            echo "PASS: static executables [$*]"
 
   - name: ${{package.name}}-user-binfmt
     description: "binfmt files for qemu-user"
@@ -261,8 +288,9 @@ subpackages:
         - ${{package.name}}-user
     pipeline:
       - runs: |
-          # package the symlinks to qemu-user that systemd-binfmt.service(8) will see
-          # but remove the targets of those symlinks whic are provided by qemu-user
+          # package the symlinks in usr/lib/binfmt.d that systemd-binfmt.service(8) will use,
+          # but remove the targets of those symlinks which are provided by qemu-user
+          # which is a runtime dependency.
           chmod ugo+x binfmt-install
           ./binfmt-install ${{targets.contextdir}} ${{build.arch}} aarch64 i386 x86_64
           rm -Rf ${{targets.contextdir}}/usr/share/qemu/binfmt.d/
