qemu: ensure that smoke tests dont output garbled text + use autoconf pipeline + be explicit about what options we want
Signed-off-by: Arthur Exaltação <arthur.exaltacao@chainguard.dev>

diff --git a/qemu.yaml b/qemu.yaml
--- a/qemu.yaml
+++ b/qemu.yaml
@@ -1,7 +1,7 @@
 package:
   name: qemu
   version: "10.0.2"
-  epoch: 1
+  epoch: 2
   description: "fast processor emulator"
   copyright:
     - license: GPL-2.0
@@ -28,7 +28,6 @@ environment:
       - liburing-dev
       - ncurses
       - ncurses-dev
-      - ninja-build
       - perl
       - pixman-dev
       - py3-packaging
@@ -47,12 +46,22 @@ pipeline:
       expected-commit: ff3419cbacdc9ad0715c716afeed65bb21a2bbbc
       tag: v${{package.version}}
 
+  - uses: autoconf/configure
+    with:
+      opts: |
+        --enable-system \
+        --enable-slirp \
+        --enable-linux-aio \
+        --enable-linux-io-uring \
+        --enable-vnc \
+        --target-list=x86_64-softmmu,aarch64-softmmu \
+        --prefix=/usr
+
+  - uses: autoconf/make
+
+  - uses: autoconf/make-install
+
   - runs: |
-      mkdir build
-      cd build
-      ../configure --enable-system --enable-slirp --enable-vnc --target-list=x86_64-softmmu,aarch64-softmmu --prefix=${{targets.destdir}}/usr
-      make -j$(nproc)
-      make install
       # Remove this firmware file, which we don't need, but requires so:dld.sl, which we don't have
       rm -f ${{targets.destdir}}/usr/share/qemu/hppa-firmware64.img
       # Can't use strip pipeline; there are some binaries that melange can't strip,
@@ -64,11 +73,17 @@ subpackages:
     description: "QEMU iPXE roms"
     pipeline:
       - runs: |
-          set -x
           mkdir -p "${{targets.subpkgdir}}"/usr/share/qemu/
           for i in e1000 e1000e eepro100 ne2k_pci pcnet rtl8139 virtio vmxnet3; do
             mv "${{targets.destdir}}"/usr/share/qemu/efi-$i.rom "${{targets.subpkgdir}}"/usr/share/qemu/
           done
+    test:
+      pipeline:
+        - name: Ensure that ROMs got properly moved
+          runs: |
+            for i in e1000 e1000e eepro100 ne2k_pci pcnet rtl8139 virtio vmxnet3; do
+              stat "/usr/share/qemu/efi-$i.rom"
+            done
 
   - name: ${{package.name}}-utils # in Alpine this is qemu-img
     description: "QEMU utils"
@@ -82,15 +97,16 @@ subpackages:
     test:
       pipeline:
         - runs: |
-            qemu-img --version
-            qemu-img --help
+            qemu-img --version | grep "${{package.version}}"
+            qemu-img --help | grep "QEMU disk image utility"
+            qemu-io --version | grep "${{package.version}}"
+            qemu-io --help | grep "QEMU Disk exerciser"
+            qemu-nbd --version | grep "${{package.version}}"
+            qemu-nbd --help | grep "QEMU Disk Network Block Device Utility"
+            qemu-storage-daemon --version | grep "${{package.version}}"
+            qemu-storage-daemon --help | grep "QEMU storage daemon"
             qemu-img create -f qcow2 disk1.img 1G
-            qemu-io --version
-            qemu-io --help
-            qemu-nbd --version
-            qemu-nbd --help
-            qemu-storage-daemon --version
-            qemu-storage-daemon --help
+            stat disk1.img
 
   - name: ${{package.name}}-system-x86_64
     description: "QEMU x86 system"
@@ -99,7 +115,6 @@ subpackages:
         - ${{package.name}}-ipxe
     pipeline:
       - runs: |
-          set -x
           mkdir -p "${{targets.subpkgdir}}"/usr/bin
           mv "${{targets.destdir}}"/usr/bin/qemu-system-x86_64 "${{targets.subpkgdir}}"/usr/bin/
 
@@ -117,8 +132,8 @@ subpackages:
             - curl
       pipeline:
         - runs: |
-            qemu-system-x86_64 --version
-            qemu-system-x86_64 --help
+            qemu-system-x86_64 --version | grep "${{package.version}}"
+            qemu-system-x86_64 --help | grep "usage: qemu-system-x86_64"
 
             # Basic test to launch a kernel with QEMU
             #
@@ -150,7 +165,7 @@ subpackages:
           mv "${{targets.destdir}}"/usr/share/qemu/edk2-aarch64-code.fd "${{targets.subpkgdir}}"/usr/share/qemu/
 
           # arm vars are same as format as aarch64, but this is easier for consumer.
-          cp "${{targets.destdir}}"/usr/share/qemu/edk2-arm-vars.fd "${{targets.subpkgdir}}"/usr/share/qemu/edk2-aarch64-vars.fd
+          install -Dpm0644 "${{targets.destdir}}"/usr/share/qemu/edk2-arm-vars.fd "${{targets.subpkgdir}}"/usr/share/qemu/edk2-aarch64-vars.fd
     test:
       environment:
         contents:
@@ -158,8 +173,8 @@ subpackages:
             - curl
       pipeline:
         - runs: |
-            qemu-system-aarch64 --version
-            qemu-system-aarch64 --help
+            qemu-system-aarch64 --version | grep "${{package.version}}"
+            qemu-system-aarch64 --help | grep "usage: qemu-system-aarch64"
             # Basic test to launch a kernel with QEMU
             #
             # First download a kernel from Alpine. Based on:
@@ -179,15 +194,18 @@ test:
     - uses: test/pkgconf
     - runs: |
         for i in /usr/bin/qemu-system-*; do
-          $i --help 2>/dev/null && echo "$i --> OKAY" || echo "$i --> FAIL"
-          $i --version 2>/dev/null && echo "$i --> OKAY" || echo "$i --> FAIL"
+          {
+            $i --help | grep "QEMU emulator"
+          } 2>/dev/null && echo "$i --> OKAY" || echo "$i --> FAIL"
+          {
+            $i --version | grep "${{package.version}}"
+          } 2>/dev/null && echo "$i --> OKAY" || echo "$i --> FAIL"
         done
-        qemu-edid version
-        qemu-edid help
-        qemu-ga --version
-        qemu-ga --help
-        qemu-pr-helper --version
-        qemu-pr-helper --help
+        qemu-edid -h | grep "test tool for the qemu edid generator"
+        qemu-ga --version | grep "${{package.version}}"
+        qemu-ga --help | grep "QEMU Guest Agent"
+        qemu-pr-helper --version | grep "${{package.version}}"
+        qemu-pr-helper --help | grep "Persistent Reservation helper program"
 
 update:
   enabled: true
