enable libquiche
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/quiche.yaml b/quiche.yaml
--- a/quiche.yaml
+++ b/quiche.yaml
@@ -51,15 +51,16 @@ pipeline:
 
   - uses: strip
 
-# subpackages:
-#   - name: libquiche
-#     pipeline:
-#       - runs: |
-#           mkdir -p ${{targets.subpkgdir}}/usr/lib
-#           mv ${{targets.destdir}}/usr/lib/libquiche.so* ${{targets.subpkgdir}}/usr/lib/
-#     test:
-#       pipeline:
-#         - uses: test/tw/ldd-check
+subpackages:
+  - name: libquiche
+    pipeline:
+      - runs: |
+          mkdir -p ${{targets.subpkgdir}}/usr/lib
+          mv ${{targets.destdir}}/usr/lib/libquiche.so* ${{targets.subpkgdir}}/usr/lib/
+    test:
+      pipeline:
+        - uses: test/tw/ldd-check
+
 update:
   enabled: true
   github:
@@ -79,7 +80,13 @@ test:
         quiche-server --help
     - name: Basic connection test
       runs: |
-        quiche-client https://cloudflare-quic.com/ --no-verify --max-data 1000 2> /dev/null 2>&1 | grep -q "HTTP/3 using NGINX and quiche"
+        response=$(quiche-client https://cloudflare-quic.com/ --no-verify)
+        if echo "$response" | grep -i "HTTP/3 using NGINX and quiche"; then
+          echo "Connection successful"
+        else
+          echo "Connection failed: $response"
+          exit 1
+        fi
     - name: "Spin up local server and client round-trip"
       uses: test/daemon-check-output
       with:
