build with nodejs-14
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>
Co-authored-by: RJ Sampson <rj.sampson@chainguard.dev>
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/rancher-ui-2.10.yaml b/rancher-ui-2.10.yaml
--- a/rancher-ui-2.10.yaml
+++ b/rancher-ui-2.10.yaml
@@ -1,6 +1,6 @@
 package:
   name: rancher-ui-2.10
-  version: "2.10.3"
+  version: "2.10.4"
   epoch: 0
   description: Rancher UI
   copyright:
@@ -15,9 +15,8 @@ environment:
       - ca-certificates-bundle
       - curl
       - git
-      - node-gyp
-      - nodejs-16
       - npm
+      - nvm
       - perl
       - py3-supported-build-base-dev
       - python-3.10
@@ -35,11 +34,22 @@ pipeline:
       recurse-submodules: true
 
   - runs: |
+      # Nothing newer version of nodejs is working with node-sass
+      source /usr/share/nvm/nvm.sh
+      nvm install v14
+      nvm use v14
       # node-saas 4.14.1 is not compatible with python3
       # https://github.com/nodejs/node-gyp/issues/1687#issuecomment-541471076
-      sed -i 's/"node-sass": "4.14.1"/"node-sass": "5.0.0"/g' package.json
+      # https://github.com/sass/node-sass/issues/2877#issuecomment-644912064
+      sed -i 's/"node-sass": "4.14.1"/"node-sass": "8.0.0"/g' package.json
       PYTHON=/usr/bin/python3 yarn --pure-lockfile --non-interactive install
       yarn build-static -f -v ${{package.version}}
+
+  - name: Install files
+    runs: |
+      mkdir -p ${{targets.destdir}}/usr/share/rancher/ui
+      cp -r dist/static/${{package.version}}/* ${{targets.destdir}}/usr/share/rancher/ui
+      cp -r public/* ${{targets.destdir}}/usr/share/rancher/ui
 
   - uses: strip
 
@@ -50,3 +60,39 @@ update:
     strip-prefix: v
     tag-filter: v2.10.
     use-tag: true
+
+test:
+  environment:
+    contents:
+      packages:
+        - rancher-api-ui # Check if rancher-api-ui is properly installed without conflicts
+        - curl
+        - nodejs
+        - npm
+        - yarn
+        - wait-for-it
+  pipeline:
+    - runs: |
+        for f in assets translations engines-dist index.html robots.txt humans.txt crossdomain.xml; do
+          # File or folder must be present
+          [ -d /usr/share/rancher/ui/$f ] || [ -f /usr/share/rancher/ui/$f ] || {
+            echo "File or folder /usr/share/rancher/ui/$f not found"
+            exit 1
+          }
+          # Size must be greater than 0
+          [ $(du -s /usr/share/rancher/ui/$f | cut -f1) -gt 0 ] || {
+            echo "File or folder /usr/share/rancher/ui/$f is empty"
+            exit 1
+          }
+        done
+    - name: "Test UI"
+      uses: test/daemon-check-output
+      with:
+        start: "npx http-server /usr/share/rancher/ui -p 8080"
+        timeout: 60
+        expected_output: |
+          serving
+          Available on
+        post: |
+          wait-for-it -t 10 --strict localhost:8080 -- echo "Server is up"
+          curl http://localhost:8080/index.html | grep "releases.rancher.com/ui/${{package.version}}"
