re2: introduce a new main package tests
Introduce a new test for the main package.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/re2.yaml b/re2.yaml
--- a/re2.yaml
+++ b/re2.yaml
@@ -69,3 +69,16 @@ update:
       replace: '.'
   github:
     identifier: google/re2
+
+test:
+  pipeline:
+    - uses: test/tw/ldd-check
+    - name: "make sure we put the libre2.so file in the APK"
+      runs: |
+        dir="/usr/lib"
+        name="libre2.so"
+        if ! find "${dir}" -name "${name}*" | grep -q . ; then
+          echo "FAIL: no files with name '${name}' found in dir '${dir}'. This is unexpected." >&2
+          exit
+        fi
+        echo "PASS: files with name '${name}' found in dir '${dir}'. This is expected."
