fix: retry
Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/ruby3.4-fluentd-kubernetes-daemonset-1.17.yaml b/ruby3.4-fluentd-kubernetes-daemonset-1.17.yaml
--- a/ruby3.4-fluentd-kubernetes-daemonset-1.17.yaml
+++ b/ruby3.4-fluentd-kubernetes-daemonset-1.17.yaml
@@ -70,7 +70,10 @@ subpackages:
           bundle config set path ${{targets.contextdir}}/fluentd/vendor/bundle
           bundle config set clean 'true'
           bundle config set deployment 'true'
-          bundle install --gemfile ./Gemfile --jobs $(nproc)
+          # --retry doesn't seem to help with network issues, completely rerun the command
+          if ! bundle install --gemfile ./Gemfile --jobs $(nproc); then
+            bundle install --gemfile ./Gemfile --jobs $(nproc)
+          fi
           bundle config unset path
 
           # Copy gemfile
