ruby3.3-webrick: introduce package tests
Introduce package tests.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/ruby3.3-webrick.yaml b/ruby3.3-webrick.yaml
--- a/ruby3.3-webrick.yaml
+++ b/ruby3.3-webrick.yaml
@@ -41,6 +41,9 @@ pipeline:
 
   - uses: ruby/clean
 
+  - name: "cleanup empty /usr/bin directory"
+    runs: rm -rf ${{targets.destdir}}/usr/bin/
+
 update:
   enabled: true
   github:
@@ -52,3 +55,24 @@ var-transforms:
     match: ^ruby(\d\.\d+)-.*
     replace: $1
     to: rubyMM
+
+test:
+  pipeline:
+    - name: "verify some .rbs files are included in the package"
+      runs: |
+        dir="/usr/lib/ruby/gems/"
+        file="*.rbs"
+        if ! find "${dir}" -name "${file}" -type f | grep -q . ; then
+          echo "FAIL: unable to find $file files under $dir." >&2
+          exit 1
+        fi
+        echo "PASS: found some $file files under $dir"
+    - name: "verify some .gemspec files are included in the package"
+      runs: |
+        dir="/usr/lib/ruby/gems/"
+        file="*.gemspec"
+        if ! find "${dir}" -name "${file}" -type f | grep -q . ; then
+          echo "FAIL: unable to find $file files under $dir." >&2
+          exit 1
+        fi
+        echo "PASS: found some $file files under $dir"
