Fix patch, add melange tests, and remove hard-coded ruby versions
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/ruby3.2-io-event.yaml b/ruby3.2-io-event.yaml
--- a/ruby3.2-io-event.yaml
+++ b/ruby3.2-io-event.yaml
@@ -1,13 +1,19 @@
 package:
   name: ruby3.2-io-event
   version: 1.7.1
-  epoch: 0
+  epoch: 1
   description: An event loop.
   copyright:
     - license: MIT
   dependencies:
     runtime:
-      - ruby-3.2
+      - ruby-${{vars.php-version}}
+
+var-transforms:
+  - from: ${{package.name}}
+    match: ruby(\d+\.\d+)-.*$
+    replace: "$1"
+    to: php-version
 
 environment:
   contents:
@@ -16,8 +22,8 @@ environment:
       - busybox
       - ca-certificates-bundle
       - git
-      - ruby-3.2
-      - ruby-3.2-dev
+      - ruby-${{vars.php-version}}
+      - ruby-${{vars.php-version}}-dev
 
 vars:
   gem: io-event
@@ -49,3 +55,30 @@ update:
   github:
     identifier: socketry/io-event
     strip-prefix: v
+
+test:
+  environment:
+    contents:
+      packages:
+        - ruby-${{vars.php-version}}
+  pipeline:
+    - name: Verify Gem Installation
+      runs: |
+        # Check that the gem is installed
+        gem list | grep 'io-event'
+        if [ $? -ne 0 ]; then
+          echo "Test failed: io-event gem is not installed."
+          exit 1
+        else
+          echo "Test passed: io-event gem is installed."
+        fi
+    - name: Test Requiring the Gem
+      runs: |
+        # Try to require the gem in Ruby
+        ruby -e "require 'io/event'; puts 'io-event gem loaded successfully'"
+        if [ $? -ne 0 ]; then
+          echo "Test failed: Unable to require io-event gem."
+          exit 1
+        else
+          echo "Test passed: io-event gem can be required."
+        fi
