Add melange test
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/ruby3.2-protocol-http.yaml b/ruby3.2-protocol-http.yaml
--- a/ruby3.2-protocol-http.yaml
+++ b/ruby3.2-protocol-http.yaml
@@ -50,3 +50,20 @@ update:
     identifier: socketry/protocol-http
     strip-prefix: v
     use-tag: true
+
+test:
+  pipeline:
+    - name: "Check Gem Installation"
+      runs: |
+        if gem list | grep -q "${{vars.gem}}"; then
+          echo "${{vars.gem}} gem installed successfully."
+        else
+          echo "${{vars.gem}} gem installation failed!" && exit 1
+        fi
+    - name: "Test Functionality"
+      runs: |
+        ruby -r 'protocol/http' -e '
+        request = Protocol::HTTP::Request.new(nil, nil, "GET", "/")
+        request.headers.add("content-type", "application/json")
+        puts "Content-Type Header: " + request.headers["content-type"]
+        ' || (echo "${{vars.gem}} test failed!" && exit 1)
