add melange test
Signed-off-by: Mark McCormick <mark.mccormick@chainguard.dev>

diff --git a/ruby3.2-protocol-http.yaml b/ruby3.2-protocol-http.yaml
--- a/ruby3.2-protocol-http.yaml
+++ b/ruby3.2-protocol-http.yaml
@@ -50,3 +50,17 @@ update:
     identifier: socketry/protocol-http
     strip-prefix: v
     use-tag: true
+
+test:
+  pipeline:
+    - name: "Check Gem Installation"
+      runs: |
+        if gem list | grep -q "${{vars.gem}}"; then
+          echo "${{vars.gem}} gem installed successfully."
+        else
+          echo "${{vars.gem}} gem installation failed!" && exit 1
+        fi
+    - name: "Basic Load Test"
+      runs: |
+        ruby -e "require 'protocol/http'; puts 'protocol-http loaded successfully.'" || \
+        (echo "protocol-http load test failed!" && exit 1)
