ruby3.2-logstash-core: refresh package
Include tests, and remove empty directory.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/ruby3.2-logstash-core.yaml b/ruby3.2-logstash-core.yaml
--- a/ruby3.2-logstash-core.yaml
+++ b/ruby3.2-logstash-core.yaml
@@ -58,6 +58,10 @@ pipeline:
 
   - uses: ruby/clean
 
+  # for some reason we have an empty /usr/bin/ dir in this package
+  - name: "remove empty /usr/bin directory"
+    runs: rm -rf ${{targets.contextdir}}/usr/bin/
+
 vars:
   gem: logstash-core
 
@@ -72,3 +76,24 @@ var-transforms:
     match: ^ruby(\d\.\d+)-.*
     replace: $1
     to: rubyMM
+
+test:
+  pipeline:
+    - name: "verify some .rb files are included"
+      runs: |
+        dir="/usr/share/jruby/lib/ruby/gems/shared/gems/"
+        file="*.rb"
+        if ! find "${dir}" -name "${file}" | grep -q . ; then
+          echo "FAIL: no '${file}' files found under '${dir}'. This is unexpected." >&2
+          exit 1
+        fi
+        echo "PASS: '${file}' files found under '${dir}'. This is expected."
+    - name: "verify some .gemspec files are included"
+      runs: |
+        dir="/usr/share/jruby/lib/ruby/gems/shared/specifications/"
+        file="*.gemspec"
+        if ! find "${dir}" -name "${file}" | grep -q . ; then
+          echo "FAIL: no '${file}' files found under '${dir}'. This is unexpected." >&2
+          exit 1
+        fi
+        echo "PASS: '${file}' files found under '${dir}'. This is expected."
