initial commit
Signed-off-by: YashPimple <yashpimple22@gmail.com>

diff --git a/step-issuer.yaml b/step-issuer.yaml
--- a/step-issuer.yaml
+++ b/step-issuer.yaml
@@ -53,8 +53,40 @@ update:
     strip-prefix: v
 
 test:
+  environment:
+    contents:
+      packages:
+        - curl
+        - ca-certificates-bundle
   pipeline:
     - name: Run Help Command
       runs: |
         /usr/bin/step-issuer -h
         step-issuer --help
+    - name: "Setup KWOK cluster"
+      uses: test/kwok/cluster
+    - name: "Install CRDs"
+      runs: |
+        kubectl apply -f https://raw.githubusercontent.com/smallstep/step-issuer/refs/tags/v${{package.version}}/config/crd/bases/certmanager.step.sm_stepclusterissuers.yaml
+        kubectl apply -f https://github.com/smallstep/step-issuer/blob/v${{package.version}}/config/crd/bases/certmanager.step.sm_stepissuers.yaml
+    - name: "Functional Test"
+      uses: test/daemon-check-output
+      with:
+        setup: |
+          kubectl config view --minify --raw > /tmp/kubeconfig.yaml
+        start: |
+          step-issuer --logtostderr=true --zap-log-level=debug --disable-approval-check --metrics-addr=":8080" --kubeconfig=/tmp/kubeconfig.yaml > /tmp/contour.log 2>&1 &
+        timeout: 60
+        expected_output: |
+          starting manager
+          Starting metrics server
+          Starting Controller
+          Starting workers
+          Starting EventSource
+        post: |
+          if curl -sf http://localhost:8080/metrics | grep -q "controller_runtime_active_workers"; then
+            echo "Metrics endpoint is up and exporting metrics"
+          else
+            echo " Metrics endpoint check failed"
+            exit 1
+          fi
