Merge pull request #74136 from markusboehme/strace/enable-selinux
feat(strace): enable SELinux context enrichment

Export:  02ca06a09c2696b7784f46a734f4d4117d0fd178

diff --git a/strace.yaml b/strace.yaml
--- a/strace.yaml
+++ b/strace.yaml
@@ -1,7 +1,7 @@
 package:
   name: strace
   version: "7.0"
-  epoch: 0
+  epoch: 1
   description: Diagnostic, debugging and instructional userspace tracer
   copyright:
     - license: BSD-3-Clause
@@ -22,6 +22,7 @@ environment:
       - coreutils # GNU date - busybox date not sufficient.
       - elfutils-dev
       - gawk
+      - libselinux-dev
       - linux-headers~${{vars.major-minor-version}}
 
 var-transforms:
@@ -46,7 +47,8 @@ pipeline:
         --build=${{host.triplet.gnu}} \
         --enable-mpers=no \
         --enable-stacktrace=yes \
-        --with-libdw
+        --with-libdw \
+        --with-libselinux=yes
 
   - uses: autoconf/make
 
@@ -107,3 +109,14 @@ test:
         #   > /usr/lib/ld-linux...(_start+0x...) [0x...]
         strace -k /usr/bin/true 2>&1 \
             | grep -E '> /usr/lib/ld-linux.*\(_start[^)]*\) \[0x[[:xdigit:]]+\]'
+    - name: Test strace SELinux (secontext) support
+      runs: |
+        if ! strace -V | grep -F secontext; then
+            echo "FAIL: strace was built without SELinux support" >&2
+            exit 1
+        fi
+
+        # Exercise --secontext against a trivial command. Regardless of the
+        # host using or not using SELinux, strace must complete the strace
+        # and exit 0.
+        strace --secontext /usr/bin/true 2>&1
