Refreshed 3.9 references to 4.1 for update, cleaned up obsolete components

diff --git a/strimzi-kafka-operator.yaml b/strimzi-kafka-operator.yaml
--- a/strimzi-kafka-operator.yaml
+++ b/strimzi-kafka-operator.yaml
@@ -41,7 +41,7 @@ environment:
     DEST_DIR: opt/strimzi
 
 vars:
-  java-version: '17' # https://github.com/strimzi/strimzi-kafka-operator/blob/0.46.0/development-docs/DEV_GUIDE.md#java-versions
+  java-version: '17' # https://github.com/strimzi/strimzi-kafka-operator/blob/0.48.0/development-docs/DEV_GUIDE.md#java-versions
   shellcheck_version: 0.10.0
   shellcheck_aarch64_shasum512: 77abeaa8bee293264ebfd94a2021bd490695ed5518f2da7c0f9ec4b402cd1e5da6642a0e9f953961510cef7351cc9afae7c7a528a597d1befd1867b8c69e15b1
   shellcheck_x86_64_shasum512: 31006830087c2b9ffe9fa36c1ab4a8b11c85078cac8203265d0cfd630c70a4a506e66dd9d7ccde964360ad95045894149de457db34f10cad76708c7a4aa544ca
@@ -53,11 +53,6 @@ pipeline:
       tag: ${{package.version}}
       expected-commit: c643d5d7d56f664e4a1c2425113dc5a55854e192
 
-  - uses: patch
-    with:
-      # temporary hack from https://github.com/strimzi/strimzi-kafka-operator/commit/9a0f0ca37c63906b5e8ee29f6a686976884efe15
-      patches: move-access-operator-dependency-to-systemtest.patch
-
   - uses: maven/pombump
 
   - uses: maven/pombump
@@ -67,13 +62,13 @@ pipeline:
 
   - uses: maven/pombump
     with:
-      patch-file: pombump-deps-3.9.x.yaml
-      pom: docker-images/artifacts/kafka-thirdparty-libs/3.9.x/pom.xml
+      patch-file: pombump-deps-4.0.x.yaml
+      pom: docker-images/artifacts/kafka-thirdparty-libs/4.0.x/pom.xml
 
   - uses: maven/pombump
     with:
-      patch-file: pombump-deps-4.0.x.yaml
-      pom: docker-images/artifacts/kafka-thirdparty-libs/4.0.x/pom.xml
+      patch-file: pombump-deps-4.1.x.yaml
+      pom: docker-images/artifacts/kafka-thirdparty-libs/4.1.x/pom.xml
 
   - runs: |
       export JAVA_HOME="/usr/lib/jvm/default-jvm"
@@ -117,7 +112,6 @@ data:
       cluster-operator: cluster-operator
       kafka-init: kafka-init
       kafka-agent: kafka-agent
-      kafka-agent-3: kafka-agent-3
       topic-operator: topic-operator
       tracing-agent: tracing-agent
       user-operator: user-operator
@@ -148,8 +142,8 @@ subpackages:
         pipeline:
           - runs: |
               mkdir -p "${{targets.contextdir}}"/usr/lib/kafka/libs/
-              cp -r ./3.9.x/target/dependency/* "${{targets.contextdir}}"/usr/lib/kafka/libs/
               cp -r ./4.0.x/target/dependency/* "${{targets.contextdir}}"/usr/lib/kafka/libs/
+              cp -r ./4.1.x/target/dependency/* "${{targets.contextdir}}"/usr/lib/kafka/libs/
 
   - name: "${{package.name}}-kafka-thirdparty-libs-cc"
     description: "Required 3rd party libraries for the Cruise Control"
@@ -271,14 +265,13 @@ test:
         # Lib directory to check
         dir="/opt/strimzi/lib"
 
-        # Ensure both agent and agent-3 jars are present as long as strimzi-kafka supports kafka 3.x
-        for file in io.strimzi.kafka-agent-${{package.version}}.jar io.strimzi.kafka-agent-3-${{package.version}}.jar; do
-          if [ -f "$dir/$file" ]; then
-            echo "$file exists in $dir."
-          else
-            echo "Error: $file does not exist in $dir."
-            exit 1
-          fi
-        done
+        # agent-3 jars removed in 0.48.0, only check for agent jar
+        if [ -f "$dir/io.strimzi.kafka-agent-${{package.version}}.jar" ]; then
+          echo "$file exists in $dir."
+        else
+          echo "Error: $file does not exist in $dir."
+          exit 1
+        fi
+
 
         echo "All required files exist in $dir."
