test(strimzi-kafka): ensure agent[-3] jars exist
Signed-off-by: Kevin Monroe <kevin.monroe@chainguard.dev>

diff --git a/strimzi-kafka-operator.yaml b/strimzi-kafka-operator.yaml
--- a/strimzi-kafka-operator.yaml
+++ b/strimzi-kafka-operator.yaml
@@ -228,11 +228,24 @@ test:
         echo "Both directories are not empty."
     - name: check files are there
       runs: |
-        # Directory to check
+        # Bin directory to check
         dir="/opt/strimzi/bin"
 
         # Check if each file exists in the directory
         for file in cluster_operator_run.sh kafka_init_run.sh launch_java.sh tls_prepare_certificates.sh topic_operator_run.sh user_operator_run.sh; do
+          if [ -f "$dir/$file" ]; then
+            echo "$file exists in $dir."
+          else
+            echo "Error: $file does not exist in $dir."
+            exit 1
+          fi
+        done
+
+        # Lib directory to check
+        dir="/opt/strimzi/lib"
+
+        # Ensure both agent and agent-3 jars are present as long as strimzi-kafka supports kafka 3.x
+        for file in io.strimzi.kafka-agent-${{package.version}}.jar io.strimzi.kafka-agent-3-${{package.version}}.jar; do
           if [ -f "$dir/$file" ]; then
             echo "$file exists in $dir."
           else
