supervisor - Fix build failure, add a test and other cleanups.
- Fix build failure by depending on on python3 directly rather than indirectly
  previously it only got /usr/bin/python3 build-time dependency
  because of py3-pip, but py3-pip no longer explicitly depends on python3.
  So in order to use 'pip'

- move population of subpackage files to subpackage rather than
  installing them in the primary package and then moving them.

- copy the provided skel/sample.conf and "sedit" it rather than using
  bin/echo_supervisord_conf to provide it.

- fix a bug in shell where a lack of 'EOF' meant that the removal of
  'tests' directory did not actually get done.  Instead
  etc/logrotate.d/supervisord had shell syntax in it.

- do not install .pyc files

- fix bug in supervisor-openrc package where the shell HEREDOC was
  evaluated making the /etc/init.d/supervisord have unexpected content.

- add a `--help` test

diff --git a/supervisor.yaml b/supervisor.yaml
--- a/supervisor.yaml
+++ b/supervisor.yaml
@@ -1,7 +1,7 @@
 package:
   name: supervisor
   version: 4.2.5
-  epoch: 4
+  epoch: 5
   description: Supervisor process control system for Unix (supervisord)
   copyright:
     - license: BSD-3-Clause
@@ -15,6 +15,7 @@ environment:
     packages:
       - busybox
       - py3-pip
+      - python3
 
 pipeline:
   - uses: git-checkout
@@ -23,54 +24,12 @@ pipeline:
       repository: https://github.com/Supervisor/supervisor
       tag: ${{package.version}}
 
-  - name: Python Install
+  - uses: py/pip-build-install
+
+  - name: drop installed tests
     runs: |
-      sitepackages=$(python3 -c 'import site; print(site.getsitepackages()[0])')
-      concatenated_path="${{targets.destdir}}${sitepackages}"
-
-      echo "sitepackages=$sitepackages"
-      echo "concatenated_path=$concatenated_path"
-
-      if [ ! -d "$sitepackage" ]; then
-        echo "making site packages directory"
-        mkdir -p "${sitepackages}"
-      fi
-
-      if [ ! -d "$concatenated_path" ]; then
-        echo "making DESTDIR sitepackages directory"
-        mkdir -p "${concatenated_path}"
-      fi
-
-      mkdir -p "${{targets.destdir}}/etc/supervisor"
-      mkdir -p "${{targets.destdir}}/etc/supervisor/conf.d"
-      mkdir -p "${{targets.destdir}}/var/log/supervisor/"
-      mkdir -p "${{targets.destdir}}/etc/logrotate.d"
-      mkdir -p "${{targets.destdir}}/usr/bin/"
-
-      pip install supervisor
-
-      /usr/bin/echo_supervisord_conf > "${{targets.destdir}}/etc/supervisord.conf"
-      cat "${{targets.destdir}}/etc/supervisord.conf"
-      sed -i 's/\;files\s.*/files = supervisord.d\/*.conf/g' "${{targets.destdir}}/etc/supervisord.conf"
-      cat "${{targets.destdir}}/etc/supervisord.conf"
-
-      mv "${sitepackages}/supervisor" "${concatenated_path}"
-      mv /usr/bin/supervisord ${{targets.destdir}}/usr/bin/supervisord
-      mv /usr/bin/supervisorctl ${{targets.destdir}}/usr/bin/supervisorctl
-
-      cat >${{targets.destdir}}/etc/logrotate.d/supervisord <<EOF
-      /var/log/supervisor/*.log {
-        missingok
-        weekly
-        notifempty
-        nocompress
-      }
-
-      chmod 600 ${{targets.destdir}}/etc/supervisord.conf
-      chmod 644 ${{targets.destdir}}/etc/logrotate.d/supervisord
-
-      find "${{targets.destdir}}" -name "*.pyo" -exec rm -rf '{}' +
-      find "${{targets.destdir}}" -name "tests" -exec rm -rf '{}' +
+      # note that pip install does include tests but they are removed here.
+      find "${{targets.contextdir}}" -name "tests" -exec rm -vrf '{}' +
 
   - uses: strip
 
@@ -79,26 +38,34 @@ subpackages:
     description: Supervisor configuration
     pipeline:
       - runs: |
-          mkdir -p ${{targets.subpkgdir}}/etc
-          mv ${{targets.destdir}}/etc/supervisord.conf ${{targets.subpkgdir}}/etc/
+          mkdir -p "${{targets.contextdir}}/etc/logrotate.d"
+          cat >${{targets.contextdir}}/etc/logrotate.d/supervisord <<"EOF"
+          /var/log/supervisor/*.log {
+            missingok
+            weekly
+            notifempty
+            nocompress
+          }
+          EOF
+          chmod 644 ${{targets.contextdir}}/etc/logrotate.d/supervisord
 
-  - name: supervisor-pyc
-    description: Precompiled Python bytecode for supervisor
-    pipeline:
-      - runs: |
-          sitepackages=$(python3 -c 'import site; print(site.getsitepackages()[0])')
-          destdir_concatenated_path="${{targets.destdir}}${sitepackages}"
-          subpkg_concatenated_path="${{targets.subpkgdir}}${sitepackages}"
-          mkdir -p "${subpkg_concatenated_path}/supervisor/__pycache__/"
-          find "${destdir_concatenated_path}/supervisor/__pycache__/" -name "*.pyc" \
-            -exec mv {} "${subpkg_concatenated_path}/supervisor/__pycache__/" +
+          mkdir -p "${{targets.contextdir}}/etc"
+          cp supervisor/skel/sample.conf ${{targets.contextdir}}/etc/supervisord.conf
+          sed -i 's/\;files\s.*/files = supervisord.d\/*.conf/g' "${{targets.contextdir}}/etc/supervisord.conf"
+
+          if diff -u supervisor/skel/sample.conf ${{targets.contextdir}}/etc/supervisord.conf; then
+            echo "supervisor/skel/sample.conf and /etc/supervisord.conf did not differ"
+            exit 1
+          fi
+
+          chmod 600 ${{targets.contextdir}}/etc/supervisord.conf
 
   - name: supervisor-openrc
     description: system for controlling process state under UNIX (OpenRC init scripts)
     pipeline:
       - runs: |
-          mkdir -p "${{targets.subpkgdir}}/etc/init.d/"
-          cat >${{targets.subpkgdir}}/etc/init.d/supervisord <<EOF
+          mkdir -p "${{targets.contextdir}}/etc/init.d/"
+          cat >${{targets.contextdir}}/etc/init.d/supervisord <<"EOF"
           #!/sbin/openrc-run
 
           name="Supervisor"
@@ -110,7 +77,17 @@ subpackages:
 
           required_files="${configfile}"
           EOF
-          chmod 755 ${{targets.subpkgdir}}/etc/init.d/supervisord
+          chmod 755 ${{targets.contextdir}}/etc/init.d/supervisord
+
+test:
+  pipeline:
+    - name: run bins with --help
+      runs: |
+        set +x
+        for b in supervisorctl supervisord; do
+            echo "execute: $b --help"
+            $b --help 2>&1 || { echo "FAIL: '$b --help' exited $?"; exit 1; }
+        done
 
 update:
   enabled: true
