fix(zizmor): GHSA-65p9-r9h6-22vj
aws-lc-sys is a dependency of aws-lc-rs


Export:  0e2b5426c730c6510fb46907e6dd426093c00b52

diff --git a/systemd.yaml b/systemd.yaml
--- a/systemd.yaml
+++ b/systemd.yaml
@@ -1,6 +1,6 @@
 package:
   name: systemd
-  version: "259.5"
+  version: "259.3"
   epoch: 0
   description: The systemd System and Service Manager
   copyright:
@@ -100,7 +100,7 @@ pipeline:
     with:
       repository: https://github.com/systemd/systemd
       tag: v${{package.version}}
-      expected-commit: b3d8fc43e9cb531d958c17ef2cd93b374bc14e8a
+      expected-commit: 32bc9ae9f58aed3fa06e111b55fc157a3fe1322b
 
   # systemd-detect is currently broken for aarch64 GCP VM's https://github.com/systemd/systemd/pull/38125
   # https://github.com/chainguard-dev/internal-dev/issues/17776
@@ -191,6 +191,7 @@ subpackages:
             # 2025/03/28 11:52:30 INFO Assertion 'mkdtemp_malloc("/tmp/test-rm-rf.XXXXXXX", &d) >= 0' failed at src/test/test-rm-rf.c:19, function test_rm_rf_chmod_inner(). Aborting.
             # 2025/03/28 11:52:30 INFO (setresuid) terminated by signal ABRT.
             # 2025/03/28 11:52:30 INFO Assertion 'r >= 0' failed at src/test/test-rm-rf.c:100, function test_rm_rf_chmod(). Aborting.
+            # test-firewall-util - Assertion failed: "r = fw_nftables_add_masquerade(nfnl, true, AF_INET6, &u1, 128)" failed with unexpected error: -2/ENOENT
             # test-hostname-setup - does not work in Docker (Assertion failed: Expected "unshare(CLONE_NEWUTS)" to succeed, but got errno: 1/EPERM)
             /usr/lib/systemd/tests/run-unit-tests.py -u \
             -s test-sd-device \
@@ -208,6 +209,7 @@ subpackages:
             -s test-mount-util \
             -s test-bpf-foreign-programs \
             -s test-execute \
+            -s test-firewall-util \
             -s test-hostname-setup
 
   - range: standalone-binaries
@@ -813,6 +815,11 @@ test:
         - systemd-dev
         - libsystemd
   pipeline:
+    - runs: |
+        if [ '${{package.version}}-r${{package.epoch}}' != '259.3-r0' ]; then
+          echo 'Check if unit test test-firewall-util can be enabled now!'
+          exit 1
+        fi
     - uses: test/verify-service
       with:
         skip-files: syslog.socket # intentionally shipped without a corresponding service
