systemd: skip unit test test-firewall-util temporarily
The unit test test-firewall-util depends on various netfilter NAT
modules being available. Skip the test for now until a new Elastic
Build kernel has been deployed that brings those modules built-in.

Signed-off-by: Markus Boehme <markus.boehme@chainguard.dev>

diff --git a/systemd.yaml b/systemd.yaml
--- a/systemd.yaml
+++ b/systemd.yaml
@@ -190,6 +190,7 @@ subpackages:
             # 2025/03/28 11:52:30 INFO Assertion 'mkdtemp_malloc("/tmp/test-rm-rf.XXXXXXX", &d) >= 0' failed at src/test/test-rm-rf.c:19, function test_rm_rf_chmod_inner(). Aborting.
             # 2025/03/28 11:52:30 INFO (setresuid) terminated by signal ABRT.
             # 2025/03/28 11:52:30 INFO Assertion 'r >= 0' failed at src/test/test-rm-rf.c:100, function test_rm_rf_chmod(). Aborting.
+            # test-firewall-util - Assertion failed: "r = fw_nftables_add_masquerade(nfnl, true, AF_INET6, &u1, 128)" failed with unexpected error: -2/ENOENT
             /usr/lib/systemd/tests/run-unit-tests.py -u \
             -s test-sd-device \
             -s test-path-util \
@@ -205,7 +206,8 @@ subpackages:
             -s test-namespace \
             -s test-mount-util \
             -s test-bpf-foreign-programs \
-            -s test-execute
+            -s test-execute \
+            -s test-firewall-util
 
   - range: standalone-binaries
     name: ${{range.key}}-standalone
@@ -810,6 +812,11 @@ test:
         - systemd-dev
         - libsystemd
   pipeline:
+    - runs: |
+        if [ '${{package.version}}-r${{package.epoch}}' != '259-r0' ]; then
+          echo 'Check if unit test test-firewall-util can be enabled now!'
+          exit 1
+        fi
     - uses: test/verify-service
       with:
         skip-files: syslog.socket # intentionally shipped without a corresponding service
