tetragon - pin clang to 15 (#335583)
* tetragon - pin clang to 15

Apparently clang-17 breaks the bpf_*.o files on GKE.
See OS-3244 for details.

Export:  fd8ff12e2ce9fd12c44137180873a556b9b4e620

diff --git a/tetragon.yaml b/tetragon.yaml
--- a/tetragon.yaml
+++ b/tetragon.yaml
@@ -1,7 +1,7 @@
 package:
   name: tetragon
   version: "1.7.1"
-  epoch: 2 # CVE-2026-84445
+  epoch: 3 # pin clang to 15 for GKE (see OS-3244)
   description: "eBPF-based Security Observability and Runtime Enforcement"
   copyright:
     - license: Apache-2.0
@@ -14,6 +14,12 @@ package:
   resources:
     cpu: "14"
     memory: 18Gi
+  annotations:
+    toolchain-stream-reconcile-optout: true
+
+vars:
+  go-version: "1.27"
+  llvm-version: "15" # Pinned for GKE (see OS-3244)
 
 environment:
   environment:
@@ -21,18 +27,27 @@ environment:
   contents:
     packages:
       - bash-completion
-      - clang-17
+      - clang-${{vars.llvm-version}}
       - elfutils-dev
       - glibc-2.44-dev
-      - go-1.27
+      - go-${{vars.go-version}}
       - libbpf-dev
       - linux-headers
-      - llvm-17
+      - llvm-${{vars.llvm-version}}
       - make
       - pkgconf
       - zlib-dev
 
 pipeline:
+  - name: "Ensure we're still on clang-15"
+    # Specifically version 15, *not* ${{vars.llvm-version}}. This is apparently
+    # required for operating in GKE, but that might not be true in the future.
+    runs: |
+      if [ "$(clang --version | head -1 | awk '{split($4,a,"."); print a[1];}')" != "15" ]; then
+        echo "ERROR: Clang version doesn't match."
+        exit 1
+      fi
+
   - uses: git-checkout
     with:
       repository: https://github.com/cilium/tetragon
@@ -62,9 +77,9 @@ pipeline:
     with:
       packages: ./cmd/tetragon
       output: tetragon
+      go-package: go-${{vars.go-version}}
       ldflags: |
         -X github.com/cilium/tetragon/pkg/version.Version=${{package.version}}
-      go-package: go-1.27
 
   - name: Install BPF objects
     runs: |
@@ -79,6 +94,8 @@ pipeline:
       if [ -f examples/configuration/tetragon.yaml ]; then
         install -m 0644 examples/configuration/tetragon.yaml "${{targets.destdir}}/etc/tetragon/tetragon.yaml"
       fi
+
+  - uses: strip
 
 subpackages:
   - name: ${{package.name}}-bash-completion
@@ -113,9 +130,9 @@ subpackages:
         with:
           packages: ./cmd/tetra
           output: tetra
+          go-package: go-${{vars.go-version}}
           ldflags: |
             -X github.com/cilium/tetragon/pkg/version.Version=${{package.version}}
-          go-package: go-1.27
       - name: "Add tetragon bash completion scripts as per upstream"
         runs: |
           mkdir -p "${{targets.subpkgdir}}/etc/bash_completion.d"
@@ -141,9 +158,9 @@ subpackages:
         with:
           packages: ./operator
           output: tetragon-operator
+          go-package: go-${{vars.go-version}}
           ldflags: |
             -X github.com/cilium/tetragon/pkg/version.Version=${{package.version}}
-          go-package: go-1.27
     test:
       environment:
         contents:
@@ -168,7 +185,7 @@ subpackages:
         - name: "Test Tetragon Operator"
           uses: test/daemon-check-output
           with:
-            start: tetragon-operator serve --metrics-bind-address :2113 --health-probe-bind-address :"${OPERATOR_HEALTH_PORT}"
+            start: /usr/bin/tetragon-operator serve --metrics-bind-address :2113 --health-probe-bind-address :"${OPERATOR_HEALTH_PORT}"
             timeout: 20
             expected_output: |
               Starting Tetragon Operator
@@ -219,13 +236,14 @@ test:
         - mount
         - tetra=${{package.full-version}}
   pipeline:
+    - uses: test/tw/ldd-check
     - name: "Test Tetragon Daemon"
       uses: test/daemon-check-output
       with:
         setup: |
           mkdir -p /tmp
           mountpoint -q /sys/kernel/tracing || mount -t tracefs none /sys/kernel/tracing
-        start: tetragon --server-address "127.0.0.1:${SERVER_PORT}" --metrics-server ":${METRICS_PORT}" --export-filename "/tmp/tetragon.json" --log-format json >/tmp/tetragon.out
+        start: /usr/bin/tetragon --server-address "127.0.0.1:${SERVER_PORT}" --metrics-server ":${METRICS_PORT}" --export-filename "/tmp/tetragon.json" --log-format json >/tmp/tetragon.out
         timeout: 20
         expected_output: |
           Loaded sensor successfully
