fix(tomcat-10.1): Build packages for supported JDK versions
Allows us to bundle the correct JDK version with the package and run
tests for each supported JDK version at the package level

Pros:
  - Better test coverage
  - Easier at the image level to determine appopriate JDK version
  - Packages can be built with the appropriate JDK version without
    losing out on any potential enhancements from building with an older
    version

Cons:
  - In the case of Tomcat, we end up building the same package a couple
    times (same JDK version used at buildtime for 11, 17, and 21), and
    this will likley be an issue for other Java programs
      - Potential workaround here is even more subpackages, but then
        we're making things more complex, requiring duplicate code
        changes in a single package definition

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/tomcat-10.1.yaml b/tomcat-10.1.yaml
--- a/tomcat-10.1.yaml
+++ b/tomcat-10.1.yaml
@@ -10,6 +10,13 @@ package:
       - tomcat=${{package.full-version}}
       - tomcat-10=${{package.full-version}}
 
+data:
+  - name: openjdk-versions
+    items:
+      21: "openjdk-21"
+      17: "openjdk-17"
+      11: "openjdk-11"
+
 environment:
   contents:
     packages:
@@ -18,8 +25,6 @@ environment:
       - busybox
       - ca-certificates-bundle
       - openjdk-17
-  environment:
-    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
 
 pipeline:
   - uses: git-checkout
@@ -35,78 +40,77 @@ pipeline:
       compile.debug=false
       EOF
 
-  - runs: |
-      ant
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat
-      cp LICENSE ${{targets.destdir}}/usr/share/tomcat/
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/bin
-      cp output/build/bin/* ${{targets.destdir}}/usr/share/tomcat/bin
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/conf
-      cp output/build/conf/* ${{targets.destdir}}/usr/share/tomcat/conf
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/lib
-      cp output/build/lib/* ${{targets.destdir}}/usr/share/tomcat/lib
-
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/logs
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/temp
-      mkdir -p ${{targets.destdir}}/usr/share/tomcat/webapps
-
 subpackages:
-  # This package includes the manager and host-manager apps.
-  # The apps are not directly usable without copying into the webapps directory.
-  # See https://github.com/docker-library/tomcat/pull/181 for more context.
-  - name: ${{package.name}}-webapps
+  - range: openjdk-versions
+    name: ${{package.name}}-${{range.value}}
     dependencies:
-      provides:
-        - tomcat-webapps=${{package.full-version}}
-        - tomcat-10-webapps=${{package.full-version}}
       runtime:
-        - tomcat
+        - ${{range.value}}-default-jvm
+        - tomcat-native
     pipeline:
       - runs: |
-          mkdir -p ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist
-          cp -r output/build/webapps/* ${{targets.subpkgdir}}/usr/share/tomcat/webapps.dist/
+          export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
 
-test:
-  environment:
-    contents:
-      packages:
-        - ${{package.name}}-webapps
-        - curl
-        - default-jvm
-        - tomcat-native
-    environment:
-      LD_LIBRARY_PATH: "/usr/lib/tomcat-native"
-  pipeline:
-    - name: Start tomcat
-      uses: test/daemon-check-output
-      with:
-        setup: |
-          #!/bin/sh -ex
-          cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
-        start: "env JAVA_HOME=/usr/lib/jvm/default-jvm /usr/share/tomcat/bin/catalina.sh run"
-        timeout: 30
-        expected_output: |
-          Deploying.*sample.war
-          Server startup in
-        post: |
-          #!/bin/sh -e
-          url=http://localhost:8080/sample/
-          echo "testing $url"
-          response=$(curl -s "$url") || {
-            echo "curl $url failed $?"
-            exit 1
-          }
-          expected="Sample.*Hello.*World.*Application"
-          echo "$response" | grep -q "$expected" || {
-            echo "response from $url did not contain \"$expected\""
-            echo "response: $response"
-            exit 1
-          }
-          echo "found \"$expected\" in output of curl $url"
+          ant -Dskip.build.java.version=true
+
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat
+          cp LICENSE ${{targets.contextdir}}/usr/share/tomcat/
+
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/bin
+          cp output/build/bin/* ${{targets.contextdir}}/usr/share/tomcat/bin
+
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/conf
+          cp output/build/conf/* ${{targets.contextdir}}/usr/share/tomcat/conf
+
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/lib
+          cp output/build/lib/* ${{targets.contextdir}}/usr/share/tomcat/lib
+
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/logs
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/temp
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps
+
+          # This includes the manager and host-manager apps.
+          # The apps are not directly usable without copying into the webapps directory.
+          # See https://github.com/docker-library/tomcat/pull/181 for more context.
+          mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps.dist
+          rm -rf output/build/webapps/examples
+          cp -r output/build/webapps/* ${{targets.contextdir}}/usr/share/tomcat/webapps.dist/
+    test:
+      environment:
+        contents:
+          packages:
+            - curl
+        environment:
+          LD_LIBRARY_PATH: "/usr/lib/tomcat-native"
+      pipeline:
+        - name: Test tomcat with OpenJDK ${{range.key}}
+          uses: test/daemon-check-output
+          with:
+            setup: |
+              #!/bin/sh -ex
+              cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
+            start: "env JAVA_HOME=/usr/lib/jvm/java-${{range.key}}-openjdk /usr/share/tomcat/bin/catalina.sh run"
+            timeout: 30
+            expected_output: |
+              Tomcat/${{package.version}}
+              JVM.Version
+              Deploying.*sample.war
+              Server startup in
+            post: |
+              #!/bin/sh -e
+              url=http://localhost:8080/sample/
+              echo "testing $url"
+              response=$(curl -s "$url") || {
+                echo "curl $url failed $?"
+                exit 1
+              }
+              expected="Sample.*Hello.*World.*Application"
+              echo "$response" | grep -q "$expected" || {
+                echo "response from $url did not contain \"$expected\""
+                echo "response: $response"
+                exit 1
+              }
+              echo "found \"$expected\" in output of curl $url"
 
 update:
   enabled: true
