fix(tomcat): Make test part of build pipeline
There's a bug in melange where testing dependencies aren't added if
using a range to create subpackages

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/tomcat-10.1.yaml b/tomcat-10.1.yaml
--- a/tomcat-10.1.yaml
+++ b/tomcat-10.1.yaml
@@ -24,7 +24,11 @@ environment:
       - build-base
       - busybox
       - ca-certificates-bundle
+      - curl
+      - openjdk-21
       - openjdk-17
+      - openjdk-11
+      - tomcat-native
 
 pipeline:
   - uses: git-checkout
@@ -75,42 +79,46 @@ subpackages:
           mkdir -p ${{targets.contextdir}}/usr/share/tomcat/webapps.dist
           rm -rf output/build/webapps/examples
           cp -r output/build/webapps/* ${{targets.contextdir}}/usr/share/tomcat/webapps.dist/
-    test:
-      environment:
-        contents:
-          packages:
-            - curl
-        environment:
-          LD_LIBRARY_PATH: "/usr/lib/tomcat-native"
-      pipeline:
-        - name: Test tomcat with OpenJDK ${{range.key}}
-          uses: test/daemon-check-output
-          with:
-            setup: |
-              #!/bin/sh -ex
-              cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
-            start: "env JAVA_HOME=/usr/lib/jvm/java-${{range.key}}-openjdk /usr/share/tomcat/bin/catalina.sh run"
-            timeout: 30
-            expected_output: |
-              Tomcat/${{package.version}}
-              JVM.Version
-              Deploying.*sample.war
-              Server startup in
-            post: |
-              #!/bin/sh -e
-              url=http://localhost:8080/sample/
-              echo "testing $url"
-              response=$(curl -s "$url") || {
-                echo "curl $url failed $?"
-                exit 1
-              }
-              expected="Sample.*Hello.*World.*Application"
-              echo "$response" | grep -q "$expected" || {
-                echo "response from $url did not contain \"$expected\""
-                echo "response: $response"
-                exit 1
-              }
-              echo "found \"$expected\" in output of curl $url"
+      - name: Test tomcat with OpenJDK ${{range.key}}
+        uses: test/daemon-check-output
+        with:
+          setup: |
+            #!/bin/sh -ex
+            rm -rf /usr/share/tomcat/*
+            mkdir -p /usr/share/tomcat
+            cp -rf ${{targets.contextdir}}/usr/share/tomcat/* /usr/share/tomcat
+            cp /usr/share/tomcat/webapps.dist/docs/appdev/sample/sample.war /usr/share/tomcat/webapps/
+          start: |
+            sh -c "
+            if [[ "${{range.key}}" == "8" ]]; then
+              export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
+            else
+              export JAVA_HOME=/usr/lib/jvm/java-${{range.key}}-openjdk
+            fi
+            export LD_LIBRARY_PATH=/usr/lib/tomcat-native
+            /usr/share/tomcat/bin/catalina.sh run
+            "
+          timeout: 30
+          expected_output: |
+            Tomcat/${{package.version}}
+            JVM.Version
+            Deploying.*sample.war
+            Server startup in
+          post: |
+            #!/bin/sh -e
+            url=http://localhost:8080/sample/
+            echo "testing $url"
+            response=$(curl -s "$url") || {
+              echo "curl $url failed $?"
+              exit 1
+            }
+            expected="Sample.*Hello.*World.*Application"
+            echo "$response" | grep -q "$expected" || {
+              echo "response from $url did not contain \"$expected\""
+              echo "response: $response"
+              exit 1
+            }
+            echo "found \"$expected\" in output of curl $url"
 
 update:
   enabled: true
