trino: refresh plugin list and add tests
Refresh the plugin list, and add some additional tests.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/trino.yaml b/trino.yaml
--- a/trino.yaml
+++ b/trino.yaml
@@ -25,11 +25,11 @@ environment:
       - go
       - jvmkill
       - maven
+      - nodejs
+      - npm
       - openjdk-25-default-jdk
       - upx
       - wolfi-base
-      - nodejs
-      - npm
 
 pipeline:
   - uses: git-checkout
@@ -50,8 +50,7 @@ pipeline:
       export JAVA_HOME=/usr/lib/jvm/java-25-openjdk
       ./mvnw package
 
-  # NOTE: commented out for now, see what cve-scan reports
-  #- uses: maven/pombump
+  - uses: maven/pombump
 
   - name: "remove upstream artificial requirement for Oracle or Temurin JDKs"
     runs: |
@@ -87,34 +86,39 @@ pipeline:
 data:
   - name: plugins
     items:
+      ai-functions: ai-functions
       bigquery: bigquery
       blackhole: blackhole
       cassandra: cassandra
       clickhouse: clickhouse
       delta-lake: delta-lake
       druid: druid
+      duckdb: duckdb
       elasticsearch: elasticsearch
       exasol: exasol
       exchange-filesystem: exchange-filesystem
       exchange-hdfs: exchange-hdfs
       faker: faker
+      functions-python: functions-python
       geospatial: geospatial
       google-sheets: google-sheets
       hive: hive
       http-event-listener: http-event-listener
-      http-server-event-listener: http-server-event-listener
       hudi: hudi
       iceberg: iceberg
       ignite: ignite
       jmx: jmx
-      kafka: kafka
       kafka-event-listener: kafka-event-listener
+      kafka: kafka
+      lakehouse: lakehouse
+      ldap-group-provider: ldap-group-provider
+      loki: loki
       mariadb: mariadb
       memory: memory
       ml: ml
       mongodb: mongodb
-      mysql: mysql
       mysql-event-listener: mysql-event-listener
+      mysql: mysql
       opa: opa
       openlineage: openlineage
       opensearch: opensearch
@@ -123,12 +127,14 @@ data:
       pinot: pinot
       postgresql: postgresql
       prometheus: prometheus
+      ranger: ranger
       redis: redis
       redshift: redshift
       resource-group-managers: resource-group-managers
       session-property-managers: session-property-managers
       singlestore: singlestore
       snowflake: snowflake
+      spooling-filesystem: spooling-filesystem
       sqlserver: sqlserver
       teradata-functions: teradata-functions
       thrift: thrift
@@ -146,6 +152,14 @@ subpackages:
       - runs: |
           mkdir -p ${{targets.subpkgdir}}/etc
           cp -r core/docker/default/etc ${{targets.subpkgdir}}/etc/trino
+    test:
+      pipeline:
+        - name: "verify the package has at least one file in the directory tree"
+          runs: |
+            dir="/etc/trino"
+            if ! find "$dir" -type f -print -quit | grep -q . ; then
+              echo "FAIL: No files found in [$dir] directory." >&2
+            fi
 
   - name: ${{package.name}}-oci-entrypoint
     dependencies:
@@ -172,6 +186,13 @@ subpackages:
     test:
       pipeline:
         - uses: test/tw/ldd-check
+        - name: "verify main binary link is present and correctly configured"
+          runs: |
+            link="/usr/bin/run-trino"
+            if [ "$(readlink $link)" != "/usr/lib/trino/bin/run-trino" ] ; then
+              echo "FAIL: main binary link [$link] not correctly configured." >&2
+              exit 1
+            fi
 
   - range: plugins
     name: trino-plugin-${{range.key}}
@@ -189,6 +210,24 @@ subpackages:
             filename=$(basename $path)
             ln -s "../../lib/${filename}" "${{targets.subpkgdir}}/usr/lib/trino/plugin/${{range.value}}/${filename}"
           done
+    test:
+      pipeline:
+        - uses: test/tw/ldd-check
+        - name: "verify plugin JARs are correctly configured"
+          runs: |
+            dir="/usr/lib/trino/plugin/${{range.key}}/"
+            if ! find "$dir" -name "*.jar" -print -quit | grep -q . ; then
+              echo "FAIL: No .jar files found in [$dir] directory." >&2
+              exit 1
+            fi
+
+            find "$dir" -type l -name "*.jar" | while read -r link; do
+              target=$(readlink -f "$link")
+              if [ ! -e "$target" ]; then
+                echo "FAIL: Broken symlink [$link -> $target]." >&2
+                exit 1
+              fi
+            done
 
 update:
   enabled: true
