test: fix race condition in tshark

diff --git a/tshark-4.4.yaml b/tshark-4.4.yaml
--- a/tshark-4.4.yaml
+++ b/tshark-4.4.yaml
@@ -140,10 +140,24 @@ test:
       packages:
         - curl
   pipeline:
-    - name: Basic version check
+    - name: Verify installation
       runs: |
-        tshark --version
-    - name: Test help output
+        set -o pipefail
+        tshark --help | grep -F -e "Usage: tshark"
+        tshark --version | grep -F -e "${{package.version}}"
+    - name: Test packet capture
       runs: |
-        tshark --help
+        tshark -w /tmp/out.pcap -c 10 host example.com&
+        while [ ! -s /tmp/out.pcap ]; do sleep 1; done
+        curl -sI http://example.com
+        for i in $(seq 1 5); do
+          echo "Attempt $i: Checking for 200 OK in /tmp/out.pcap..."
+          if tshark -r /tmp/out.pcap -Y "http" 2>/dev/null | grep -q '200 OK'; then
+            echo "200 OK found"
+            exit 0
+          fi
+          sleep 1
+        done
+        echo "200 OK not found after multiple attempts."
+        exit 1
     - uses: test/tw/ldd-check
