test: add grep for basic tests update pcap url

diff --git a/tshark-4.4.yaml b/tshark-4.4.yaml
--- a/tshark-4.4.yaml
+++ b/tshark-4.4.yaml
@@ -78,18 +78,20 @@ subpackages:
         - uses: test/tw/ldd-check
         - name: Verify installation
           runs: |
-            editcap --help
-            editcap --version
+            set -o pipefail
+            editcap --help | grep -F -e "Usage: editcap"
+            editcap --version | grep -F -e "${{package.version}}"
         - name: Download a sample .pcap file
           runs: |
-            curl https://raw.githubusercontent.com/wireshark/wireshark/master/test/captures/http-ooo2.pcap -o /tmp/test.pcap
+            PCAP_FILE_URL="https://gitlab.com/wireshark/wireshark/-/raw/release-4.4/test/captures/http-ooo2.pcap?ref_type=heads&inline=false"
+            curl $PCAP_FILE_URL -o /tmp/test.pcap
         - name: Verify packet split
           runs: |
             cd /tmp
             no_of_packets=$(tcpdump -r test.pcap | wc -l)
             # splitting each packet into its own file
             editcap -c 1 test.pcap split.pcap
-            no_of_files=$(ls -1 split* | wc -l)
+            no_of_files=$(find -type f -iname 'split*' | wc -l)
             if [[ "$no_of_packets" -ne "$no_of_files" ]]; then
               echo "Error: Number of packets ($no_of_packets) does not match number of files ($no_of_files)."
               exit 1
@@ -104,7 +106,7 @@ subpackages:
             expected_packets=$((no_of_packets - 3))
             actual_packets=$(tcpdump -r remaining.pcap | wc -l)
             if [[ "$actual_packets" -ne "$expected_packets" ]]; then
-              echo "Error: Expected $expected_packets packets in remaining.pcap, but got $actual_packets."
+              echo "Error: Expected $expected_packets packets in remaining.pcap, but got $actual_packets packets."
               exit 1
             fi
             echo "Successfully verified discarding packets."
