feat(tshark): add editcap subpackage

diff --git a/tshark-4.4.yaml b/tshark-4.4.yaml
--- a/tshark-4.4.yaml
+++ b/tshark-4.4.yaml
@@ -1,13 +1,15 @@
 package:
   name: tshark-4.4
   version: "4.4.7"
-  epoch: 1
+  epoch: 2
   description: "TShark is a network protocol analyzer to dump and analyze network traffic"
   copyright:
     - license: GPL-2.0-only
   dependencies:
     provides:
       - tshark=${{package.full-version}}
+    runtime:
+      - ${{package.name}}-libs
 
 environment:
   contents:
@@ -45,6 +47,70 @@ pipeline:
   - uses: strip
 
 subpackages:
+  - name: ${{package.name}}-libs
+    dependencies:
+      provides:
+        - tshark-libs=${{package.full-version}}
+    pipeline:
+      - runs: |
+          mkdir -p "${{targets.subpkgdir}}"/usr/lib
+          mv "${{targets.destdir}}"/usr/lib/* "${{targets.subpkgdir}}"/usr/lib
+    description: ${{package.name}} libraries
+    test:
+      pipeline:
+        - uses: test/tw/ldd-check
+
+  - name: editcap
+    description: Edit and/or translate the format of capture files
+    dependencies:
+      runtime:
+        - ${{package.name}}-libs
+    pipeline:
+      - runs: |
+          install -Dm755 "${{targets.destdir}}/usr/bin/editcap" "${{targets.contextdir}}/usr/bin/editcap"
+    test:
+      environment:
+        contents:
+          packages:
+            - tcpdump
+            - curl
+      pipeline:
+        - uses: test/tw/ldd-check
+        - name: Verify installation
+          runs: |
+            editcap --help
+            editcap --version
+        - name: Download a sample .pcap file
+          runs: |
+            curl https://raw.githubusercontent.com/wireshark/wireshark/master/test/captures/http-ooo2.pcap -o /tmp/test.pcap
+        - name: Verify packet split
+          runs: |
+            cd /tmp
+            no_of_packets=$(tcpdump -r test.pcap | wc -l)
+            # splitting each packet into its own file
+            editcap -c 1 test.pcap split.pcap
+            no_of_files=$(ls -1 split* | wc -l)
+            if [[ "$no_of_packets" -ne "$no_of_files" ]]; then
+              echo "Error: Number of packets ($no_of_packets) does not match number of files ($no_of_files)."
+              exit 1
+            fi
+            echo "Successfully verified packet split."
+
+        - name: Verify discarding packets
+          runs: |
+            cd /tmp
+            no_of_packets=$(tcpdump -r test.pcap | wc -l)
+            # discard the first 3 packets
+            editcap -v test.pcap remaining.pcap 1-3
+            expected_packets=$((no_of_packets - 3))
+            actual_packets=$(tcpdump -r remaining.pcap | wc -l)
+            if [[ "$actual_packets" -ne "$expected_packets" ]]; then
+              echo "Error: Expected $expected_packets packets in remaining.pcap, but got $actual_packets."
+              exit 1
+            fi
+            echo "Successfully verified discarding packets."
+
+
   - name: tshark-4.4-privileged
     description: tshark with cap_net_raw and cap_net_admin capabilities set for running as nonroot user
     pipeline:
