utf8proc: refresh package tests
Refresh package tests.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/utf8proc.yaml b/utf8proc.yaml
--- a/utf8proc.yaml
+++ b/utf8proc.yaml
@@ -19,6 +19,10 @@ environment:
       - mpfr-dev
       - zlib-dev
 
+vars:
+  path: "/usr/lib"
+  sofile: "libutf8proc.so"
+
 pipeline:
   - uses: fetch
     with:
@@ -39,8 +43,11 @@ subpackages:
     description: utf8proc dev
     test:
       pipeline:
+        - name: "verify .so file link exists"
+          runs: readlink "${{vars.path}}/${{vars.sofile}}"
         - uses: test/pkgconf
         - uses: test/tw/ldd-check
+        - uses: test/tw/header-check
 
 update:
   enabled: true
@@ -48,3 +55,14 @@ update:
     identifier: JuliaLang/utf8proc
     strip-prefix: v
     tag-filter: v
+
+test:
+  pipeline:
+    - uses: test/tw/ldd-check
+    - name: "verify .so file exists"
+      runs: |
+        if ! find "${{vars.path}}" -name "${{vars.sofile}}*" | grep -q . ; then
+          echo "FAIL: could not find '${{vars.sofile}}' in '${{vars.path}}'. This is unexpected." >&2
+          exit 1
+        fi
+        echo "PASS: found '${{vars.sofile}}' in '${{vars.path}}'. This is expected."
