fix cve red and added test
Signed-off-by: debasishbsw <debasishbsws.dev@gmail.com>

diff --git a/vault-1.13.yaml b/vault-1.13.yaml
--- a/vault-1.13.yaml
+++ b/vault-1.13.yaml
@@ -30,7 +30,7 @@ pipeline:
 
   - uses: go/bump
     with:
-      deps: github.com/jackc/pgx@v4.18.2
+      deps: github.com/jackc/pgx/v4@v4.18.2
 
   - runs: |
       go mod tidy
@@ -95,3 +95,14 @@ update:
     identifier: hashicorp/vault
     strip-prefix: v
     tag-filter: v1.13.
+
+test:
+  pipeline:
+    - runs: |
+        output=$(vault version | grep ${{package.version}})
+        if [ -z "$output" ]; then
+          echo "Test failed: Output is empty"
+          exit 1
+        else
+          echo "Test passed: Output is not empty"
+        fi
