Add '--help' test to wavefront-proxy
Just a simple invocation of 'java -jar' to get help output
is would show the stacktrace fixed by the previous commit.

diff --git a/wavefront-proxy.yaml b/wavefront-proxy.yaml
--- a/wavefront-proxy.yaml
+++ b/wavefront-proxy.yaml
@@ -72,6 +72,29 @@ subpackages:
         - wavefront-proxy-config
         - wavefront-proxy-licenses
 
+test:
+  environment:
+    contents:
+      packages:
+        - busybox
+  pipeline:
+    - runs: |
+        set -- java -jar /usr/share/java/wavefront/wavefront-proxy/wavefront-proxy.jar
+        "$@" --help >out 2>&1 || {
+          rc=$?;
+          echo "failed [$rc]: $*"
+          cat out
+          exit $rc;
+        }
+        expected="Wavefront Proxy version ${{package.version}}"
+        grep "$expected" out || {
+          echo "command '$* --help' did not contain expected output"
+          echo "expected: $expected"
+          echo "actual:"
+          cat out
+          exit 1
+        }
+
 update:
   enabled: true
   github:
