Add tests to wolfi-base (#42429)
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>

diff --git a/wolfi-base.yaml b/wolfi-base.yaml
--- a/wolfi-base.yaml
+++ b/wolfi-base.yaml
@@ -21,5 +21,24 @@ pipeline:
     runs: |
       mkdir -p "${{targets.destdir}}"
 
+test:
+  pipeline:
+    - name: "Commands exist"
+      runs: |
+        for x in apk sh ; do
+          if ! which $x ; then
+            echo "$x not found"
+            exit 1
+          fi
+        done
+    - name: "Commands do not exist"
+      runs: |
+        for x in curl ; do
+          if which $x ; then
+            echo "$x not found"
+            exit 1
+          fi
+        done
+
 update:
   enabled: false
