Merge branch 'main' into staging-update-bot/os/db.yaml
Export:  f1619c422c09cf23b45bb441ae88011263901137

diff --git a/x265.yaml b/x265.yaml
--- a/x265.yaml
+++ b/x265.yaml
@@ -1,7 +1,7 @@
 package:
   name: x265
-  version: "4.1"
-  epoch: 8 # add exit 1 on encoding failure in test
+  version: "4.2"
+  epoch: 0 # add exit 1 on encoding failure in test
   description: H.265/HEVC encoder
   copyright:
     - license: GPL-2.0-only
@@ -19,14 +19,15 @@ environment:
       - gcc-14-default
       - nasm
 
+vars:
+  soversion: 216
+
 pipeline:
   - uses: git-checkout
     with:
       repository: https://bitbucket.org/multicoreware/x265_git.git
       tag: ${{package.version}}
-      expected-commit: 1d117bed4747758b51bd2c124d738527e30392cb
-      cherry-picks: |
-        master/b354c009a60bcd6d7fc04014e200a1ee9c45c167: Fix CMake build error with latest CMake 4.0 release
+      expected-commit: e444744c03978c1fb4e037168967020cf2648427
 
   - name: build 10bit static library
     uses: cmake/configure
@@ -80,9 +81,25 @@ pipeline:
     with:
       output-dir: 8bit
 
+  - runs: |
+      expected_sofile="libx265.so.${{vars.soversion}}"
+      if [ ! -f "${{targets.contextdir}}/usr/lib/$expected_sofile" ]; then
+        echo "ERROR: Build did not generate expected versioned .so file (wanted: $expected_sofile)"
+        echo "Found:"
+        ls ${{targets.contextdir}}/usr/lib/libx265.so.*
+        exit 1
+      fi
+
   - uses: strip
 
 subpackages:
+  - name: lib${{package.name}}-${{vars.soversion}}
+    pipeline:
+      - uses: split/lib
+    test:
+      pipeline:
+        - uses: test/tw/ldd-check
+
   - name: x265-dev
     pipeline:
       - uses: split/dev
