kwok: create sa token and ca.cert
Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>

diff --git a/pipelines/test/kwok/cluster.yaml b/pipelines/test/kwok/cluster.yaml
--- a/pipelines/test/kwok/cluster.yaml
+++ b/pipelines/test/kwok/cluster.yaml
@@ -45,3 +45,19 @@ pipeline:
 
       kubectl wait --for=condition=Ready nodes --all
       kubectl cluster-info
+
+  - name: Create ServiceAccount and Token
+    runs: |
+      #!/usr/bin/env bash
+      set -euo pipefail
+      # Create a ServiceAccount and Token for the kwokctl cluster, fix for:
+      # "Fail to create in-cluster Kubernetes config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"
+      export KUBERNETES_SERVICE_HOST=127.0.0.1
+      export KUBERNETES_SERVICE_PORT=32764
+      DIR=/var/run/secrets/kubernetes.io/serviceaccount
+      mkdir -p "$DIR"
+      kubectl create serviceaccount default --dry-run=client -o yaml | kubectl apply -f -
+      kubectl create token default > "$DIR"/token
+      CA=$(kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority}')
+      cp $CA "$DIR"/ca.crt
+      echo default > "$DIR/namespace"
