feat(py/bundle): Install from requirements file
Use a requirements file instead of passing dependencies directly to the
pipeline

Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/pipelines/py/bundle.yaml b/pipelines/py/bundle.yaml
--- a/pipelines/py/bundle.yaml
+++ b/pipelines/py/bundle.yaml
@@ -1,36 +1,48 @@
-name: Install Python packages with UV
+name: Install Python package bundles with uv
 
 needs:
   packages:
-    - python-${{inputs.python-version}}-base
+    - busybox
     - uv
 
 inputs:
-  dependencies:
-    description: "Indirect dependencies to install."
-    default: ""
   package:
-    description: "Name of packages to install."
-    required: true
-  python-version:
-    description: "Python version to use."
-    required: true
-  version:
-    description: "Version of package to install."
-    required: true
+    description: |
+      "Main package. Used to validate package version and requirements are in sync."
+    default: ""
+  python:
+    description: "Path to Python executable."
+    default: "/usr/bin/python3"
+  requirements:
+    description: "Path to requirements file."
+    default: "requirements.locked"
 
 pipeline:
   - runs: |
+      main_package=${{inputs.package}}
+
+      # If main package is unset, default to package name
+      if [ -z $main_package ]; then
+        main_package=${{package.name}}
+      fi
+
+      # Validate requirements contain main package at package version
+      if ! grep "$main_package==${{package.version}}" ${{inputs.requirements}}; then
+        echo "Failed to find $main_package at version ${{package.version}} in requirements!"
+        echo "Please update your requirements file at ${{package.name}}/${{inputs.requirements}}"
+        echo "To compile new requirements, use the py/compile-requirements pipeline."
+        exit 1
+      fi
+
       # Set Python version
-      export "UV_PYTHON=${{inputs.python-version}}"
+      export "UV_PYTHON=${{inputs.python}}"
 
       # Install package
       mkdir -p ${{targets.contextdir}}
       uv pip install \
         --config-file /etc/uv/uv.toml \
         --system --prefix ${{targets.contextdir}}/usr \
-        ${{inputs.package}}==${{inputs.version}} \
-        ${{inputs.dependencies}}
+        -r ${{inputs.requirements}}
 
       # Remove lockfile
       rm ${{targets.contextdir}}/usr/.lock
