Add 'prevent-inclusion' and build/ cleaning in pip-build-install pipeline (#33476)
Some packages were not co-installable because they included directories
in their site-packages/ directory that were not intended.

The root of the problem seems to be around behavior changes of 'build'
(called by 'pip wheel') when setuptools-scm is installed.

Fixes: https://github.com/wolfi-dev/os/issues/33397

diff --git a/pipelines/py/pip-build-install.yaml b/pipelines/py/pip-build-install.yaml
--- a/pipelines/py/pip-build-install.yaml
+++ b/pipelines/py/pip-build-install.yaml
@@ -13,6 +13,11 @@ inputs:
   needs-exe-named-python:
     description: Does the build actually need 'python' in its PATH
     default: false
+  prevent-inclusion:
+    description: |
+      prevent the provided filesystem entries from being included in
+      the wheel by means of hiding them from build.
+    required: false
 
 pipeline:
   - name: "pip build"
@@ -87,6 +92,16 @@ pipeline:
         fi
       fi
 
+      prevents="${{inputs.prevent-inclusion}}"
+      if [ -n "$prevents" ]; then
+         # do not allow expansion of prevents
+         ( set -f; vr tar -cpf "$tmpd/prevent-inclusion.tar" $prevents &&
+           vr rm -rf $prevents ) ||
+           { echo "ERROR: failed creation of prevent-inclusion.tar with $prevents"; exit 1; }
+         echo "prevented-inclusion of $prevents"
+      fi
+
+      [ -d build ] && hadbuild=true || hadbuild=false
       # --find-links to an empty dir and --no-index makes pip fully "offline"
       distwheelsd="$tmpd/dist-wheels"
       mkdir -p "$distwheelsd"
@@ -97,3 +112,13 @@ pipeline:
           "--find-links=$distwheelsd" --no-index --no-build-isolation --no-deps \
           --force-reinstall --no-compile --prefix=/usr "--root=$root" "$wd"/*.whl
       vr $py -m compileall --invalidation-mode=unchecked-hash -r100 "$root/$sitepkgd"
+
+      if [ "$hadbuild" = "false" -a -d build ]; then
+        vr rm -Rf build
+      fi
+      if [ -n "$prevents" ]; then
+        vr tar -xpf "$tmpd/prevent-inclusion.tar" ||
+          { echo "ERROR: failed restoring 'prevent-inclusion' files"; exit 1; }
+        echo "restored $prevents"
+      fi
+      exit 0
