drop python req from pip-build-install, move to pip-build-install, add tests
There are lots of changes here, centered around removing all occurences
of SETUPTOOLS_SCM_PRETEND_VERSION.  That seems to be not necessary now,
at least with the current pip-build-install workflow.

 * do not require 'python' setting in pip-build-install.  Default to
   using the target of the 'python3' link. If not present, user
   has to supply it.

   Also use contextdir rather than subpkgdir so it can be used from "main"
   packages also.

 * replace any packages that had SETUPTOOLS_SCM_PRETEND_VERSION with
   py/pip-build-install.

 * py3-cppy has a runtime dep on setuptools

 * Add tests to touched packages

 * Drop 'python3' runtime dep from touched packages.

 * Fix uninstallable py3-gcloud-aio-storage which conflicted with
   its dependency py3-gcloud-aio-auth as they both provided
   usr/lib/python3.12/site-packages/gcloud/py.typed

 * Fix the provides in py3-maturin-bin packages to provide py3-maturin-bin
   rather than just py3-maturin.  That also fixes py3-pendulum which
   was failing to build because it actually needs 'maturin' executable
   but that was not being provided by the 'py3-maturin' dep.

 * Fix pendulum's dependency that had py3-pytzdata, it's deps list 'tzdata'

 * Drop the now-unused py3-pytzdata

Note the 'python3' shell snippet in py3-rich and others is painful.
See https://github.com/wolfi-dev/os/issues/26818 for more context.

diff --git a/pipelines/py/pip-build-install-bootstrap.yaml b/pipelines/py/pip-build-install-bootstrap.yaml
--- a/pipelines/py/pip-build-install-bootstrap.yaml
+++ b/pipelines/py/pip-build-install-bootstrap.yaml
@@ -7,7 +7,7 @@ needs:
 inputs:
   python:
     description: which python to use
-    required: true
+    default: "DEFAULT"
   wheel:
     description: build a wheel?
     required: false
@@ -24,6 +24,27 @@ pipeline:
       pipzip=/usr/share/pip-zipapp/pip-zipapp.pyz
       [ -e "$pipzip" ] || { echo "missing pip-zip - $pipzip does not exist"; exit 1; }
       [ -f "$pipzip" ] || { echo "missing pip-zip - $pipzip is not a file"; exit 1; }
+      if [ "$py" = "DEFAULT" ]; then
+        if p=$(command -v python3); then
+          py=$p
+          if [ -L "$p" ]; then
+            py=$(readlink -f "$p") ||
+              { echo "ERROR: failed 'readlink -f $p'" 1>&2; exit 1; }
+          fi
+        else
+          glob="/usr/bin/python3.[0-9][0-9] /usr/bin/python3.[789]"
+          n=0
+          for p in $glob; do
+            [ -x "$p" ] && n=$((n+1)) && py=$p && found="$found $p"
+          done
+          if [ "$n" -ne 1 ]; then
+            echo "ERROR: must set inputs.python: " \
+                "found $n executables matching $glob" 1>&2
+            [ "$n" -eq 0 ] || echo "  found: $found" 1>&2
+            exit 1
+          fi
+        fi
+      fi
       pyver=$("$py" -c 'import sys; print("%s.%s" % (sys.version_info.major, sys.version_info.minor))')
       sitepkgd=$("$py" -c 'import site; print(site.getsitepackages()[0])')
       sitepkgd=${sitepkgd#/}
