Merge pull request #121758 from dannf/pipelines/test/pkgconf/PKG_CONFIG_PATH
feat: pipelines: test/pkgconf: Add support for paths in $PKG_CONFIG_PATH

Export:  2e52bf39c86d9b96b7520013913530331a30e9bc

diff --git a/pipelines/test/pkgconf.yaml b/pipelines/test/pkgconf.yaml
--- a/pipelines/test/pkgconf.yaml
+++ b/pipelines/test/pkgconf.yaml
@@ -17,9 +17,23 @@ pipeline:
         # Ensure this is a pkgconf .pc file
         if grep -q "^Name:" $pc_file; then
           lib_name=$(basename "$pc_file" ".pc")
-          # Ensure .pc file is installed in usr/lib/pkgconfig/*.pc or
-          # in usr/share/pkgconfig/*.pc
-          echo "$pc_file" | grep -q "^usr/lib/pkgconfig/${lib_name}.pc$\|^usr/share/pkgconfig/${lib_name}.pc$"
+          # Build list of valid pkgconfig paths
+          pc_paths="/usr/lib/pkgconfig /usr/share/pkgconfig"
+          if [ -n "$PKG_CONFIG_PATH" ]; then
+            # Append PKG_CONFIG_PATH directories
+            for path in $(echo "$PKG_CONFIG_PATH" | tr ':' ' '); do
+              pc_paths="$pc_paths $path"
+            done
+          fi
+          found=false
+          for path in $pc_paths; do
+            [ -e "${path}/${lib_name}.pc" ] || continue
+            found=true
+            break
+          done
+          if [ "$found" = "false" ]; then
+            echo "Error: $pc_file not in valid pkgconfig paths" && exit 1
+          fi
           # Try to get the library name from the pc filename
           # Run some package config tests, which will likely be used by
           # other packages that have build dependencies on this dev package
