virtualpackage: refresh variable names and messages
Update variable names and messages per the feedback in the PR.

Signed-off-by: Arturo Borrero Gonzalez <arturo.borrero@chainguard.dev>

diff --git a/pipelines/test/virtualpackage.yaml b/pipelines/test/virtualpackage.yaml
--- a/pipelines/test/virtualpackage.yaml
+++ b/pipelines/test/virtualpackage.yaml
@@ -3,17 +3,17 @@ name: virtualpackage
 # virtual packages should never be installed - instead one of the providing packages should be installed.
 # This package test ensures this remains true and does not regress.
 inputs:
-  virtual_pkg_name:
+  virtual-pkg-name:
     description: "virtual package name to test"
     required: true
-  real_pkg_name:
+  real-pkg-name:
     description: |
       if you want to ensure at least one of the real packages are installed, set its name here
     required: false
     default: ''
 
 pipeline:
-  - name: virtual package not installed
+  - name: virtual package checks
     description: Check that a virtual package does not install itself
     runs: |
       get_installed_version() {
@@ -21,23 +21,23 @@ pipeline:
         apk list installed "${pkg}" 2>/dev/null | awk '{print $1}'
       }
 
-      virtual_pkg_name_and_version="${{inputs.virtual_pkg_name}}-${{package.full-version}}"
-      maybe_installed_pkg_name_and_version="$(get_installed_version ${{inputs.virtual_pkg_name}})"
+      virtual_pkg_name_and_version="${{inputs.virtual-pkg-name}}-${{package.full-version}}"
+      maybe_installed_pkg_name_and_version="$(get_installed_version ${{inputs.virtual-pkg-name}})"
 
       if [ "${virtual_pkg_name_and_version}" == "${maybe_installed_pkg_name_and_version}" ] ; then
-        echo "${virtual_pkg_name_and_version} is installed. This is not expected, is a virtual package."
+        echo "FAIL: ${virtual_pkg_name_and_version} is installed." >&2
         exit 1
       fi
 
-      echo "${virtual_pkg_name_and_version} is not installed. This is expected, is a virtual package."
+      echo "PASS: ${virtual_pkg_name_and_version} is not installed."
 
-      if [ "${{inputs.real_pkg_name}}" != "" ] ; then
-        maybe_real_pkg_installed_name_and_version="$(get_installed_version ${{inputs.real_pkg_name}})"
+      if [ "${{inputs.real-pkg-name}}" != "" ] ; then
+        maybe_real_pkg_installed_name_and_version="$(get_installed_version ${{inputs.real-pkg-name}})"
         if [ "${maybe_real_pkg_installed_name_and_version}" != "" ] ; then
-          echo "${maybe_real_pkg_installed_name_and_version} is installed. This is expected, is a real package"
+          echo "PASS: ${maybe_real_pkg_installed_name_and_version} is installed."
           exit 0
         else
-          echo "No real package ${{inputs.real_pkg_name}} installed for virtual package ${{inputs.virtual_pkg_name}}. Unexpected."
+          echo "FAIL: No real package ${{inputs.real-pkg-name}} installed for virtual package ${{inputs.virtual-pkg-name}}." >&2
           exit 1
         fi
       fi
