chore(pipelines/auth): Prefer Octo STS over local tokens
Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/pipelines/auth/guarded-repo.yaml b/pipelines/auth/guarded-repo.yaml
--- a/pipelines/auth/guarded-repo.yaml
+++ b/pipelines/auth/guarded-repo.yaml
@@ -20,14 +20,17 @@ pipeline:
   - runs: |
       set -euo pipefail
 
-      # If guarded repo token exists locally, use that.
-      if [ -f /home/build/.guarded-repo.token ]; then
-        echo "Using local token for ${{inputs.repo}}"
+      # If we aren't able to authenticate using Octo STS, fall back to local token
+      if idtoken=$(curl --fail-with-body -sSL -H "Metadata-Flavor: Google" \
+                   http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=issuer.enforce.dev); then
+        echo "Using OctoSTS to get a token for ${{inputs.repo}} as ${{inputs.identity}}"
+        ghtoken=$(curl --fail-with-body -sSL -H "Authorization: Bearer ${idtoken}" 'https://octo-sts.dev/sts/exchange?scope=${{inputs.repo}}&identity=${{inputs.identity}}' | jq -r '.token')
+      elif [ -f /home/build/.guarded-repo.token ]; then
+        echo "Using local token for ${{inputs.repo}}"        
         ghtoken=$(cat /home/build/.guarded-repo.token)
       else
-        echo "Using OctoSTS to get a token for ${{inputs.repo}} as ${{inputs.identity}}"
-        idtoken=$(curl --fail-with-body -sSL -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=octo-sts.dev)
-        ghtoken=$(curl --fail-with-body -sSL -H "Authorization: Bearer ${idtoken}" "https://octo-sts.dev/sts/exchange?scope=${{inputs.repo}}&identity=${{inputs.identity}}" | jq -r .token)
+        echo "Unable to generate token for guarded repo!"
+        exit 1
       fi
 
       git config --global credential.helper store
