chore(pipelines/auth): Prefer Octo STS over local tokens
Signed-off-by: RJ Sampson <rj.sampson@chainguard.dev>

diff --git a/pipelines/auth/maven.yaml b/pipelines/auth/maven.yaml
--- a/pipelines/auth/maven.yaml
+++ b/pipelines/auth/maven.yaml
@@ -19,13 +19,15 @@ pipeline:
     runs: |
       set -euo pipefail
 
-      # If libraries token exists locally, use that.
-      # Fetch the token with: make lib-token
-      if [ -f /home/build/.libraries.token ]; then
+      # If we aren't able to authenticate using Octo STS, fall back to local token
+      if idtoken=$(curl --fail-with-body -sSL -H "Metadata-Flavor: Google" \
+                   http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=issuer.enforce.dev); then
+        cgtoken=$(curl --fail-with-body -sSL -H "Authorization: Bearer ${idtoken}" 'https://issuer.enforce.dev/sts/exchange?aud=libraries.cgr.dev&scope=${{inputs.group}}&identity=${{inputs.identity}}' | jq -r '.token')
+      elif [ -f /home/build/.libraries.token ]; then
         cgtoken=$(cat /home/build/.libraries.token)
       else
-        idtoken=$(curl --fail-with-body -sSL -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=issuer.enforce.dev)
-        cgtoken=$(curl --fail-with-body -sSL -H "Authorization: Bearer ${idtoken}" 'https://issuer.enforce.dev/sts/exchange?aud=libraries.cgr.dev&scope=${{inputs.group}}&identity=${{inputs.identity}}' | jq -r '.token')
+        echo "Unable to generate token for guarded libraries!"
+        exit 1
       fi
 
       echo "Removing local maven repository, if exists..."
